// Banque de questions « Connaissance de la société néerlandaise » (KNS, examen de base à l’étranger).
// Thèmes : les 7 thèmes officiels du KNS + la vie quotidienne (usages, circulation).
// Questions et réponses en néerlandais (comme à l'examen), traduction et explication en français.
// Chaque question : id stable, cat, q, qFr, opts[3], optsFr[3], corr (index), expl (FR).
// L'ordre des réponses est mélangé à l'affichage : la position de la bonne réponse ne compte pas.
// Dernière vérification du contenu : septembre 2026.

export const KNS_CATS = {
  wonen: { label: 'Géographie & logement', nl: 'Aardrijkskunde en wonen', icon: '🏠' },
  geschiedenis: { label: 'Histoire', nl: 'Geschiedenis', icon: '📜' },
  staat: { label: 'État, droits & démarches', nl: 'Staatsinrichting en rechtsstaat', icon: '🏛️' },
  taal: { label: 'La langue néerlandaise', nl: 'Nederlandse taal', icon: '💬' },
  onderwijs: { label: 'Enfants & école', nl: 'Opvoeding en onderwijs', icon: '🎒' },
  zorg: { label: 'Santé & soins', nl: 'Gezondheidszorg', icon: '🩺' },
  werk: { label: 'Travail & argent', nl: 'Werk en inkomen', icon: '💼' },
  usages: { label: 'Vie quotidienne & usages', nl: 'Omgangsvormen en dagelijks leven', icon: '🤝' },
};

const Q = (id, cat, q, qFr, opts, optsFr, corr, expl) => ({ id, cat, q, qFr, opts, optsFr, corr, expl });

import { KNS_PLUS } from './kns_plus.js';

const KNS_BASE = [
  Q('kns001', 'zorg', 'Je voelt je al een paar dagen ziek. Wie bel je voor een afspraak?', 'Vous êtes malade depuis quelques jours. Qui appelez-vous pour un rendez-vous ?',
    ['Het alarmnummer 112', 'De huisarts', 'Het ziekenhuis'], ['Le numéro d’urgence 112', 'Le médecin généraliste', 'L’hôpital'], 1,
    'Le médecin généraliste (huisarts) est toujours le premier contact médical aux Pays-Bas. On ne va pas directement à l’hôpital.'),
  Q('kns002', 'zorg', 'Wat heb je nodig om naar een specialist in het ziekenhuis te gaan?', 'De quoi avez-vous besoin pour voir un spécialiste à l’hôpital ?',
    ['Een verwijsbrief van de huisarts', 'Een brief van de gemeente', 'Niets, je maakt zelf een afspraak'], ['Une lettre d’orientation du généraliste', 'Une lettre de la commune', 'Rien, vous prenez rendez-vous vous-même'], 0,
    'Sans « verwijsbrief » (lettre d’orientation) du huisarts, le spécialiste ne vous reçoit pas et l’assurance ne rembourse pas.'),
  Q('kns003', 'zorg', 'Wanneer bel je 112?', 'Quand appelez-vous le 112 ?',
    ['Als je verkouden bent', 'Bij direct levensgevaar, brand of een misdrijf dat nu gebeurt', 'Als de apotheek dicht is'], ['Quand vous êtes enrhumé', 'En cas de danger de mort immédiat, d’incendie ou de crime en cours', 'Quand la pharmacie est fermée'], 1,
    'Le 112 (ambulance, pompiers, police) est réservé aux urgences où chaque seconde compte.'),
  Q('kns004', 'zorg', 'Wat is de huisartsenpost?', 'Qu’est-ce que la « huisartsenpost » ?',
    ['De receptie van het ziekenhuis', 'De eerste hulp van het ziekenhuis', 'De dienst voor dringende zorg ’s avonds, ’s nachts en in het weekend'], ['L’accueil de l’hôpital', 'Les urgences de l’hôpital', 'Le service médical de garde le soir, la nuit et le week-end'], 2,
    'En dehors des heures d’ouverture du généraliste, on appelle d’abord la huisartsenpost (HAP) pour un problème urgent mais pas vital.'),
  Q('kns005', 'zorg', 'Wie moet in Nederland een zorgverzekering hebben?', 'Qui doit avoir une assurance maladie aux Pays-Bas ?',
    ['Alleen mensen die werken', 'Iedereen die in Nederland woont of werkt', 'Alleen mensen ouder dan 65 jaar'], ['Seulement les personnes qui travaillent', 'Toute personne qui habite ou travaille aux Pays-Bas', 'Seulement les plus de 65 ans'], 1,
    'L’assurance maladie de base (basisverzekering) est obligatoire pour tous. À partir de 18 ans, on paie soi-même une prime mensuelle.'),
  Q('kns006', 'zorg', 'Moeten ouders premie betalen voor de zorgverzekering van hun kinderen onder de 18?', 'Les parents doivent-ils payer une prime d’assurance maladie pour leurs enfants de moins de 18 ans ?',
    ['Ja, hetzelfde bedrag als voor volwassenen', 'Nee, kinderen zijn gratis meeverzekerd bij hun ouders', 'Ja, de helft van het bedrag'], ['Oui, le même montant que pour un adulte', 'Non, les enfants sont assurés gratuitement avec leurs parents', 'Oui, la moitié du montant'], 1,
    'Les enfants de moins de 18 ans sont inscrits sur l’assurance d’un parent, sans prime à payer.'),
  Q('kns007', 'zorg', 'Wat is het eigen risico bij de zorgverzekering?', 'Qu’est-ce que l’« eigen risico » de l’assurance maladie ?',
    ['Het bedrag dat je per jaar zelf betaalt voordat de verzekering bepaalde zorg betaalt', 'De premie die je elke maand betaalt', 'Een boete als je te vaak naar de dokter gaat'], ['Le montant que vous payez vous-même chaque année avant que l’assurance rembourse certains soins', 'La prime que vous payez chaque mois', 'Une amende si vous allez trop souvent chez le médecin'], 0,
    'C’est une franchise annuelle obligatoire. Attention : la visite chez le huisarts n’entre pas dans l’eigen risico. Le montant change chaque année.'),
  Q('kns008', 'zorg', 'Waar haal je medicijnen die de huisarts heeft voorgeschreven?', 'Où allez-vous chercher les médicaments prescrits par le généraliste ?',
    ['Bij de supermarkt', 'Bij de apotheek', 'Bij de drogist'], ['Au supermarché', 'À la pharmacie', 'À la droguerie'], 1,
    'Les médicaments sur ordonnance s’obtiennent à la pharmacie (apotheek). La drogist ne vend que des produits sans ordonnance.'),
  Q('kns009', 'zorg', 'Je hebt veel kiespijn in het weekend. Wat doe je?', 'Vous avez très mal aux dents pendant le week-end. Que faites-vous ?',
    ['Je wacht tot maandag, want er is geen hulp', 'Je belt je tandarts; je hoort dan welke tandarts dienst heeft', 'Je belt 112'], ['Vous attendez lundi, il n’y a aucune aide', 'Vous appelez votre dentiste ; on vous indique le dentiste de garde', 'Vous appelez le 112'], 1,
    'Le répondeur de votre dentiste indique le dentiste de garde (spoedtandarts) pour le soir et le week-end.'),
  Q('kns010', 'zorg', 'Wat is een consult bij de huisarts?', 'Qu’est-ce qu’un « consult » chez le généraliste ?',
    ['Een operatie in het ziekenhuis', 'Een afspraak met de huisarts voor een gesprek en onderzoek', 'Een vaccinatie op school'], ['Une opération à l’hôpital', 'Un rendez-vous avec le généraliste pour un entretien et un examen', 'Une vaccination à l’école'], 1,
    'Une consultation dure environ 10 minutes. Préparez vos questions : on traite en général un seul problème par rendez-vous.'),

  Q('kns011', 'wonen', 'Je huurt een huis. Je wilt een muur in de woonkamer weghalen. Wat moet je doen?', 'Vous louez une maison. Vous voulez abattre un mur du salon. Que devez-vous faire ?',
    ['Dat mag je zelf beslissen', 'Eerst schriftelijke toestemming vragen aan de verhuurder', 'Alleen de buren informeren'], ['Vous pouvez décider seul', 'Demander d’abord l’accord écrit du propriétaire', 'Prévenir seulement les voisins'], 1,
    'Les gros travaux demandent l’accord du bailleur (verhuurder). Les petits changements (peindre l’intérieur, fixer une étagère) sont en général permis, mais il faut parfois tout remettre en état en partant.'),
  Q('kns012', 'wonen', 'Waar gooi je lege glazen flessen weg?', 'Où jetez-vous les bouteilles en verre vides ?',
    ['In de gft-bak', 'In de glasbak', 'In de papierbak'], ['Dans la poubelle à déchets organiques', 'Dans le conteneur à verre', 'Dans la poubelle à papier'], 1,
    'Le verre va dans la glasbak, souvent dans la rue ou près du supermarché.'),
  Q('kns013', 'wonen', 'Waar gooi je groente- en fruitafval weg?', 'Où jetez-vous les épluchures de légumes et de fruits ?',
    ['In de gft-bak', 'In de papierbak', 'In de glasbak'], ['Dans la poubelle à déchets organiques (gft)', 'Dans la poubelle à papier', 'Dans le conteneur à verre'], 0,
    'GFT = groente, fruit en tuinafval (légumes, fruits, jardin). Ces déchets sont compostés.'),
  Q('kns014', 'wonen', 'Je hebt een oude, kapotte kast. Wat doe je ermee?', 'Vous avez une vieille armoire cassée. Qu’en faites-vous ?',
    ['Je gooit hem in de gewone vuilnisbak', 'Je brengt hem naar de milieustraat, of je laat hem ophalen als grofvuil', 'Je zet hem op straat bij de bushalte'], ['Vous la mettez dans la poubelle normale', 'Vous l’apportez à la déchetterie, ou vous la faites enlever comme encombrant', 'Vous la déposez dans la rue près de l’arrêt de bus'], 1,
    'Les encombrants (grofvuil) vont à la milieustraat, ou la commune vient les chercher sur rendez-vous. Les déposer dans la rue peut coûter une amende.'),
  Q('kns015', 'wonen', 'Wat is huurtoeslag?', 'Qu’est-ce que la « huurtoeslag » ?',
    ['Een boete als je de huur te laat betaalt', 'Een bijdrage van de overheid in de huur voor mensen met een laag inkomen', 'Een extra bedrag dat je aan de verhuurder betaalt'], ['Une amende si vous payez le loyer en retard', 'Une aide de l’État pour le loyer des personnes à faible revenu', 'Un supplément à payer au propriétaire'], 1,
    'C’est une allocation logement. Elle dépend de votre revenu et du montant du loyer.'),
  Q('kns016', 'wonen', 'Je buren draaien al weken ’s nachts harde muziek. Wat is de beste eerste stap?', 'Vos voisins mettent de la musique forte la nuit depuis des semaines. Quelle est la meilleure première étape ?',
    ['Meteen de politie bellen', 'Rustig met de buren gaan praten', 'Zelf ook harde muziek draaien'], ['Appeler tout de suite la police', 'Aller parler calmement aux voisins', 'Mettre vous aussi de la musique forte'], 1,
    'Aux Pays-Bas, on parle d’abord directement et calmement avec les voisins. Si cela ne marche pas : bailleur, médiation de voisinage (buurtbemiddeling), puis police.'),
  Q('kns017', 'wonen', 'Na welke tijd moet je ’s avonds meestal rustig zijn voor de buren?', 'À partir de quelle heure faut-il en général être calme le soir pour les voisins ?',
    ['Na 18.00 uur', 'Na 22.00 uur', 'Na 02.00 uur'], ['Après 18 h', 'Après 22 h', 'Après 2 h du matin'], 1,
    'Ce n’est pas une loi nationale, mais c’est l’usage et souvent la règle de l’immeuble ou de la commune : après 22 h, on évite le bruit.'),
  Q('kns018', 'wonen', 'Wie betaalt groot onderhoud aan een huurhuis, zoals een nieuw dak?', 'Qui paie les gros travaux d’un logement loué, comme un nouveau toit ?',
    ['De huurder', 'De verhuurder', 'De gemeente'], ['Le locataire', 'Le propriétaire', 'La commune'], 1,
    'Le gros entretien est à la charge du bailleur. Le locataire s’occupe des petites réparations (ampoules, joints…).'),
  Q('kns019', 'wonen', 'Waarvoor dient een rookmelder in huis?', 'À quoi sert un détecteur de fumée à la maison ?',
    ['Om de temperatuur te meten', 'Om op tijd te waarschuwen bij brand', 'Om inbrekers te melden'], ['À mesurer la température', 'À avertir à temps en cas d’incendie', 'À signaler les cambrioleurs'], 1,
    'Depuis juillet 2022, un détecteur de fumée est obligatoire à chaque étage de tout logement.'),
  Q('kns020', 'wonen', 'Je gaat verhuizen. Wanneer geef je je nieuwe adres door aan de gemeente?', 'Vous déménagez. Quand signalez-vous votre nouvelle adresse à la commune ?',
    ['Vanaf 4 weken vóór tot uiterlijk 5 dagen na de verhuizing', 'Binnen 6 maanden', 'Dat hoeft niet'], ['Entre 4 semaines avant et au plus tard 5 jours après le déménagement', 'Dans les 6 mois', 'Ce n’est pas nécessaire'], 0,
    'On le déclare à la commune du nouveau domicile, en ligne avec DigiD ou au guichet. Les autres organismes reçoivent ensuite l’adresse automatiquement.'),

  Q('kns021', 'werk', 'Wat is een proeftijd bij een nieuw contract?', 'Qu’est-ce que la « proeftijd » dans un nouveau contrat ?',
    ['Een periode waarin je geen salaris krijgt', 'Een periode waarin werkgever en werknemer het contract direct kunnen stoppen', 'Een vakantieperiode'], ['Une période sans salaire', 'Une période où employeur et salarié peuvent arrêter le contrat immédiatement', 'Une période de vacances'], 1,
    'C’est la période d’essai : 1 ou 2 mois au maximum selon la durée du contrat. Vous êtes payé normalement pendant cette période.'),
  Q('kns022', 'werk', 'Je bent ziek en kunt niet werken. Wat moet je doen?', 'Vous êtes malade et ne pouvez pas travailler. Que devez-vous faire ?',
    ['Je stuurt na de werkdag een e-mail', 'Je meldt je ziek bij je werkgever voordat je werk begint', 'Je belt na een week'], ['Vous envoyez un e-mail après la journée', 'Vous vous déclarez malade auprès de l’employeur avant le début du travail', 'Vous appelez après une semaine'], 1,
    'On se déclare malade (ziek melden) le jour même, avant l’heure de début, en suivant la règle de l’entreprise (souvent par téléphone).'),
  Q('kns023', 'werk', 'Wat is zwartwerken?', 'Qu’est-ce que le « zwartwerken » ?',
    ['Werken in de nacht', 'Werken zonder dat je inkomen aan de Belastingdienst wordt gemeld', 'Werken in een fabriek'], ['Travailler la nuit', 'Travailler sans que le revenu soit déclaré aux impôts', 'Travailler en usine'], 1,
    'C’est le travail au noir : illégal et puni. Vous n’avez alors ni assurance ni droits en cas d’accident ou de licenciement.'),
  Q('kns024', 'werk', 'Welke organisatie betaalt een uitkering als je je werk kwijtraakt?', 'Quel organisme verse une allocation si vous perdez votre emploi ?',
    ['Het UWV', 'De Belastingdienst', 'De huisarts'], ['L’UWV', 'Les impôts (Belastingdienst)', 'Le médecin généraliste'], 0,
    'L’UWV gère l’allocation chômage (WW) et aide à retrouver du travail.'),
  Q('kns025', 'werk', 'Wat staat er op een loonstrook?', 'Qu’y a-t-il sur une fiche de paie (loonstrook) ?',
    ['Je gewerkte uren en je bruto- en nettoloon', 'Het contract met je verhuurder', 'Je medische gegevens'], ['Vos heures travaillées et votre salaire brut et net', 'Le contrat avec votre propriétaire', 'Vos données médicales'], 0,
    'Le brut, c’est avant impôts et cotisations ; le net, c’est ce qui arrive sur votre compte.'),
  Q('kns026', 'werk', 'Wat is het minimumloon?', 'Qu’est-ce que le salaire minimum (minimumloon) ?',
    ['Het laagste loon dat een werkgever volgens de wet mag betalen', 'Het hoogste loon dat je mag verdienen', 'Een fooi van klanten'], ['Le salaire le plus bas qu’un employeur peut payer selon la loi', 'Le salaire le plus haut autorisé', 'Un pourboire des clients'], 0,
    'Depuis 2024, le salaire minimum légal est fixé par heure. Il est plus bas pour les jeunes de moins de 21 ans.'),
  Q('kns027', 'werk', 'Heb je met een contract recht op betaalde vakantie?', 'Avec un contrat, avez-vous droit à des congés payés ?',
    ['Nee, vakantie is altijd onbetaald', 'Ja, minimaal vier keer het aantal uren dat je per week werkt', 'Alleen in de zomer'], ['Non, les vacances ne sont jamais payées', 'Oui, au moins quatre fois votre nombre d’heures par semaine', 'Seulement en été'], 1,
    'Soit 4 semaines par an pour un temps plein. Vous recevez aussi en général un pécule de vacances (vakantiegeld) d’environ 8 % du salaire.'),
  Q('kns028', 'werk', 'Wat is een vast contract?', 'Qu’est-ce qu’un « vast contract » ?',
    ['Een contract voor onbepaalde tijd', 'Een contract voor één dag', 'Een contract dat nooit kan eindigen'], ['Un contrat à durée indéterminée (CDI)', 'Un contrat d’un jour', 'Un contrat qui ne peut jamais finir'], 0,
    'C’est un CDI : il n’a pas de date de fin, mais il peut quand même se terminer (démission, licenciement selon les règles).'),
  Q('kns029', 'werk', 'Wat is een arbeidsovereenkomst?', 'Qu’est-ce qu’une « arbeidsovereenkomst » ?',
    ['Een huurcontract', 'Een afspraak tussen werkgever en werknemer over het werk', 'Een verzekeringspolis'], ['Un bail de location', 'Un accord entre employeur et salarié sur le travail', 'Une police d’assurance'], 1,
    'C’est le contrat de travail : salaire, horaires, congés, durée. Lisez-le bien avant de signer.'),
  Q('kns030', 'werk', 'Je neemt zelf ontslag. Krijg je dan een WW-uitkering?', 'Vous démissionnez vous-même. Recevez-vous une allocation chômage (WW) ?',
    ['Ja, altijd direct', 'Meestal niet', 'Ja, maar je moet je salaris terugbetalen'], ['Oui, toujours immédiatement', 'En général non', 'Oui, mais vous remboursez votre salaire'], 1,
    'Celui qui démissionne volontairement n’a en principe pas droit à la WW.'),

  Q('kns031', 'onderwijs', 'Vanaf welke leeftijd moet een kind naar school?', 'À partir de quel âge un enfant doit-il aller à l’école ?',
    ['Vanaf 4 jaar', 'Vanaf 5 jaar', 'Vanaf 7 jaar'], ['À partir de 4 ans', 'À partir de 5 ans', 'À partir de 7 ans'], 1,
    'L’obligation scolaire (leerplicht) commence le 1er jour du mois qui suit les 5 ans. La plupart des enfants vont déjà à l’école à 4 ans.'),
  Q('kns032', 'onderwijs', 'Tot welke leeftijd moeten jongeren naar school?', 'Jusqu’à quel âge les jeunes doivent-ils aller à l’école ?',
    ['Tot 16 jaar', 'Tot 18 jaar, of tot ze een diploma hebben (startkwalificatie)', 'Tot 21 jaar'], ['Jusqu’à 16 ans', 'Jusqu’à 18 ans, ou jusqu’à l’obtention d’un diplôme de base', 'Jusqu’à 21 ans'], 1,
    'Après 16 ans, les jeunes sans diplôme de base (havo, vwo ou mbo niveau 2) doivent continuer jusqu’à 18 ans.'),
  Q('kns033', 'onderwijs', 'Wat is een tienminutengesprek op school?', 'Qu’est-ce qu’un « tienminutengesprek » à l’école ?',
    ['Een straf voor een leerling', 'Een kort gesprek tussen ouders en leerkracht over het kind', 'Een gymles'], ['Une punition pour un élève', 'Un court entretien entre parents et enseignant sur l’enfant', 'Un cours de sport'], 1,
    'Ces rendez-vous reviennent plusieurs fois par an. Les parents sont censés y aller : l’école attend leur participation.'),
  Q('kns034', 'onderwijs', 'Wat is de ouderbijdrage op een basisschool?', 'Qu’est-ce que la « ouderbijdrage » à l’école primaire ?',
    ['Een verplichte belasting', 'Een vrijwillige bijdrage voor extra activiteiten', 'Het salaris van de leraar'], ['Un impôt obligatoire', 'Une contribution volontaire pour des activités en plus', 'Le salaire de l’enseignant'], 1,
    'Elle est facultative. Un enfant ne peut pas être exclu d’une activité parce que ses parents n’ont pas payé.'),
  Q('kns035', 'onderwijs', 'Welke organisatie regelt de inburgeringsexamens?', 'Quel organisme organise les examens d’intégration ?',
    ['DUO', 'De gemeente', 'De Belastingdienst'], ['DUO', 'La commune', 'Les impôts'], 0,
    'DUO (Dienst Uitvoering Onderwijs) gère les examens d’intégration, y compris l’examen de base à l’étranger, ainsi que les bourses d’études.'),
  Q('kns036', 'onderwijs', 'Wat is het vmbo?', 'Qu’est-ce que le « vmbo » ?',
    ['Middelbare school die voorbereidt op een beroepsopleiding (mbo)', 'De universiteit', 'Een school voor kinderen van 4 tot 12 jaar'], ['Un collège qui prépare à une formation professionnelle (mbo)', 'L’université', 'Une école pour les enfants de 4 à 12 ans'], 0,
    'Après l’école primaire, il y a trois filières : vmbo (4 ans, professionnel), havo (5 ans) et vwo (6 ans, prépare à l’université).'),
  Q('kns037', 'onderwijs', 'Mag je met je schoolgaande kind op vakantie buiten de schoolvakanties?', 'Pouvez-vous partir en vacances avec votre enfant en dehors des vacances scolaires ?',
    ['Ja, dat mag altijd', 'Alleen in bijzondere gevallen, met toestemming van de directeur', 'Ja, als je de school een week van tevoren informeert'], ['Oui, toujours', 'Seulement dans des cas particuliers, avec l’accord du directeur', 'Oui, si vous prévenez l’école une semaine avant'], 1,
    'Sans accord du directeur, c’est une absence illégale : l’école la signale et les parents peuvent recevoir une amende.'),
  Q('kns038', 'onderwijs', 'Wat is kinderopvangtoeslag?', 'Qu’est-ce que la « kinderopvangtoeslag » ?',
    ['Geld van de school voor schoolboeken', 'Een bijdrage in de kosten van de kinderopvang voor werkende ouders', 'Een boete voor ouders'], ['De l’argent de l’école pour les livres', 'Une aide aux frais de garde d’enfants pour les parents qui travaillent', 'Une amende pour les parents'], 1,
    'C’est une aide aux frais de crèche ou de garde, pour les parents qui travaillent ou étudient.'),
  Q('kns039', 'onderwijs', 'Hoe heet de toets in groep 8 van de basisschool?', 'Comment s’appelle le test de la dernière année de l’école primaire (groep 8) ?',
    ['De doorstroomtoets', 'Het rijexamen', 'Het inburgeringsexamen'], ['Le test d’orientation (doorstroomtoets)', 'L’examen du permis', 'L’examen d’intégration'], 0,
    'Ce test aide à choisir le niveau d’école secondaire, avec l’avis de l’enseignant.'),
  Q('kns040', 'onderwijs', 'Wat is het mbo?', 'Qu’est-ce que le « mbo » ?',
    ['Middelbaar beroepsonderwijs', 'Een basisschool', 'Een universiteit'], ['L’enseignement professionnel secondaire', 'Une école primaire', 'Une université'], 0,
    'Le mbo forme à des métiers concrets : aide-soignant, mécanicien, coiffeur, cuisinier…'),

  Q('kns041', 'staat', 'Wie is het staatshoofd van Nederland?', 'Qui est le chef de l’État des Pays-Bas ?',
    ['De minister-president', 'Koning Willem-Alexander', 'De burgemeester van Amsterdam'], ['Le Premier ministre', 'Le roi Willem-Alexander', 'Le maire d’Amsterdam'], 1,
    'Les Pays-Bas sont une monarchie constitutionnelle : le roi est chef de l’État, mais ce sont les ministres qui gouvernent.'),
  Q('kns042', 'staat', 'Hoeveel leden heeft de Tweede Kamer?', 'Combien de membres compte la Tweede Kamer ?',
    ['75', '150', '250'], ['75', '150', '250'], 1,
    'La Tweede Kamer (Chambre des représentants) compte 150 députés élus pour 4 ans.'),
  Q('kns043', 'staat', 'In welke stad zitten de regering en het parlement?', 'Dans quelle ville siègent le gouvernement et le parlement ?',
    ['Amsterdam', 'Den Haag', 'Rotterdam'], ['Amsterdam', 'La Haye', 'Rotterdam'], 1,
    'Amsterdam est la capitale, mais le gouvernement et le parlement sont à La Haye (Den Haag).'),
  Q('kns044', 'staat', 'Wat staat er in artikel 1 van de Grondwet?', 'Que dit l’article 1 de la Constitution ?',
    ['Iedereen moet stemmen', 'Iedereen wordt gelijk behandeld; discriminatie is verboden', 'Nederland heeft een koning'], ['Tout le monde doit voter', 'Tout le monde est traité de la même façon ; la discrimination est interdite', 'Les Pays-Bas ont un roi'], 1,
    'L’article 1 interdit la discrimination selon la religion, les convictions, l’origine, le sexe, l’orientation sexuelle, le handicap…'),
  Q('kns045', 'staat', 'Vanaf welke leeftijd mag je stemmen voor de Tweede Kamer?', 'À partir de quel âge peut-on voter pour la Tweede Kamer ?',
    ['16 jaar', '18 jaar', '21 jaar'], ['16 ans', '18 ans', '21 ans'], 1,
    'Il faut avoir 18 ans et la nationalité néerlandaise. Aux élections communales, les citoyens de l’UE et les autres étrangers en séjour légal depuis 5 ans peuvent aussi voter.'),
  Q('kns046', 'staat', 'Wie is de leider van de regering?', 'Qui dirige le gouvernement ?',
    ['De koning', 'De minister-president', 'De burgemeester'], ['Le roi', 'Le Premier ministre', 'Le maire'], 1,
    'Le minister-president préside le conseil des ministres.'),
  Q('kns047', 'staat', 'Wat doet de Eerste Kamer?', 'Que fait la Eerste Kamer ?',
    ['Zij controleert wetten en stemt voor of tegen', 'Zij kiest de koning', 'Zij schrijft alle nieuwe wetten'], ['Elle contrôle les lois et vote pour ou contre', 'Elle choisit le roi', 'Elle écrit toutes les nouvelles lois'], 0,
    'La Eerste Kamer (Sénat) vote sur les lois déjà adoptées par la Tweede Kamer, sans pouvoir les modifier.'),
  Q('kns048', 'staat', 'Wie besturen een gemeente?', 'Qui dirige une commune ?',
    ['Het parlement', 'De burgemeester, de wethouders en de gemeenteraad', 'De ministers'], ['Le parlement', 'Le maire, les échevins et le conseil municipal', 'Les ministres'], 1,
    'Le conseil municipal (gemeenteraad) est élu par les habitants ; le maire et les échevins (wethouders) forment le collège B&W.'),
  Q('kns049', 'staat', 'Wat is een politieke partij?', 'Qu’est-ce qu’un parti politique ?',
    ['Een groep ambtenaren van de gemeente', 'Een groep mensen met dezelfde ideeën over hoe het land bestuurd moet worden', 'Een vakbond'], ['Un groupe de fonctionnaires de la commune', 'Un groupe de personnes qui partagent des idées sur la façon de gouverner le pays', 'Un syndicat'], 1,
    'Il y a beaucoup de partis aux Pays-Bas. Aucun n’a la majorité seul : le gouvernement est toujours une coalition.'),
  Q('kns050', 'staat', 'Wat mag de Tweede Kamer wel en de Eerste Kamer niet?', 'Que peut faire la Tweede Kamer, mais pas la Eerste Kamer ?',
    ['Wetsvoorstellen veranderen (amenderen)', 'Stemmen over wetten', 'Vergaderen in Den Haag'], ['Modifier les projets de loi (amender)', 'Voter les lois', 'Se réunir à La Haye'], 0,
    'Seule la Tweede Kamer a le droit d’amendement. La Eerste Kamer peut seulement accepter ou rejeter une loi.'),

  Q('kns051', 'geschiedenis', 'Wanneer was Nederland bezet door Duitsland?', 'Quand les Pays-Bas étaient-ils occupés par l’Allemagne ?',
    ['1914 – 1918', '1940 – 1945', '1950 – 1955'], ['1914 – 1918', '1940 – 1945', '1950 – 1955'], 1,
    'Pendant la Seconde Guerre mondiale, de mai 1940 à mai 1945.'),
  Q('kns052', 'geschiedenis', 'Wie was Anne Frank?', 'Qui était Anne Frank ?',
    ['Een koningin', 'Een Joods meisje dat bekend werd door haar dagboek', 'Een verzetsstrijder die de oorlog overleefde'], ['Une reine', 'Une jeune fille juive célèbre pour son journal', 'Une résistante qui a survécu à la guerre'], 1,
    'Cachée à Amsterdam, elle a écrit son journal. Elle a été déportée et est morte en 1945 au camp de Bergen-Belsen.'),
  Q('kns053', 'geschiedenis', 'Wat vieren we op 5 mei?', 'Que fête-t-on le 5 mai ?',
    ['Koningsdag', 'Bevrijdingsdag', 'Sinterklaas'], ['La fête du Roi', 'La fête de la Libération', 'La Saint-Nicolas'], 1,
    'Le 5 mai, on fête la fin de l’occupation allemande en 1945.'),
  Q('kns054', 'geschiedenis', 'Wat zijn de Deltawerken?', 'Que sont les « Deltawerken » ?',
    ['Dammen en stormvloedkeringen tegen overstromingen', 'Snelwegen over het water', 'Bruggen in Amsterdam'], ['Des barrages et digues anti-tempête contre les inondations', 'Des autoroutes sur l’eau', 'Des ponts à Amsterdam'], 0,
    'Construits après l’inondation catastrophique de 1953, ils protègent le sud-ouest du pays contre la mer.'),
  Q('kns055', 'geschiedenis', 'Wanneer is Koningsdag?', 'Quand a lieu la fête du Roi ?',
    ['30 april', '27 april', '5 mei'], ['30 avril', '27 avril', '5 mai'], 1,
    'C’est l’anniversaire du roi Willem-Alexander. Si le 27 avril tombe un dimanche, on la fête le 26.'),
  Q('kns056', 'wonen', 'Wat is de Randstad?', 'Qu’est-ce que la Randstad ?',
    ['Een groot bos in het oosten', 'Het gebied met Amsterdam, Rotterdam, Den Haag en Utrecht', 'Een rivier in Friesland'], ['Une grande forêt à l’est', 'La région d’Amsterdam, Rotterdam, La Haye et Utrecht', 'Une rivière en Frise'], 1,
    'C’est la région la plus peuplée et la plus active économiquement, dans l’ouest du pays.'),
  Q('kns057', 'geschiedenis', 'Waarom had Nederland vroeger veel molens?', 'Pourquoi les Pays-Bas avaient-ils autrefois beaucoup de moulins ?',
    ['Om stroom te maken', 'Om water uit de polders te pompen en graan te malen', 'Alleen als versiering'], ['Pour produire de l’électricité', 'Pour pomper l’eau des polders et moudre le grain', 'Seulement pour décorer'], 1,
    'Beaucoup de terres sont sous le niveau de la mer : les moulins pompaient l’eau pour garder les polders au sec.'),
  Q('kns058', 'wonen', 'Wat doet een waterschap?', 'Que fait un « waterschap » ?',
    ['Het verkoopt drinkwater', 'Het zorgt voor de dijken en de hoogte van het water', 'Het is een zwembad'], ['Il vend l’eau potable', 'Il entretient les digues et gère le niveau de l’eau', 'C’est une piscine'], 1,
    'Les waterschappen sont des autorités régionales élues. L’eau du robinet, elle, vient d’une compagnie des eaux.'),
  Q('kns059', 'geschiedenis', 'Wat gebeurt er op 4 mei om 20.00 uur?', 'Que se passe-t-il le 4 mai à 20 h ?',
    ['Een vuurwerkshow', 'Twee minuten stilte voor de slachtoffers van oorlogen', 'Het begin van Koningsdag'], ['Un feu d’artifice', 'Deux minutes de silence pour les victimes des guerres', 'Le début de la fête du Roi'], 1,
    'C’est la Dodenherdenking : on se souvient des victimes néerlandaises de la Seconde Guerre mondiale et des conflits ultérieurs.'),
  Q('kns060', 'wonen', 'Aan welke zee ligt Nederland?', 'Au bord de quelle mer se trouvent les Pays-Bas ?',
    ['De Middellandse Zee', 'De Noordzee', 'De Zwarte Zee'], ['La Méditerranée', 'La mer du Nord', 'La mer Noire'], 1,
    'La côte ouest et nord donne sur la mer du Nord.'),

  Q('kns061', 'staat', 'Wat is een BSN?', 'Qu’est-ce qu’un BSN ?',
    ['Een bankpas', 'Je persoonlijke nummer voor contact met de overheid, werk en zorg', 'Je huisnummer'], ['Une carte bancaire', 'Votre numéro personnel pour l’État, le travail et les soins', 'Votre numéro de maison'], 1,
    'Le burgerservicenummer est attribué à l’inscription à la commune. Donnez-le seulement aux organismes qui en ont besoin.'),
  Q('kns062', 'staat', 'Waar vraag je een Nederlands paspoort of identiteitskaart aan?', 'Où demandez-vous un passeport ou une carte d’identité néerlandaise ?',
    ['Bij de supermarkt', 'Bij de gemeente', 'Bij de politie'], ['Au supermarché', 'À la commune', 'À la police'], 1,
    'Les documents de voyage sont délivrés au guichet de la commune (Burgerzaken).'),
  Q('kns063', 'werk', 'Wat doet de Belastingdienst?', 'Que fait la Belastingdienst ?',
    ['Belasting innen en toeslagen betalen', 'Paspoorten maken', 'Een uitkering betalen als je werkloos bent'], ['Percevoir les impôts et verser les allocations', 'Faire les passeports', 'Verser l’allocation chômage'], 0,
    'Elle perçoit les impôts et, via son service Toeslagen, verse les aides comme la huurtoeslag ou la zorgtoeslag.'),
  Q('kns064', 'werk', 'Je bent je portemonnee met je bankpas kwijt. Wat doe je eerst?', 'Vous avez perdu votre portefeuille avec votre carte bancaire. Que faites-vous d’abord ?',
    ['Wachten tot iemand hem terugbrengt', 'Je bankpas direct laten blokkeren', 'Een nieuwe portemonnee kopen'], ['Attendre que quelqu’un le rapporte', 'Faire bloquer immédiatement votre carte bancaire', 'Acheter un nouveau portefeuille'], 1,
    'On bloque la carte tout de suite pour éviter les abus, puis on signale la perte (gemeente pour une pièce d’identité, police en cas de vol).'),
  Q('kns065', 'staat', 'Wat is DigiD?', 'Qu’est-ce que DigiD ?',
    ['Een digitale camera', 'Je persoonlijke inlogcode voor websites van de overheid', 'Een webwinkel'], ['Un appareil photo numérique', 'Votre identifiant personnel pour les sites de l’État', 'Une boutique en ligne'], 1,
    'Avec DigiD, on se connecte à la commune, aux impôts, à DUO, à l’assurance maladie… Ne le donnez jamais à personne.'),
  Q('kns066', 'staat', 'Je fiets is gisteren gestolen. Welk nummer bel je?', 'Votre vélo a été volé hier. Quel numéro appelez-vous ?',
    ['0900-8844', '112', 'Je belt niemand'], ['0900-8844', '112', 'Vous n’appelez personne'], 0,
    '0900-8844 est le numéro de la police pour les situations non urgentes. On peut aussi déclarer certains vols en ligne.'),
  Q('kns067', 'staat', 'Wat is een uittreksel uit de BRP?', 'Qu’est-ce qu’un « uittreksel uit de BRP » ?',
    ['Een recept van de arts', 'Een officieel document van de gemeente met je gegevens, zoals je adres', 'Een belastingaanslag'], ['Une ordonnance médicale', 'Un document officiel de la commune avec vos données, comme votre adresse', 'Un avis d’imposition'], 1,
    'La BRP est le registre de la population de la commune. Cet extrait sert de preuve d’adresse ou d’état civil.'),
  Q('kns068', 'usages', 'Mag je op straat plassen?', 'Peut-on uriner dans la rue ?',
    ['Ja, als niemand kijkt', 'Nee, dat is verboden; je kunt een boete krijgen', 'Alleen ’s nachts'], ['Oui, si personne ne regarde', 'Non, c’est interdit ; vous pouvez recevoir une amende', 'Seulement la nuit'], 1,
    'Le « wildplassen » est puni d’une amende.'),
  Q('kns069', 'staat', 'Wie mogen in Nederland met elkaar trouwen?', 'Qui peut se marier aux Pays-Bas ?',
    ['Alleen een man en een vrouw', 'Twee volwassenen, ook van hetzelfde geslacht', 'Alleen mensen met de Nederlandse nationaliteit'], ['Seulement un homme et une femme', 'Deux adultes, y compris du même sexe', 'Seulement les Néerlandais'], 1,
    'Depuis 2001, le mariage est ouvert aux couples de même sexe. Le mariage civil à la commune est le seul valable légalement ; un mariage religieux ne peut avoir lieu qu’après.'),
  Q('kns070', 'wonen', 'Er is brand in je huis. Welk nummer bel je?', 'Il y a le feu chez vous. Quel numéro appelez-vous ?',
    ['112', '0900-8844', 'Het nummer van de gemeente'], ['112', '0900-8844', 'Le numéro de la commune'], 0,
    'Pompiers, ambulance et police urgente : toujours le 112.'),

  Q('kns071', 'staat', 'Hoe denken de meeste Nederlanders over mannen en vrouwen?', 'Que pensent la plupart des Néerlandais des hommes et des femmes ?',
    ['Mannen en vrouwen hebben dezelfde rechten en plichten', 'Mannen beslissen in het gezin', 'Vrouwen werken niet buitenshuis'], ['Hommes et femmes ont les mêmes droits et devoirs', 'Les hommes décident dans la famille', 'Les femmes ne travaillent pas à l’extérieur'], 0,
    'L’égalité hommes-femmes est une valeur de base, aussi à la maison : les tâches et les décisions se partagent.'),
  Q('kns072', 'staat', 'Wat betekent vrijheid van meningsuiting?', 'Que signifie la liberté d’expression ?',
    ['Je mag geen kritiek geven op de regering', 'Je mag je mening zeggen, maar niet discrimineren of oproepen tot geweld', 'Je mag alles zeggen, ook als het discriminerend is'], ['Vous ne pouvez pas critiquer le gouvernement', 'Vous pouvez dire votre opinion, mais sans discriminer ni appeler à la violence', 'Vous pouvez tout dire, même des propos discriminatoires'], 1,
    'C’est un droit fondamental, avec des limites fixées par la loi.'),
  Q('kns073', 'usages', 'Waarom komen Nederlanders op tijd voor een afspraak?', 'Pourquoi les Néerlandais arrivent-ils à l’heure à un rendez-vous ?',
    ['Het is niet belangrijk', 'Het is een teken van respect en betrouwbaarheid', 'Het is alleen belangrijk op het werk'], ['Ce n’est pas important', 'C’est une marque de respect et de fiabilité', 'C’est important seulement au travail'], 1,
    'Si vous êtes en retard, prévenez avant. On prend aussi souvent rendez-vous pour une simple visite chez des amis.'),
  Q('kns074', 'usages', 'Je bent op een verjaardag. Wie feliciteer je?', 'Vous êtes à un anniversaire. Qui félicitez-vous ?',
    ['Alleen de jarige', 'De jarige en ook de familie en vrienden van de jarige', 'Niemand'], ['Seulement la personne qui fête son anniversaire', 'La personne fêtée, mais aussi sa famille et ses amis', 'Personne'], 1,
    'On dit par exemple : « Gefeliciteerd met je man ! » Les invités sont souvent assis en cercle (kringverjaardag).'),
  Q('kns075', 'usages', 'Je ontmoet iemand voor het eerst, bijvoorbeeld op je werk. Hoe begroet je hem of haar?', 'Vous rencontrez quelqu’un pour la première fois, par exemple au travail. Comment le saluez-vous ?',
    ['Je geeft een hand en zegt je naam', 'Je geeft drie zoenen', 'Je zegt niets'], ['Vous serrez la main et dites votre nom', 'Vous faites trois bises', 'Vous ne dites rien'], 0,
    'La poignée de main est la norme. Les trois bises, c’est entre proches (famille, amis), par exemple pour un anniversaire.'),
  Q('kns076', 'staat', 'Hoe is homoseksualiteit geregeld in Nederland?', 'Quelle est la situation de l’homosexualité aux Pays-Bas ?',
    ['Het is verboden', 'Homo’s en lesbiennes hebben dezelfde rechten als iedereen', 'Het mag alleen thuis'], ['C’est interdit', 'Les homosexuels ont les mêmes droits que tout le monde', 'C’est permis seulement à la maison'], 1,
    'En 2001, les Pays-Bas ont été le premier pays au monde à ouvrir le mariage aux couples de même sexe.'),
  Q('kns077', 'staat', 'Iemand is het niet met je eens. Mag je hem slaan?', 'Quelqu’un n’est pas d’accord avec vous. Pouvez-vous le frapper ?',
    ['Ja, als je gelijk hebt', 'Nee, geweld is verboden; bij een conflict kun je naar de rechter', 'Alleen binnen het gezin'], ['Oui, si vous avez raison', 'Non, la violence est interdite ; en cas de conflit, on peut aller en justice', 'Seulement au sein de la famille'], 1,
    'La violence est toujours interdite, y compris à la maison (violence domestique : appelez Veilig Thuis au 0800-2000).'),
  Q('kns078', 'staat', 'Een ambtenaar vraagt geld om je aanvraag sneller te behandelen. Wat is dat?', 'Un fonctionnaire demande de l’argent pour traiter votre demande plus vite. Qu’est-ce que c’est ?',
    ['Normaal, dat doet iedereen', 'Omkoping; dat is strafbaar', 'Een officiële betaling'], ['Normal, tout le monde le fait', 'De la corruption ; c’est puni par la loi', 'Un paiement officiel'], 1,
    'La corruption est punie, pour celui qui demande comme pour celui qui paie. Les frais officiels ont toujours un tarif public.'),
  Q('kns079', 'staat', 'Wat is de rol van religie in de Nederlandse wet?', 'Quel est le rôle de la religion dans la loi néerlandaise ?',
    ['De wet is gebaseerd op één godsdienst', 'Kerk en staat zijn gescheiden; iedereen mag zijn eigen geloof hebben', 'Religie is verboden'], ['La loi repose sur une seule religion', 'Églises et État sont séparés ; chacun est libre de sa religion', 'La religion est interdite'], 1,
    'Chacun peut croire ce qu’il veut, ou ne pas croire. Les règles religieuses ne passent jamais avant la loi.'),
  Q('kns080', 'taal', 'Wanneer gebruik je ‘u’ in plaats van ‘je’?', 'Quand utilisez-vous « u » plutôt que « je » ?',
    ['Nooit', 'Bij mensen die je niet kent, oudere mensen en bij instanties', 'Alleen bij kinderen'], ['Jamais', 'Avec des inconnus, des personnes âgées et dans les administrations', 'Seulement avec les enfants'], 1,
    '« U » correspond au vouvoiement. Les Néerlandais passent vite au « je », mais attendez qu’on vous le propose.'),

  Q('kns081', 'usages', 'Wie heeft voorrang op een kruispunt zonder borden?', 'Qui a la priorité à un carrefour sans panneaux ?',
    ['Verkeer van rechts', 'Verkeer van links', 'Wie het hardst rijdt'], ['Les véhicules venant de droite', 'Les véhicules venant de gauche', 'Celui qui roule le plus vite'], 0,
    'La règle de base : priorité à droite, aussi pour les vélos.'),
  Q('kns082', 'usages', 'Hoe betaal je in de trein, bus en tram?', 'Comment payez-vous dans le train, le bus et le tram ?',
    ['Je checkt in en uit met een OV-chipkaart of bankpas', 'Je betaalt contant aan de chauffeur', 'Je hoeft niet te betalen'], ['Vous validez à l’entrée et à la sortie avec une carte OV-chipkaart ou bancaire', 'Vous payez en espèces au chauffeur', 'C’est gratuit'], 0,
    'On « check in » en montant et « check uit » en descendant. Oublier de check uit coûte cher.'),
  Q('kns083', 'usages', 'Moet je fiets verlichting hebben als het donker is?', 'Votre vélo doit-il être éclairé quand il fait nuit ?',
    ['Nee, dat hoeft niet', 'Ja, een wit licht voor en een rood licht achter', 'Alleen in de winter'], ['Non, ce n’est pas nécessaire', 'Oui, une lumière blanche devant et rouge derrière', 'Seulement en hiver'], 1,
    'Sans éclairage la nuit, vous pouvez recevoir une amende.'),
  Q('kns084', 'usages', 'Hoe hard mag je meestal rijden in de bebouwde kom?', 'À quelle vitesse peut-on en général rouler en agglomération ?',
    ['30 of 50 km per uur', '80 km per uur', '120 km per uur'], ['30 ou 50 km/h', '80 km/h', '120 km/h'], 0,
    'En ville, c’est 50 km/h, et de plus en plus souvent 30 km/h. Regardez toujours les panneaux.'),
  Q('kns085', 'usages', 'Mag je alcohol drinken en daarna autorijden?', 'Peut-on boire de l’alcool puis conduire ?',
    ['Ja, zoveel je wilt', 'Er is een strenge grens; voor beginnende bestuurders is die nog lager', 'Alleen bier mag'], ['Oui, autant qu’on veut', 'Il y a une limite stricte ; encore plus basse pour les jeunes conducteurs', 'Seulement de la bière'], 1,
    'La limite est de 0,5 ‰ (0,2 ‰ pour les conducteurs novices). Le plus sûr : ne pas boire du tout avant de conduire.'),
  Q('kns086', 'usages', 'Iemand wil oversteken bij een zebrapad. Wie heeft voorrang?', 'Quelqu’un veut traverser à un passage piéton. Qui a la priorité ?',
    ['De auto', 'De voetganger', 'Wie het eerst komt'], ['La voiture', 'Le piéton', 'Le premier arrivé'], 1,
    'Au passage piéton (zebrapad), les voitures et les vélos doivent laisser passer les piétons.'),
  Q('kns087', 'usages', 'Moet je in de auto een gordel dragen?', 'Faut-il porter une ceinture de sécurité en voiture ?',
    ['Alleen voorin', 'Ja, iedereen in de auto', 'Alleen op de snelweg'], ['Seulement à l’avant', 'Oui, tous les passagers', 'Seulement sur l’autoroute'], 1,
    'La ceinture est obligatoire pour tous, devant et derrière. Les jeunes enfants ont besoin d’un siège auto adapté.'),
  Q('kns088', 'usages', 'Wat betekent een rood verkeerslicht?', 'Que signifie un feu rouge ?',
    ['Doorrijden', 'Stoppen', 'Langzaam doorrijden'], ['Continuer', 'S’arrêter', 'Continuer lentement'], 1,
    'Rouge = stop, aussi pour les cyclistes.'),
  Q('kns089', 'usages', 'Waar mag je je fiets niet neerzetten?', 'Où ne pouvez-vous pas garer votre vélo ?',
    ['In een fietsenrek', 'Waar een bord zegt dat het verboden is, of waar hij in de weg staat', 'In een fietsenstalling'], ['Dans un range-vélos', 'Là où un panneau l’interdit, ou là où il gêne le passage', 'Dans un parking à vélos'], 1,
    'Un vélo mal garé peut être enlevé par la commune ; il faut payer pour le récupérer.'),
  Q('kns090', 'usages', 'Wat is een rotonde?', 'Qu’est-ce qu’une « rotonde » ?',
    ['Een rond kruispunt waar het verkeer in één richting rijdt', 'Een doodlopende straat', 'Een snelweg'], ['Un carrefour rond où l’on roule dans un seul sens', 'Une impasse', 'Une autoroute'], 0,
    'C’est un rond-point. Les panneaux indiquent qui a la priorité ; souvent, c’est le trafic déjà sur le rond-point.'),

  Q('kns091', 'werk', 'Je krijgt een brief van de Belastingdienst die je niet begrijpt. Wat doe je?', 'Vous recevez une lettre des impôts que vous ne comprenez pas. Que faites-vous ?',
    ['Je gooit de brief weg', 'Je vraagt hulp, bijvoorbeeld bij het Informatiepunt Digitale Overheid in de bibliotheek', 'Je wacht tot er een tweede brief komt'], ['Vous jetez la lettre', 'Vous demandez de l’aide, par exemple au point d’information de la bibliothèque', 'Vous attendez une deuxième lettre'], 1,
    'Ne laissez jamais une lettre officielle sans réponse : il y a souvent un délai. Les bibliothèques aident gratuitement.'),
  Q('kns092', 'usages', 'Wat is een vrijwilliger?', 'Qu’est-ce qu’un « vrijwilliger » ?',
    ['Iemand die een straf uitvoert', 'Iemand die zonder loon helpt, bijvoorbeeld bij een sportclub', 'Een manager'], ['Quelqu’un qui exécute une peine', 'Quelqu’un qui aide sans salaire, par exemple dans un club de sport', 'Un manager'], 1,
    'Le bénévolat est très répandu aux Pays-Bas et c’est un bon moyen de pratiquer le néerlandais.'),
  Q('kns093', 'usages', 'Je fietst en wilt linksaf. Wat doe je?', 'Vous êtes à vélo et voulez tourner à gauche. Que faites-vous ?',
    ['Je steekt op tijd je linkerhand uit en let op het verkeer', 'Je belt met je bel en slaat meteen af', 'Je stapt af en loopt over de stoep'], ['Vous tendez le bras gauche à temps et faites attention au trafic', 'Vous sonnez et tournez tout de suite', 'Vous descendez et marchez sur le trottoir'], 0,
    'Tendre le bras indique votre direction aux autres usagers.'),
  Q('kns094', 'onderwijs', 'Voor welke kinderen is de basisschool?', 'Pour quels enfants est l’école primaire (basisschool) ?',
    ['Kinderen van ongeveer 4 tot 12 jaar', 'Kinderen van 12 tot 16 jaar', 'Kinderen van 0 tot 4 jaar'], ['Les enfants d’environ 4 à 12 ans', 'Les enfants de 12 à 16 ans', 'Les enfants de 0 à 4 ans'], 0,
    'L’école primaire compte 8 années, de groep 1 à groep 8.'),
  Q('kns095', 'werk', 'Je koopt iets in een webwinkel. Mag je het terugsturen?', 'Vous achetez quelque chose en ligne. Pouvez-vous le renvoyer ?',
    ['Ja, meestal binnen 14 dagen na ontvangst', 'Nee, nooit', 'Alleen als het kapot is'], ['Oui, en général dans les 14 jours après réception', 'Non, jamais', 'Seulement s’il est cassé'], 0,
    'C’est le délai de rétractation (bedenktijd) pour les achats en ligne. Il existe quelques exceptions, comme les produits sur mesure.'),
  Q('kns096', 'werk', 'Wat is de Kamer van Koophandel (KvK)?', 'Qu’est-ce que la « Kamer van Koophandel » (KvK) ?',
    ['Een kantoor van de Belastingdienst', 'Het register waar ieder bedrijf ingeschreven moet staan', 'Een bank voor bedrijven'], ['Un bureau des impôts', 'Le registre où toute entreprise doit être inscrite', 'Une banque pour les entreprises'], 1,
    'Si vous créez votre entreprise, vous devez vous inscrire à la KvK (Chambre de commerce).'),
  Q('kns097', 'usages', 'Wat is Sinterklaas?', 'Qu’est-ce que Sinterklaas ?',
    ['Een kinderfeest op 5 december met cadeautjes', 'De verjaardag van de koning', 'Een herdenking van de oorlog'], ['Une fête pour les enfants le 5 décembre, avec des cadeaux', 'L’anniversaire du roi', 'Une commémoration de la guerre'], 0,
    'Le soir du 5 décembre (pakjesavond), les enfants reçoivent des cadeaux. C’est une tradition culturelle, fêtée par des familles de toutes origines.'),
  Q('kns098', 'wonen', 'Wat is waar over een brandblusser in huis?', 'Qu’est-ce qui est vrai à propos d’un extincteur à la maison ?',
    ['Het is verplicht in elke woning', 'Hij helpt om een kleine, beginnende brand te blussen', 'De gemeente controleert hem elk jaar'], ['Il est obligatoire dans chaque logement', 'Il aide à éteindre un petit feu qui commence', 'La commune le contrôle chaque année'], 1,
    'L’extincteur n’est pas obligatoire dans un logement ; le détecteur de fumée, lui, l’est.'),
  Q('kns099', 'staat', 'Wat doet de burgemeester?', 'Que fait le maire (burgemeester) ?',
    ['Hij maakt de wetten van het land', 'Hij leidt het gemeentebestuur en zorgt voor de openbare orde', 'Hij is de baas van de politie in heel Nederland'], ['Il fait les lois du pays', 'Il dirige la commune et veille à l’ordre public', 'Il dirige la police dans tout le pays'], 1,
    'Aux Pays-Bas, le maire n’est pas élu : il est nommé par le gouvernement (la Couronne).'),
  Q('kns100', 'taal', 'Wat is de officiële taal van Nederland?', 'Quelle est la langue officielle des Pays-Bas ?',
    ['Engels', 'Nederlands (en in Friesland ook Fries)', 'Duits'], ['L’anglais', 'Le néerlandais (et aussi le frison en Frise)', 'L’allemand'], 1,
    'Le néerlandais est la langue officielle. En Frise, le frison est aussi une langue officielle.'),
];

export const KNS_QUESTIONS = [...KNS_BASE, ...KNS_PLUS];
