// Questions supplémentaires (KNS), rédigées d’après des sources publiques :
// Rijksoverheid.nl, Government.nl, IND, DUO, SVB, Belastingdienst, Juridisch Loket, Canon van Nederland.
// L’ordre des réponses est mélangé à l’affichage. Dernière vérification : septembre 2026.

const Q = (id, cat, q, qFr, opts, optsFr, expl, corr = 0) => ({ id, cat, q, qFr, opts, optsFr, corr, expl });

export const KNS_PLUS = [
  // ── La langue néerlandaise ──
  Q('kns101', 'taal', 'Waarom is het belangrijk om Nederlands te leren?', 'Pourquoi est-il important d’apprendre le néerlandais ?',
    ['Om werk te vinden en contact te hebben met buren, school en dokter', 'Het is niet belangrijk; iedereen spreekt Engels', 'Alleen voor mensen die gaan studeren'],
    ['Pour trouver du travail et communiquer avec voisins, école et médecin', 'Ce n’est pas important ; tout le monde parle anglais', 'Seulement pour ceux qui vont étudier'],
    'Beaucoup de Néerlandais parlent anglais, mais le travail, l’école des enfants, les lettres officielles et les soins se font en néerlandais. La loi demande aussi de continuer l’intégration après l’arrivée.'),
  Q('kns102', 'taal', 'Waar spreken ze ook Nederlands?', 'Où parle-t-on aussi néerlandais ?',
    ['In Vlaanderen, in België', 'In Frankrijk', 'In Duitsland'], ['En Flandre, en Belgique', 'En France', 'En Allemagne'],
    'On parle néerlandais aux Pays-Bas, en Flandre (nord de la Belgique), au Suriname et dans les îles néerlandaises des Caraïbes.'),
  Q('kns103', 'taal', 'In welk land in Zuid-Amerika is Nederlands de officiële taal?', 'Dans quel pays d’Amérique du Sud le néerlandais est-il la langue officielle ?',
    ['Suriname', 'Brazilië', 'Argentinië'], ['Le Suriname', 'Le Brésil', 'L’Argentine'],
    'Le Suriname est une ancienne colonie néerlandaise, indépendante depuis 1975. Le néerlandais y est resté la langue officielle.'),
  Q('kns104', 'taal', 'Welke tweede officiële taal spreken veel mensen in Friesland?', 'Quelle deuxième langue officielle beaucoup de gens parlent-ils en Frise ?',
    ['Fries', 'Engels', 'Duits'], ['Le frison', 'L’anglais', 'L’allemand'],
    'Le frison est reconnu comme langue officielle dans la province de Frise, à côté du néerlandais.'),
  Q('kns105', 'taal', 'Je begrijpt de huisarts niet goed. Wat doe je?', 'Vous ne comprenez pas bien le médecin. Que faites-vous ?',
    ['Je vraagt of hij het langzaam of met andere woorden wil zeggen', 'Je knikt en zegt niets', 'Je gaat weg'],
    ['Vous lui demandez de parler lentement ou autrement', 'Vous hochez la tête sans rien dire', 'Vous partez'],
    'Il est normal de dire « Wilt u dat herhalen? » ou « Ik begrijp het niet. » Mieux vaut demander que se tromper de traitement.'),
  Q('kns106', 'taal', 'Je hebt het examen in het buitenland gehaald. Ben je dan klaar met inburgeren?', 'Vous avez réussi l’examen à l’étranger. Votre intégration est-elle terminée ?',
    ['Nee, in Nederland moeten de meeste nieuwkomers verder met inburgeren', 'Ja, dan ben je klaar', 'Alleen als je wilt werken'],
    ['Non, aux Pays-Bas la plupart des nouveaux arrivants doivent poursuivre l’intégration', 'Oui, c’est terminé', 'Seulement si vous voulez travailler'],
    'L’examen à l’étranger est la première étape. Aux Pays-Bas, la commune fait un entretien d’accueil (brede intake) et il faut ensuite réussir l’examen d’intégration, en général au niveau B1, dans un délai de 3 ans.'),
  Q('kns107', 'taal', 'Wie betaalt de inburgeringscursus van een partner die naar Nederland komt (gezinsmigrant)?', 'Qui paie le cours d’intégration d’un partenaire venu aux Pays-Bas (regroupement familial) ?',
    ['De gezinsmigrant zelf; lenen bij DUO is mogelijk', 'De gemeente betaalt alles', 'De werkgever'],
    ['Le migrant familial lui-même ; un prêt de DUO est possible', 'La commune paie tout', 'L’employeur'],
    'Les migrants venus pour rejoindre leur famille paient eux-mêmes leur parcours d’intégration. DUO peut accorder un prêt.'),
  Q('kns108', 'taal', 'Wat zeg je als je iemand een fijne dag wilt wensen?', 'Que dites-vous pour souhaiter une bonne journée à quelqu’un ?',
    ['Fijne dag!', 'Gefeliciteerd!', 'Beterschap!'], ['Bonne journée !', 'Félicitations !', 'Bon rétablissement !'],
    '« Fijne dag! » = bonne journée. « Gefeliciteerd! » sert pour un anniversaire, « Beterschap! » pour une personne malade.'),
  Q('kns109', 'taal', 'Wat zeg je tegen iemand die ziek is?', 'Que dites-vous à quelqu’un qui est malade ?',
    ['Beterschap!', 'Proost!', 'Gefeliciteerd!'], ['Bon rétablissement !', 'Santé ! (en trinquant)', 'Félicitations !'],
    '« Beterschap! » = bon rétablissement. « Proost! » se dit en levant son verre.'),
  Q('kns110', 'taal', 'Waar kun je boeken lenen en vaak ook Nederlands oefenen, bijvoorbeeld in een taalcafé?', 'Où pouvez-vous emprunter des livres et souvent pratiquer le néerlandais, par exemple dans un « taalcafé » ?',
    ['In de bibliotheek', 'In de supermarkt', 'Bij de politie'], ['À la bibliothèque', 'Au supermarché', 'À la police'],
    'Les bibliothèques sont gratuites pour les enfants ; les adultes paient souvent un abonnement. Beaucoup proposent un « Taalhuis » ou un « taalcafé » pour pratiquer.'),

  // ── Histoire ──
  Q('kns111', 'geschiedenis', 'Wie was Willem van Oranje?', 'Qui était Guillaume d’Orange ?',
    ['De leider van de opstand tegen Spanje, de ‘Vader des Vaderlands’', 'De eerste president van Nederland', 'Een beroemde schilder'],
    ['Le chef de la révolte contre l’Espagne, le « Père de la Patrie »', 'Le premier président des Pays-Bas', 'Un peintre célèbre'],
    'Au XVIe siècle, il a mené la révolte contre le roi d’Espagne. Il est l’ancêtre de la famille royale actuelle, la maison d’Orange.'),
  Q('kns112', 'geschiedenis', 'Hoe heet de 17e eeuw, toen Nederland rijk werd door handel?', 'Comment appelle-t-on le XVIIe siècle, quand les Pays-Bas se sont enrichis grâce au commerce ?',
    ['De Gouden Eeuw', 'De IJzertijd', 'De Middeleeuwen'], ['Le Siècle d’or', 'L’âge du fer', 'Le Moyen Âge'],
    'C’est l’époque du commerce mondial, de Rembrandt et de la VOC. Elle a aussi un côté sombre : colonisation et esclavage.'),
  Q('kns113', 'geschiedenis', 'Wat was de VOC?', 'Qu’était la VOC ?',
    ['Een grote handelsmaatschappij, opgericht in 1602', 'Een voetbalclub', 'Een politieke partij'], ['Une grande compagnie de commerce fondée en 1602', 'Un club de football', 'Un parti politique'],
    'La Compagnie néerlandaise des Indes orientales commerçait en Asie. Elle a aussi joué un rôle dans la colonisation et l’esclavage.'),
  Q('kns114', 'geschiedenis', 'In welk jaar schafte Nederland de slavernij af in Suriname en op de Antillen?', 'En quelle année les Pays-Bas ont-ils aboli l’esclavage au Suriname et aux Antilles ?',
    ['In 1863', 'In 1945', 'In 2001'], ['En 1863', 'En 1945', 'En 2001'],
    'L’abolition date du 1er juillet 1863, mais beaucoup d’anciens esclaves ont dû travailler encore 10 ans. On la commémore chaque 1er juillet (Keti Koti). En 2023, le roi a présenté des excuses.'),
  Q('kns115', 'geschiedenis', 'Wat gebeurde er in 1953 in het zuidwesten van Nederland?', 'Que s’est-il passé en 1953 dans le sud-ouest des Pays-Bas ?',
    ['Een grote overstroming: de watersnoodramp', 'Een aardbeving', 'Een grote brand'], ['Une grande inondation : la catastrophe de 1953', 'Un tremblement de terre', 'Un grand incendie'],
    'Une tempête a rompu les digues : plus de 1 800 morts. Ensuite, les Pays-Bas ont construit les Deltawerken.'),
  Q('kns116', 'geschiedenis', 'Waarom kwamen er in de jaren 60 en 70 veel gastarbeiders naar Nederland?', 'Pourquoi beaucoup de travailleurs immigrés sont-ils venus dans les années 60 et 70 ?',
    ['Er was veel werk in fabrieken en te weinig werknemers', 'Voor vakantie', 'Om te studeren'],
    ['Il y avait beaucoup de travail en usine et pas assez de travailleurs', 'Pour les vacances', 'Pour étudier'],
    'Ils venaient notamment d’Italie, d’Espagne, de Turquie et du Maroc. Beaucoup sont restés et ont fait venir leur famille.'),
  Q('kns117', 'geschiedenis', 'Wanneer werd Suriname onafhankelijk?', 'Quand le Suriname est-il devenu indépendant ?',
    ['In 1975', 'In 1863', 'In 1945'], ['En 1975', 'En 1863', 'En 1945'],
    'Avant et après l’indépendance, beaucoup de Surinamais sont venus s’installer aux Pays-Bas.'),
  Q('kns118', 'geschiedenis', 'Sinds wanneer mogen vrouwen in Nederland stemmen?', 'Depuis quand les femmes peuvent-elles voter aux Pays-Bas ?',
    ['Sinds 1919', 'Sinds 2001', 'Sinds 1850'], ['Depuis 1919', 'Depuis 2001', 'Depuis 1850'],
    'Les femmes pouvaient être élues dès 1917 et ont obtenu le droit de vote en 1919.'),
  Q('kns119', 'geschiedenis', 'Hoe heet het volkslied van Nederland?', 'Comment s’appelle l’hymne national des Pays-Bas ?',
    ['Het Wilhelmus', 'De Marseillaise', 'God save the King'], ['Le Wilhelmus', 'La Marseillaise', 'God save the King'],
    'Le Wilhelmus parle de Guillaume d’Orange. C’est l’un des plus anciens hymnes nationaux du monde.'),
  Q('kns120', 'geschiedenis', 'Met welk geld betaal je sinds 2002 in Nederland?', 'Avec quelle monnaie paie-t-on aux Pays-Bas depuis 2002 ?',
    ['De euro', 'De gulden', 'De dollar'], ['L’euro', 'Le florin', 'Le dollar'],
    'Avant l’euro, c’était le florin (gulden). Les Pays-Bas font partie des fondateurs de l’Union européenne.'),

  // ── Géographie & logement ──
  Q('kns121', 'wonen', 'Hoeveel provincies heeft Nederland?', 'Combien de provinces compte les Pays-Bas ?',
    ['12', '8', '20'], ['12', '8', '20'],
    'Par exemple la Hollande-Septentrionale, la Hollande-Méridionale, Utrecht, la Frise, le Limbourg…'),
  Q('kns122', 'wonen', 'Wat is de hoofdstad van Nederland?', 'Quelle est la capitale des Pays-Bas ?',
    ['Amsterdam', 'Den Haag', 'Rotterdam'], ['Amsterdam', 'La Haye', 'Rotterdam'],
    'Amsterdam est la capitale. Le gouvernement, le parlement et le roi travaillent à La Haye.'),
  Q('kns123', 'wonen', 'Welke landen zijn de buurlanden van Nederland?', 'Quels pays sont voisins des Pays-Bas ?',
    ['België en Duitsland', 'Frankrijk en Spanje', 'Denemarken en Polen'], ['La Belgique et l’Allemagne', 'La France et l’Espagne', 'Le Danemark et la Pologne'],
    'Au sud la Belgique, à l’est l’Allemagne, au nord et à l’ouest la mer du Nord.'),
  Q('kns124', 'wonen', 'Welke grote rivieren stromen door Nederland?', 'Quels grands fleuves traversent les Pays-Bas ?',
    ['De Rijn en de Maas', 'De Nijl en de Donau', 'De Seine en de Loire'], ['Le Rhin et la Meuse', 'Le Nil et le Danube', 'La Seine et la Loire'],
    'Le Rhin et la Meuse se jettent dans la mer du Nord. Le port de Rotterdam est à leur embouchure.'),
  Q('kns125', 'wonen', 'Welke landen horen bij het Koninkrijk der Nederlanden?', 'Quels pays font partie du Royaume des Pays-Bas ?',
    ['Nederland, Aruba, Curaçao en Sint Maarten', 'Nederland en België', 'Alleen Nederland'], ['Les Pays-Bas, Aruba, Curaçao et Saint-Martin', 'Les Pays-Bas et la Belgique', 'Seulement les Pays-Bas'],
    'Le Royaume compte 4 pays. Bonaire, Saint-Eustache et Saba sont des communes spéciales des Pays-Bas.'),
  Q('kns126', 'wonen', 'Je wilt een goedkope huurwoning van een woningcorporatie. Hoe werkt dat meestal?', 'Vous voulez un logement social bon marché. Comment cela marche-t-il en général ?',
    ['Je schrijft je in en wacht, soms jaren (wachtlijst)', 'Je krijgt meteen een huis van de gemeente', 'Je koopt een lot'],
    ['Vous vous inscrivez et attendez, parfois des années (liste d’attente)', 'La commune vous donne tout de suite un logement', 'Vous achetez un billet de loterie'],
    'Il y a peu de logements sociaux et les listes d’attente sont longues, surtout dans les grandes villes. Inscrivez-vous tôt.'),
  Q('kns127', 'wonen', 'Je kunt de huur deze maand niet op tijd betalen. Wat doe je?', 'Vous ne pouvez pas payer le loyer à temps ce mois-ci. Que faites-vous ?',
    ['Zo snel mogelijk contact opnemen met de verhuurder', 'Niets zeggen en wachten', 'Verhuizen zonder iets te zeggen'],
    ['Contacter le propriétaire le plus vite possible', 'Ne rien dire et attendre', 'Déménager sans rien dire'],
    'Prévenir tôt permet souvent un plan de paiement. La commune peut aussi aider en cas de dettes.'),
  Q('kns128', 'wonen', 'Hoe parkeer je je fiets het veiligst?', 'Comment garer votre vélo le plus sûrement ?',
    ['Altijd op slot, het liefst met twee sloten', 'Zonder slot, dat is niet nodig', 'In de hal van de buren'],
    ['Toujours cadenassé, de préférence avec deux antivols', 'Sans antivol, ce n’est pas nécessaire', 'Dans le hall des voisins'],
    'Les vols de vélos sont fréquents. Attachez aussi le cadre à un range-vélos.'),

  // ── État, droits & démarches ──
  Q('kns129', 'staat', 'Wie beslist in een rechtszaak?', 'Qui décide dans une affaire en justice ?',
    ['Een onafhankelijke rechter', 'De politie', 'De burgemeester'], ['Un juge indépendant', 'La police', 'Le maire'],
    'Aux Pays-Bas, ce sont des juges indépendants qui jugent (il n’y a pas de jury). Le gouvernement ne peut pas leur donner d’ordres.'),
  Q('kns130', 'staat', 'Je hebt een juridisch probleem en weinig geld. Waar krijg je gratis advies?', 'Vous avez un problème juridique et peu d’argent. Où obtenir un conseil gratuit ?',
    ['Bij het Juridisch Loket', 'Bij de supermarkt', 'Bij de Belastingdienst'], ['Au Juridisch Loket', 'Au supermarché', 'Aux impôts'],
    'Le Juridisch Loket donne des conseils juridiques gratuits, par téléphone ou en ligne. Si vous avez besoin d’un avocat, une aide financière est possible.'),
  Q('kns131', 'staat', 'Je wordt gediscrimineerd bij het zoeken naar werk. Wat kun je doen?', 'Vous êtes discriminé en cherchant du travail. Que pouvez-vous faire ?',
    ['Het melden bij een antidiscriminatievoorziening of bij de politie', 'Niets, dat is normaal', 'Zelf wraak nemen'],
    ['Le signaler à un service anti-discrimination ou à la police', 'Rien, c’est normal', 'Vous venger vous-même'],
    'La discrimination est interdite (article 1 de la Constitution). Chaque commune a un point de signalement ; on peut aussi porter plainte.'),
  Q('kns132', 'staat', 'Wat is de taak van de politie?', 'Quel est le rôle de la police ?',
    ['Zorgen voor veiligheid en mensen helpen', 'Belasting innen', 'Scholen leiden'], ['Assurer la sécurité et aider les gens', 'Percevoir les impôts', 'Diriger les écoles'],
    'La police aide aussi les citoyens. Vous pouvez lui demander de l’aide sans crainte.'),
  Q('kns133', 'staat', 'Voor welke organen zijn er verkiezingen in Nederland?', 'Pour quelles institutions y a-t-il des élections aux Pays-Bas ?',
    ['Onder andere de Tweede Kamer, de gemeenteraad en de provincie', 'Alleen voor de koning', 'Er zijn geen verkiezingen'],
    ['Entre autres la Tweede Kamer, le conseil municipal et la province', 'Seulement pour le roi', 'Il n’y a pas d’élections'],
    'Il y a aussi des élections pour les waterschappen et le Parlement européen. Le roi, lui, n’est pas élu.'),
  Q('kns134', 'staat', 'De politie vraagt op straat naar je identiteit. Wat moet je laten zien (vanaf 14 jaar)?', 'La police vous demande votre identité dans la rue. Que devez-vous montrer (à partir de 14 ans) ?',
    ['Een geldig identiteitsbewijs, zoals paspoort, ID-kaart of verblijfsdocument', 'Niets', 'Alleen je bankpas'],
    ['Une pièce d’identité valide : passeport, carte d’identité ou titre de séjour', 'Rien', 'Seulement votre carte bancaire'],
    'À partir de 14 ans, il faut pouvoir montrer une pièce d’identité quand la police le demande. Sinon : amende possible.'),
  Q('kns135', 'staat', 'Welke organisatie beslist over je verblijfsvergunning?', 'Quel organisme décide de votre titre de séjour ?',
    ['De IND', 'DUO', 'De huisarts'], ['L’IND', 'DUO', 'Le médecin'],
    'L’IND (service d’immigration et de naturalisation) traite les demandes de séjour, dont le visa MVV.'),
  Q('kns136', 'staat', 'Mag een man zijn vrouw verbieden om te werken of te studeren?', 'Un mari peut-il interdire à sa femme de travailler ou d’étudier ?',
    ['Nee, vrouwen beslissen zelf over hun leven', 'Ja, dat mag', 'Alleen als ze kinderen hebben'],
    ['Non, les femmes décident elles-mêmes de leur vie', 'Oui, c’est permis', 'Seulement si elles ont des enfants'],
    'Hommes et femmes ont les mêmes droits. Chacun décide de son travail, de ses études, de son argent et de ses relations.'),

  // ── Enfants & école ──
  Q('kns137', 'onderwijs', 'Wat is het consultatiebureau?', 'Qu’est-ce que le « consultatiebureau » ?',
    ['Een plek waar baby’s en jonge kinderen gratis worden gecontroleerd en ingeënt', 'Een school', 'Een kinderdagverblijf'],
    ['Un lieu où les bébés et jeunes enfants sont suivis et vaccinés gratuitement', 'Une école', 'Une crèche'],
    'Jusqu’à 4 ans, on y surveille la croissance et le développement de l’enfant et on donne les vaccins. C’est gratuit.'),
  Q('kns138', 'onderwijs', 'Mag je je kind slaan als straf?', 'Pouvez-vous frapper votre enfant pour le punir ?',
    ['Nee, geweld tegen kinderen is verboden', 'Ja, dat mag thuis', 'Alleen een beetje'], ['Non, la violence envers les enfants est interdite', 'Oui, à la maison', 'Seulement un peu'],
    'Depuis 2007, la loi interdit toute violence dans l’éducation des enfants. Des services (consultatiebureau, CJG) aident les parents.'),
  Q('kns139', 'onderwijs', 'Wat is kinderbijslag?', 'Qu’est-ce que la « kinderbijslag » ?',
    ['Geld van de overheid (SVB) voor de kosten van kinderen tot 18 jaar', 'Een boete voor ouders', 'Een schoolboek'],
    ['De l’argent de l’État (SVB) pour les frais des enfants jusqu’à 18 ans', 'Une amende pour les parents', 'Un livre scolaire'],
    'Ce sont les allocations familiales, versées chaque trimestre par la SVB.'),
  Q('kns140', 'onderwijs', 'Wat doen de meeste kinderen als ze 4 jaar worden?', 'Que font la plupart des enfants quand ils ont 4 ans ?',
    ['Ze gaan naar de basisschool (groep 1)', 'Ze blijven thuis tot 7 jaar', 'Ze gaan werken'], ['Ils entrent à l’école primaire (groep 1)', 'Ils restent à la maison jusqu’à 7 ans', 'Ils travaillent'],
    'L’école est obligatoire à partir de 5 ans, mais presque tous les enfants commencent à 4 ans.'),
  Q('kns141', 'onderwijs', 'Waar kunnen kleine kinderen overdag zijn als hun ouders werken?', 'Où les petits enfants peuvent-ils aller la journée quand leurs parents travaillent ?',
    ['Bij de kinderopvang, bijvoorbeeld een kinderdagverblijf', 'Bij de huisarts', 'Op het gemeentehuis'], ['À la garde d’enfants, par exemple une crèche', 'Chez le médecin', 'À la mairie'],
    'Les parents qui travaillent peuvent recevoir une aide pour les frais de garde (kinderopvangtoeslag).'),
  Q('kns142', 'onderwijs', 'Wie beslissen over de opvoeding van de kinderen?', 'Qui décide de l’éducation des enfants ?',
    ['De vader en de moeder samen', 'Alleen de vader', 'Alleen de grootouders'], ['Le père et la mère ensemble', 'Seulement le père', 'Seulement les grands-parents'],
    'Les deux parents ont autant de droits et de responsabilités, aussi après une séparation.'),
  Q('kns143', 'onderwijs', 'Je kind wordt gepest op school. Wat doe je?', 'Votre enfant est harcelé à l’école. Que faites-vous ?',
    ['Je praat met de leerkracht of de mentor', 'Je doet niets', 'Je gaat de andere kinderen straffen'],
    ['Vous parlez à l’enseignant ou au tuteur', 'Vous ne faites rien', 'Vous allez punir les autres enfants'],
    'Chaque école doit agir contre le harcèlement (pesten). Parlez-en d’abord à l’enseignant.'),
  Q('kns144', 'onderwijs', 'Tot welke leeftijd is iemand minderjarig?', 'Jusqu’à quel âge est-on mineur ?',
    ['Tot 18 jaar', 'Tot 16 jaar', 'Tot 21 jaar'], ['Jusqu’à 18 ans', 'Jusqu’à 16 ans', 'Jusqu’à 21 ans'],
    'À 18 ans, on est majeur : on peut voter, signer un contrat et on paie soi-même son assurance maladie.'),

  // ── Santé & soins ──
  Q('kns145', 'zorg', 'Je bent zwanger. Bij wie ga je meestal voor controles?', 'Vous êtes enceinte. Chez qui allez-vous en général pour les contrôles ?',
    ['Bij de verloskundige', 'Bij de tandarts', 'Bij de apotheek'], ['Chez la sage-femme', 'Chez le dentiste', 'À la pharmacie'],
    'Pour une grossesse normale, on est suivie par une sage-femme (verloskundige), sans passer par le médecin. On peut accoucher à la maison ou à l’hôpital.'),
  Q('kns146', 'zorg', 'Wat is kraamzorg?', 'Qu’est-ce que la « kraamzorg » ?',
    ['Hulp thuis voor moeder en baby in de eerste dagen na de geboorte', 'Een winkel met babykleding', 'Een school voor baby’s'],
    ['Une aide à domicile pour la mère et le bébé les premiers jours après la naissance', 'Un magasin de vêtements pour bébé', 'Une école pour bébés'],
    'Une assistante vient à la maison pendant environ une semaine. Il faut la réserver tôt pendant la grossesse ; l’assurance de base la rembourse, avec une petite participation.'),
  Q('kns147', 'zorg', 'Wat is een zorgpas?', 'Qu’est-ce qu’une « zorgpas » ?',
    ['Een pasje van je zorgverzekeraar dat je laat zien bij arts, apotheek of ziekenhuis', 'Een bankpas', 'Een OV-chipkaart'],
    ['La carte de votre assurance maladie, à montrer chez le médecin, à la pharmacie ou à l’hôpital', 'Une carte bancaire', 'Une carte de transport'],
    'Elle contient votre numéro d’assuré. Gardez-la toujours sur vous avec votre pièce d’identité.'),
  Q('kns148', 'zorg', 'Je voelt je al lang somber en gestrest. Wie kan je helpen?', 'Vous vous sentez déprimé et stressé depuis longtemps. Qui peut vous aider ?',
    ['Je huisarts; die kan je ook doorsturen naar een psycholoog', 'Niemand; dat is geen ziekte', 'Alleen de politie'],
    ['Votre généraliste ; il peut aussi vous orienter vers un psychologue', 'Personne ; ce n’est pas une maladie', 'Seulement la police'],
    'La santé mentale fait partie des soins. Le huisarts est aussi le premier contact dans ce cas.'),
  Q('kns149', 'zorg', 'Betaalt de basisverzekering de tandarts voor volwassenen?', 'L’assurance de base rembourse-t-elle le dentiste pour les adultes ?',
    ['Meestal niet; daarvoor kun je een aanvullende verzekering nemen', 'Ja, altijd alles', 'Alleen voor mannen'],
    ['En général non ; on peut prendre une assurance complémentaire', 'Oui, toujours tout', 'Seulement pour les hommes'],
    'Pour les moins de 18 ans, le dentiste est remboursé. Pour les adultes, il faut en général une assurance complémentaire (aanvullende verzekering).'),
  Q('kns150', 'zorg', 'Wat is zorgtoeslag?', 'Qu’est-ce que la « zorgtoeslag » ?',
    ['Een bijdrage van de overheid in de premie van de zorgverzekering bij een laag inkomen', 'Een boete', 'Het salaris van de arts'],
    ['Une aide de l’État pour payer la prime d’assurance maladie quand le revenu est bas', 'Une amende', 'Le salaire du médecin'],
    'On la demande à la Belastingdienst (service Toeslagen). Attention : signalez tout changement de revenu pour éviter de devoir rembourser.'),
  Q('kns151', 'zorg', 'Moet je je kind laten vaccineren?', 'Devez-vous faire vacciner votre enfant ?',
    ['Het is vrijwillig, maar gratis en bijna alle ouders doen het', 'Het is verboden', 'Het kost veel geld'],
    ['C’est volontaire, mais gratuit, et presque tous les parents le font', 'C’est interdit', 'Cela coûte très cher'],
    'Le programme national de vaccination protège contre des maladies graves. Les vaccins se font au consultatiebureau.'),
  Q('kns152', 'zorg', 'Wat neem je mee naar je eerste afspraak bij een nieuwe huisarts?', 'Qu’apportez-vous à votre premier rendez-vous chez un nouveau généraliste ?',
    ['Je identiteitsbewijs en je zorgpas', 'Je rijbewijs en je fiets', 'Niets'], ['Votre pièce d’identité et votre carte d’assurance', 'Votre permis et votre vélo', 'Rien'],
    'Pensez aussi à la liste de vos médicaments.'),

  // ── Travail & argent ──
  Q('kns153', 'werk', 'Wat is de AOW?', 'Qu’est-ce que l’AOW ?',
    ['Het basispensioen van de overheid als je oud bent, vanaf ongeveer 67 jaar', 'Een uitkering voor studenten', 'Een belasting op auto’s'],
    ['La pension de base de l’État pour les personnes âgées, à partir de 67 ans environ', 'Une allocation pour étudiants', 'Une taxe sur les voitures'],
    'L’âge est 67 ans en 2026-2027, puis 67 ans et 3 mois à partir de 2028. Le montant dépend du nombre d’années vécues aux Pays-Bas.'),
  Q('kns154', 'werk', 'Hoe betalen de meeste mensen in de winkel?', 'Comment la plupart des gens paient-ils en magasin ?',
    ['Met de bankpas (pinnen) of met de telefoon', 'Alleen contant', 'Met een cheque'], ['Par carte bancaire (« pinnen ») ou avec le téléphone', 'Seulement en espèces', 'Par chèque'],
    'Un compte bancaire néerlandais est vite indispensable : salaire, loyer et aides y sont versés.'),
  Q('kns155', 'werk', 'Je hebt schulden en kunt je rekeningen niet betalen. Waar vraag je hulp?', 'Vous avez des dettes et ne pouvez plus payer vos factures. Où demander de l’aide ?',
    ['Bij de gemeente (schuldhulpverlening)', 'Nergens', 'Bij een onbekende op straat'], ['À la commune (aide au désendettement)', 'Nulle part', 'À un inconnu dans la rue'],
    'L’aide de la commune est gratuite. Plus on demande tôt, plus il est facile de trouver une solution.'),
  Q('kns156', 'werk', 'Je krijgt een brief om aangifte te doen bij de Belastingdienst. Wanneer doe je dat meestal?', 'Vous recevez une lettre pour faire votre déclaration d’impôts. Quand la faites-vous en général ?',
    ['Vóór 1 mei', 'Wanneer je wilt', 'Nooit'], ['Avant le 1er mai', 'Quand vous voulez', 'Jamais'],
    'La déclaration de revenus se fait chaque année, en général avant le 1er mai. On peut demander un délai.'),
  Q('kns157', 'werk', 'Wat is een vakbond?', 'Qu’est-ce qu’un « vakbond » ?',
    ['Een organisatie die opkomt voor de belangen van werknemers', 'Een bank', 'Een school'], ['Une organisation qui défend les intérêts des salariés', 'Une banque', 'Une école'],
    'C’est un syndicat. Il négocie par exemple les conventions collectives (cao) sur le salaire et les conditions de travail.'),
  Q('kns158', 'werk', 'Mag een werkgever een vrouw minder betalen voor hetzelfde werk?', 'Un employeur peut-il payer une femme moins pour le même travail ?',
    ['Nee, dat is verboden', 'Ja, dat mag', 'Alleen als ze jong is'], ['Non, c’est interdit', 'Oui, c’est permis', 'Seulement si elle est jeune'],
    'Salaire égal pour un travail égal : c’est la loi.'),
  Q('kns159', 'werk', 'Wat is een uitzendbureau?', 'Qu’est-ce qu’un « uitzendbureau » ?',
    ['Een bedrijf dat mensen helpt aan (tijdelijk) werk', 'Een reisbureau', 'Een postkantoor'], ['Une agence qui aide les gens à trouver du travail (temporaire)', 'Une agence de voyage', 'Un bureau de poste'],
    'C’est une agence d’intérim. Beaucoup de nouveaux arrivants trouvent un premier emploi par ce biais.'),
  Q('kns160', 'werk', 'Wat is een bijstandsuitkering?', 'Qu’est-ce que la « bijstand » ?',
    ['Geld van de gemeente voor mensen die niet genoeg inkomen hebben om van te leven', 'Een bonus van de werkgever', 'Een lening van de bank'],
    ['Une aide de la commune pour les personnes sans revenu suffisant pour vivre', 'Une prime de l’employeur', 'Un prêt de la banque'],
    'C’est le revenu minimum social. Attention : pour certains titres de séjour, demander la bijstand peut avoir des conséquences. Renseignez-vous d’abord (IND).'),

  // ── Vie quotidienne & usages ──
  Q('kns161', 'usages', 'Je bent uitgenodigd om te eten om 18.00 uur. Hoe laat kom je?', 'Vous êtes invité à dîner à 18 h. À quelle heure arrivez-vous ?',
    ['Rond 18.00 uur, niet veel later', 'Om 20.00 uur', 'Wanneer je wilt'], ['Vers 18 h, pas beaucoup plus tard', 'À 20 h', 'Quand vous voulez'],
    'Aux Pays-Bas, on dîne tôt (souvent vers 18 h) et on arrive à l’heure. En cas de retard, prévenez.'),
  Q('kns162', 'usages', 'Je hebt nieuwe buren. Wat is gebruikelijk?', 'Vous avez de nouveaux voisins. Qu’est-ce qui est habituel ?',
    ['Je stelt je even voor', 'Je doet alsof je ze niet ziet', 'Je vraagt meteen geld te lenen'], ['Vous vous présentez brièvement', 'Vous faites semblant de ne pas les voir', 'Vous leur demandez tout de suite de l’argent'],
    'Se présenter aux voisins est courant, surtout quand on emménage. Cela facilite beaucoup de choses.'),
  Q('kns163', 'usages', 'In de volle bus staat een oudere vrouw. Wat is beleefd?', 'Dans le bus plein, une dame âgée est debout. Qu’est-ce qui est poli ?',
    ['Je staat op en geeft haar je plaats', 'Je blijft zitten en kijkt weg', 'Je vraagt haar om geld'], ['Vous vous levez et lui laissez votre place', 'Vous restez assis et regardez ailleurs', 'Vous lui demandez de l’argent'],
    'Céder sa place aux personnes âgées, enceintes ou handicapées est une règle de politesse.'),
  Q('kns164', 'usages', 'Een Nederlandse collega zegt direct ‘nee’ tegen je idee. Wat betekent dat meestal?', 'Un collègue néerlandais dit directement « non » à votre idée. Qu’est-ce que cela signifie en général ?',
    ['Nederlanders zijn vaak direct; het is niet onbeleefd bedoeld', 'Hij wil ruzie', 'Nee betekent eigenlijk ja'],
    ['Les Néerlandais sont souvent directs ; ce n’est pas de l’impolitesse', 'Il cherche la dispute', '« Non » veut dire « oui »'],
    'La franchise est appréciée : on dit ce qu’on pense, poliment. Vous pouvez faire de même.'),
];
