// Grammaire, construction de phrases, lecture et écoute.
// Explications en français ; le matériel de pratique reste en néerlandais.

// ── Construction de phrases ─────────────────────────────
// words : les mots à placer (minuscules, sans ponctuation, sauf noms propres).
// answer : la phrase modèle ; alts : autres ordres corrects (acceptés aussi).
export const PUZZLES = [
  { id: 'pz01', fr: 'Demain, je vais chez le médecin.', answer: 'Morgen ga ik naar de dokter.', alts: ['Ik ga morgen naar de dokter.'],
    rule: 'Si la phrase commence par un autre mot que le sujet (ici « morgen »), le verbe reste en 2e position et le sujet passe après : Morgen <b>ga ik</b>…' },
  { id: 'pz02', fr: 'J’habite dans un petit appartement.', answer: 'Ik woon in een klein appartement.', alts: [],
    rule: 'Ordre de base : sujet + verbe + reste. L’adjectif se place avant le nom.' },
  { id: 'pz03', fr: 'Comme je suis malade, je reste à la maison.', answer: 'Omdat ik ziek ben, blijf ik thuis.', alts: ['Ik blijf thuis, omdat ik ziek ben.'],
    rule: 'Après « omdat », le verbe va à la fin : omdat ik ziek <b>ben</b>. Si la phrase commence par cette partie, la suite commence par le verbe : <b>blijf ik</b> thuis.' },
  { id: 'pz04', fr: 'À six heures, nous mangeons ensemble.', answer: 'Om zes uur eten wij samen.', alts: ['Wij eten om zes uur samen.', 'Wij eten samen om zes uur.'],
    rule: 'Verbe en 2e position : « Om zes uur » compte comme un seul élément, puis vient le verbe « eten ».' },
  { id: 'pz05', fr: 'Les enfants jouent dans le jardin.', answer: 'De kinderen spelen in de tuin.', alts: ['In de tuin spelen de kinderen.'],
    rule: 'Sujet + verbe + lieu. On peut aussi commencer par le lieu, mais le verbe reste 2e.' },
  { id: 'pz06', fr: 'Je n’ai pas de voiture.', answer: 'Ik heb geen auto.', alts: [],
    rule: 'Devant un nom sans article défini, la négation est « geen » (et pas « niet »).' },
  { id: 'pz07', fr: 'Où est l’arrêt de bus ?', answer: 'Waar is de bushalte?', alts: [],
    rule: 'Question avec un mot interrogatif : mot interrogatif + verbe + sujet.' },
  { id: 'pz08', fr: 'Le lundi, il travaille.', answer: 'Op maandag werkt hij.', alts: ['Hij werkt op maandag.'],
    rule: 'Inversion : après « Op maandag », le verbe « werkt » vient avant le sujet « hij ».' },
  { id: 'pz09', fr: 'Je lis un livre.', answer: 'Ik lees een boek.', alts: [],
    rule: 'Sujet + verbe + complément, comme en français.' },
  { id: 'pz10', fr: 'Bonne chance pour ton examen !', answer: 'Veel succes met je examen!', alts: [],
    rule: 'Expression figée à apprendre par cœur : « Veel succes met… ».' },
];

// ── Questions de grammaire ──────────────────────────────
export const GRAMMAR_Q = [
  { id: 'gr01', q: 'Welk lidwoord hoort bij ‘huis’?', qFr: 'Quel article va avec « huis » (maison) ?', opts: ['de', 'het'], corr: 1,
    expl: 'On dit « het huis ». Environ deux tiers des noms prennent « de » ; les mots en -je (diminutifs) prennent toujours « het ». Apprenez chaque nom avec son article.' },
  { id: 'gr02', q: 'Ik heb … auto.', qFr: 'Je n’ai pas de voiture.', opts: ['niet', 'geen', 'niets'], corr: 1,
    expl: 'Devant un nom sans « de/het », on utilise « geen ». « Niet » sert pour le reste : Ik werk niet. Het is niet duur.' },
  { id: 'gr03', q: 'Morgen … ik werken.', qFr: 'Demain, je vais travailler.', opts: ['ga', 'gaan', 'gaat'], corr: 0,
    expl: 'Avec « ik », le verbe est le radical : ik ga. Le verbe reste en 2e position, avant le sujet, car la phrase commence par « morgen ».' },
  { id: 'gr04', q: 'Wat is het meervoud van ‘kind’?', qFr: 'Quel est le pluriel de « kind » (enfant) ?', opts: ['kinds', 'kinderen', 'kinden'], corr: 1,
    expl: 'Pluriel irrégulier : een kind → twee kinderen. La plupart des noms prennent -en (boek → boeken) ou -s (tafel → tafels).' },
  { id: 'gr05', q: 'Na welk woord staat het werkwoord aan het einde van de zin?', qFr: 'Après quel mot le verbe va-t-il à la fin de la phrase ?', opts: ['en', 'want', 'omdat'], corr: 2,
    expl: '« Omdat » (parce que) introduit une subordonnée : le verbe va à la fin. Avec « want » et « en », l’ordre normal reste : …want ik ben ziek / …omdat ik ziek ben.' },
  { id: 'gr06', q: 'De docent … de les.', qFr: 'Le professeur commence la leçon.', opts: ['begin', 'begint', 'beginnen'], corr: 1,
    expl: 'Avec hij / zij / het (ou un nom au singulier), on ajoute -t au radical : begin + t = begint.' },
  { id: 'gr07', q: 'Gisteren … ik de hele dag.', qFr: 'Hier, j’ai travaillé toute la journée.', opts: ['werkte', 'werkde', 'werken'], corr: 0,
    expl: 'Passé des verbes réguliers : si la dernière lettre du radical est dans « ’t kofschip » (t, k, f, s, ch, p), on ajoute -te ; sinon -de. werk → k → werkte. woon → n → woonde.' },
  { id: 'gr08', q: 'Welk lidwoord hoort bij ‘tafel’?', qFr: 'Quel article va avec « tafel » (table) ?', opts: ['de', 'het'], corr: 0,
    expl: 'On dit « de tafel ». Au pluriel, tous les noms prennent « de » : de tafels, de huizen.' },
  { id: 'gr09', q: 'Ik woon … Amsterdam.', qFr: 'J’habite à Amsterdam.', opts: ['op', 'in', 'aan'], corr: 1,
    expl: 'On habite « in » une ville ou un pays : in Amsterdam, in Nederland. Mais : op de derde verdieping (au 3e étage).' },
  { id: 'gr10', q: 'Het boek ligt … de tafel.', qFr: 'Le livre est posé sur la table.', opts: ['op', 'in', 'uit'], corr: 0,
    expl: '« Op » = sur une surface. « In » = dans : het boek zit in de tas.' },
];

// ── Lecture : documents du quotidien ────────────────────
// doc : texte du document (HTML simple, contenu interne) ; qFr : traduction de la question ; expl : explication.
export const READING = [
  { id: 'rd01', title: 'Folder van de supermarkt', style: 'blue',
    doc: '<b>SUPERACTIE!</b><br>2 pakken halfvolle melk voor de prijs van 1.<br>Geldig van maandag tot en met zondag.<br>Maximaal 3 acties per klant.',
    q: 'Tot wanneer is deze aanbieding geldig?', qFr: 'Jusqu’à quand cette offre est-elle valable ?',
    opts: ['Alleen vandaag', 'Tot en met zondag', 'Tot volgende maand'], corr: 1,
    expl: '« Tot en met zondag » = jusqu’à dimanche inclus.' },
  { id: 'rd02', title: 'Huurcontract, artikel 4', style: 'plain',
    doc: 'Artikel 4 – Huisdieren<br>Honden en katten zijn in dit appartement niet toegestaan zonder schriftelijke toestemming van de verhuurder.',
    q: 'Mag u zomaar een hond in het appartement hebben?', qFr: 'Pouvez-vous avoir un chien dans l’appartement sans rien demander ?',
    opts: ['Ja, altijd', 'Nee, alleen met schriftelijke toestemming', 'Alleen in het weekend'], corr: 1,
    expl: '« Niet toegestaan zonder schriftelijke toestemming » = interdit sans autorisation écrite.' },
  { id: 'rd03', title: 'Openingstijden huisartsenpraktijk', style: 'grey',
    doc: 'Maandag t/m vrijdag: 08.00 – 17.00 uur<br>Tussen 12.30 en 13.30 uur gesloten (lunch).<br>Zaterdag en zondag gesloten.',
    q: 'Is de praktijk op woensdag om 13.00 uur open?', qFr: 'Le cabinet est-il ouvert le mercredi à 13 h ?',
    opts: ['Nee, dan is het lunchpauze', 'Ja, de hele dag', 'Alleen op afspraak'], corr: 0,
    expl: 'Entre 12 h 30 et 13 h 30, le cabinet est fermé pour le déjeuner.' },
  { id: 'rd04', title: 'Afvalkalender', style: 'green',
    doc: 'Groene container (gft): zet de container elke dinsdag vóór 07.30 uur aan de straat.<br>Haal hem na het legen vóór 19.00 uur weer binnen.',
    q: 'Wanneer moet de container buiten staan?', qFr: 'Quand la poubelle doit-elle être dehors ?',
    opts: ['Dinsdag vóór 07.30 uur', 'Dinsdagavond', 'Maandag om 12.00 uur'], corr: 0,
    expl: '« Vóór 07.30 uur » = avant 7 h 30.' },
  { id: 'rd05', title: 'Uitnodiging buurtfeest', style: 'amber',
    doc: 'Beste buren,<br>Aanstaande zaterdag om 16.00 uur houden we een barbecue in de binnentuin.<br>Neem je eigen drinken mee!',
    q: 'Wat moet u zelf meenemen?', qFr: 'Que devez-vous apporter vous-même ?',
    opts: ['Vlees', 'Uw eigen drinken', 'Een tafel'], corr: 1,
    expl: '« Neem je eigen drinken mee » = apportez vos propres boissons.' },
  { id: 'rd06', title: 'Rekening energieleverancier', style: 'plain',
    doc: 'Te betalen: € 120,50<br>Wij schrijven dit bedrag rond de 28e van deze maand automatisch af.<br>Zorg dat er genoeg geld op uw rekening staat.',
    q: 'Wanneer wordt het geld afgeschreven?', qFr: 'Quand l’argent sera-t-il prélevé ?',
    opts: ['Vandaag', 'Rond de 28e van deze maand', 'Volgend jaar'], corr: 1,
    expl: '« Afschrijven » = prélever sur votre compte ; « rond de 28e » = vers le 28.' },
  { id: 'rd07', title: 'Vacature', style: 'orange',
    doc: 'Gezocht: winkelmedewerker, 24 uur per week.<br>Ervaring is fijn, maar niet nodig.<br>Je spreekt goed Nederlands.',
    q: 'Hoeveel uur per week is deze baan?', qFr: 'Combien d’heures par semaine compte ce poste ?',
    opts: ['12 uur', '24 uur', '40 uur'], corr: 1,
    expl: '« 24 uur per week » = 24 heures par semaine.' },
  { id: 'rd08', title: 'Bord in het park', style: 'red',
    doc: 'VERBODEN TE FIETSEN OP HET GRAS.<br>Honden altijd aan de lijn.<br>Wie dit niet doet, kan een boete krijgen.',
    q: 'Wat is verplicht voor honden?', qFr: 'Qu’est-ce qui est obligatoire pour les chiens ?',
    opts: ['Ze mogen los lopen', 'Ze moeten aan de lijn', 'Ze mogen niet in het park'], corr: 1,
    expl: '« Aan de lijn » = tenu en laisse.' },
  { id: 'rd09', title: 'Etiket van de apotheek', style: 'grey',
    doc: 'Paracetamol 500 mg<br>Drie keer per dag 1 tablet innemen, met water, tijdens of na het eten.<br>Buiten bereik van kinderen bewaren.',
    q: 'Hoe vaak per dag neemt u een tablet?', qFr: 'Combien de fois par jour prenez-vous un comprimé ?',
    opts: ['1 keer', '2 keer', '3 keer'], corr: 2,
    expl: '« Drie keer per dag » = trois fois par jour.' },
  { id: 'rd10', title: 'Weerbericht', style: 'blue',
    doc: 'Morgen veel wolken en regen, soms harde wind.<br>Het wordt maximaal 12 graden.<br>Neem een paraplu mee!',
    q: 'Wat moet u morgen meenemen?', qFr: 'Que devez-vous prendre avec vous demain ?',
    opts: ['Een zonnebril', 'Een paraplu', 'Zwemkleding'], corr: 1,
    expl: '« Paraplu » = parapluie.' },
];

// ── Écoute : messages courts (lus par la voix néerlandaise de l’appareil) ──
export const LISTENING = [
  { id: 'ls01', text: 'Goedemorgen, u spreekt met de tandartspraktijk. Uw afspraak van morgen om negen uur gaat niet door, want de tandarts is ziek. Wilt u maandag bellen voor een nieuwe afspraak?',
    textFr: 'Bonjour, ici le cabinet dentaire. Votre rendez-vous de demain à 9 h est annulé car le dentiste est malade. Pouvez-vous appeler lundi pour un nouveau rendez-vous ?',
    q: 'Wat moet de patiënt doen?', qFr: 'Que doit faire le patient ?', opts: ['Niets', 'Maandag bellen voor een nieuwe afspraak', 'Morgen naar de praktijk gaan'], corr: 1 },
  { id: 'ls02', text: 'Dames en heren, de intercity naar Utrecht heeft ongeveer tien minuten vertraging. De trein vertrekt van spoor vier.',
    textFr: 'Mesdames et messieurs, l’intercity pour Utrecht a environ dix minutes de retard. Le train part de la voie quatre.',
    q: 'Hoeveel vertraging heeft de trein?', qFr: 'Combien de retard a le train ?', opts: ['Tien minuten', 'Vier minuten', 'Geen vertraging'], corr: 0 },
  { id: 'ls03', text: 'Goedemiddag, met de apotheek. Uw medicijnen liggen klaar. Neemt u uw identiteitsbewijs en uw zorgpas mee?',
    textFr: 'Bonjour, ici la pharmacie. Vos médicaments sont prêts. Pouvez-vous apporter votre pièce d’identité et votre carte d’assurance ?',
    q: 'Wat moet u meenemen?', qFr: 'Que devez-vous apporter ?', opts: ['Contant geld', 'Uw identiteitsbewijs en zorgpas', 'Een tas'], corr: 1 },
  { id: 'ls04', text: 'Let op: bus twaalf rijdt vandaag een andere route. Er wordt gewerkt aan de weg in het centrum.',
    textFr: 'Attention : le bus douze suit un autre itinéraire aujourd’hui. Il y a des travaux sur la route dans le centre.',
    q: 'Waarom rijdt bus twaalf anders?', qFr: 'Pourquoi le bus douze suit-il un autre itinéraire ?', opts: ['Er is een ongeluk', 'Er wordt gewerkt aan de weg', 'Het weer is slecht'], corr: 1 },
  { id: 'ls05', text: 'Hallo Mark, met Jan. Ik heb koorts. Ik kan vandaag niet komen werken. Ik bel morgen weer.',
    textFr: 'Bonjour Mark, c’est Jan. J’ai de la fièvre. Je ne peux pas venir travailler aujourd’hui. Je rappelle demain.',
    q: 'Waarom belt Jan?', qFr: 'Pourquoi Jan appelle-t-il ?', opts: ['Hij meldt zich ziek', 'Hij wil vakantie', 'Hij komt te laat'], corr: 0 },
  { id: 'ls06', text: 'Beste ouders, aanstaande vrijdag hebben de leraren een studiedag. De kinderen hebben die dag geen school.',
    textFr: 'Chers parents, vendredi prochain, les enseignants ont une journée de formation. Les enfants n’ont pas école ce jour-là.',
    q: 'Moeten de kinderen vrijdag naar school?', qFr: 'Les enfants doivent-ils aller à l’école vendredi ?', opts: ['Ja, tot twaalf uur', 'Nee, ze zijn de hele dag vrij', 'Alleen groep acht'], corr: 1 },
  { id: 'ls07', text: 'Beste klanten, alleen vandaag: koopt u voor twintig euro groente, dan krijgt u een zak appels gratis.',
    textFr: 'Chers clients, aujourd’hui seulement : pour vingt euros de légumes achetés, vous recevez un sac de pommes gratuit.',
    q: 'Wat krijgt u gratis?', qFr: 'Que recevez-vous gratuitement ?', opts: ['Een zak appels', 'Bloemen', 'Korting op vlees'], corr: 0 },
  { id: 'ls08', text: 'Hoi Anna, met Sophie. Ga je vanavond mee naar de film? Bel me even terug of stuur een berichtje.',
    textFr: 'Salut Anna, c’est Sophie. Tu viens au cinéma ce soir ? Rappelle-moi ou envoie-moi un message.',
    q: 'Wat wil Sophie doen?', qFr: 'Que veut faire Sophie ?', opts: ['Samen koken', 'Naar de film gaan', 'Winkelen'], corr: 1 },
  { id: 'ls09', text: 'Er zijn sleutels gevonden bij de ingang. Het is een rode sleutelbos. U kunt hem ophalen bij de receptie.',
    textFr: 'Des clés ont été trouvées à l’entrée. C’est un trousseau rouge. Vous pouvez le récupérer à l’accueil.',
    q: 'Wat is er gevonden?', qFr: 'Qu’est-ce qui a été trouvé ?', opts: ['Een portemonnee', 'Een rode sleutelbos', 'Een telefoon'], corr: 1 },
  { id: 'ls10', text: 'Bericht voor de wijk Noord: deze week halen we het papier niet op woensdag op, maar op donderdag.',
    textFr: 'Message pour le quartier Nord : cette semaine, nous ramassons le papier jeudi au lieu de mercredi.',
    q: 'Wanneer wordt het papier deze week opgehaald?', qFr: 'Quand le papier sera-t-il ramassé cette semaine ?', opts: ['Woensdag', 'Donderdag', 'Vrijdag'], corr: 1 },
];

// Deuxième question par texte (à l’examen : 2 questions par texte). Même document, autre question.
const SECOND = {
  rd01: ['Hoeveel pakken melk betaalt u als u er 2 koopt?', 'Combien de briques de lait payez-vous si vous en prenez 2 ?', ['1 pak', '2 pakken', '3 pakken'], 0, '« 2 voor de prijs van 1 » = 2 pour le prix d’1.'],
  rd02: ['Wie moet toestemming geven voor een kat?', 'Qui doit donner l’autorisation pour un chat ?', ['De buren', 'De verhuurder', 'De gemeente'], 1, 'La « verhuurder » est le propriétaire.'],
  rd03: ['Kunt u op zaterdag naar de praktijk?', 'Pouvez-vous aller au cabinet le samedi ?', ['Ja, de hele dag', 'Nee, de praktijk is dan gesloten', 'Alleen ’s ochtends'], 1, '« Zaterdag en zondag gesloten » = fermé le samedi et le dimanche.'],
  rd04: ['Wanneer haalt u de container weer binnen?', 'Quand rentrez-vous la poubelle ?', ['Vóór 19.00 uur', 'De volgende ochtend', 'Na een week'], 0, '« Haal hem … vóór 19.00 uur weer binnen » = rentrez-la avant 19 h.'],
  rd05: ['Waar is de barbecue?', 'Où a lieu le barbecue ?', ['In het park', 'In de binnentuin', 'Op het strand'], 1, '« De binnentuin » = la cour intérieure.'],
  rd06: ['Hoe betaalt u deze rekening?', 'Comment payez-vous cette facture ?', ['Contant bij het kantoor', 'Het bedrag wordt automatisch afgeschreven', 'Met een brief'], 1, '« Automatisch afschrijven » = prélèvement automatique.'],
  rd07: ['Wat is verplicht voor deze baan?', 'Qu’est-ce qui est exigé pour ce poste ?', ['Veel ervaring', 'Goed Nederlands spreken', 'Een rijbewijs'], 1, '« Ervaring is fijn, maar niet nodig » : l’expérience n’est pas obligatoire ; le néerlandais, si.'],
  rd08: ['Wat mag u niet doen in het park?', 'Que ne pouvez-vous pas faire dans le parc ?', ['Wandelen', 'Fietsen op het gras', 'Op een bank zitten'], 1, '« Verboden te fietsen op het gras » = interdit de rouler à vélo sur la pelouse.'],
  rd09: ['Wanneer neemt u de tablet?', 'Quand prenez-vous le comprimé ?', ['Voor het slapen', 'Tijdens of na het eten', 'Voor het ontbijt, zonder water'], 1, '« Tijdens of na het eten » = pendant ou après le repas.'],
  rd10: ['Hoe warm wordt het morgen?', 'Quelle température fera-t-il demain ?', ['Maximaal 12 graden', 'Ongeveer 20 graden', 'Onder nul'], 0, '« Maximaal 12 graden » = 12 degrés au maximum.'],
};
READING.splice(0, READING.length, ...READING.flatMap((d) => {
  const [q, qFr, opts, corr, expl] = SECOND[d.id];
  return [d, { ...d, id: d.id + 'b', q, qFr, opts, corr, expl }];
}));
