// Lecture : textes supplémentaires, au format de l’examen (depuis mai 2023 : 9 textes, questions à 3 choix, 35 minutes).
// Types de textes : tableaux, instructions, courts récits, messages, annonces, formulaires.
// Chaque texte : { id, title, style, doc (HTML simple), qs: [[q, qFr, [3 options], bonne réponse (index), explication]] }

const T = (id, title, style, doc, qs) => ({ id, title, style, doc, qs });

export const READING_TEXTS = [
  T('rt01', 'Wegwijzer in de bibliotheek', 'plain',
    '<table class="w-full text-sm"><tr><td class="pr-3 font-bold">Begane grond</td><td>Kranten en tijdschriften · Koffiehoek</td></tr><tr><td class="pr-3 font-bold">1e verdieping</td><td>Boeken voor kinderen</td></tr><tr><td class="pr-3 font-bold">2e verdieping</td><td>Studieplekken · Computers</td></tr><tr><td class="pr-3 font-bold">3e verdieping</td><td>Taalhuis: Nederlands oefenen</td></tr></table>',
    [['Op welke verdieping kunt u rustig studeren?', 'À quel étage pouvez-vous étudier au calme ?', ['Begane grond', '1e verdieping', '2e verdieping'], 2, '« Studieplekken » = places pour étudier : 2e étage.'],
     ['Waar kunt u Nederlands oefenen?', 'Où pouvez-vous pratiquer le néerlandais ?', ['Op de 3e verdieping', 'In de koffiehoek', 'Bij de kinderboeken'], 0, '« Taalhuis » au 3e étage.']]),
  T('rt02', 'Pakket beschadigd?', 'grey',
    'Is uw pakket beschadigd?<br>1. Maak eerst een foto van het pakket.<br>2. Open het pakket niet.<br>3. Bel binnen 2 dagen onze klantenservice: 088 123 4567.',
    [['Wat moet u eerst doen?', 'Que devez-vous faire en premier ?', ['Het pakket openen', 'Een foto maken', 'De winkel bezoeken'], 1, '« Maak eerst een foto » = prenez d’abord une photo.'],
     ['Wanneer moet u bellen?', 'Quand devez-vous appeler ?', ['Binnen 2 dagen', 'Na een week', 'Vandaag voor 12 uur'], 0, '« Binnen 2 dagen » = dans les 2 jours.']]),
  T('rt03', 'Een regenachtige dag', 'plain',
    'Lina gaat naar de markt. Het regent hard. Ze koopt eerst een paraplu. Daarna koopt ze appels en brood. Om twaalf uur is ze weer thuis. Ze drinkt thee met haar buurvrouw.',
    [['Wat koopt Lina omdat het regent?', 'Qu’achète Lina parce qu’il pleut ?', ['Een jas', 'Een paraplu', 'Laarzen'], 1, '« Ze koopt eerst een paraplu. »'],
     ['Met wie drinkt Lina thee?', 'Avec qui Lina boit-elle du thé ?', ['Met haar zus', 'Met haar buurvrouw', 'Met haar man'], 1, '« buurvrouw » = voisine.']]),
  T('rt04', 'Sms van de school', 'blue',
    'Beste ouders, morgen gaan de kinderen naar de dierentuin. Geef uw kind een lunchpakket en een regenjas mee. We zijn om 15.00 uur terug bij school.',
    [['Waar gaan de kinderen morgen naartoe?', 'Où vont les enfants demain ?', ['Naar het zwembad', 'Naar de dierentuin', 'Naar het museum'], 1, '« dierentuin » = zoo.'],
     ['Wat moet uw kind meenemen?', 'Que doit emporter votre enfant ?', ['Geld en een boek', 'Een lunchpakket en een regenjas', 'Sportkleren'], 1, '« lunchpakket » = repas emporté ; « regenjas » = imperméable.']]),
  T('rt05', 'Openingstijden zwembad De Vaart', 'green',
    '<table class="w-full text-sm"><tr><td class="pr-3 font-bold">Maandag</td><td>gesloten</td></tr><tr><td class="pr-3 font-bold">Di – vr</td><td>07.00 – 21.00</td></tr><tr><td class="pr-3 font-bold">Za – zo</td><td>09.00 – 17.00</td></tr></table>Vrouwenzwemmen: woensdag 19.00 – 20.00',
    [['Wanneer is het zwembad dicht?', 'Quand la piscine est-elle fermée ?', ['Op maandag', 'Op zondag', 'Op woensdag'], 0, '« Maandag: gesloten » = fermé le lundi.'],
     ['Hoe laat is het vrouwenzwemmen?', 'À quelle heure est la séance réservée aux femmes ?', ['Zaterdag om 9 uur', 'Woensdag van 19.00 tot 20.00 uur', 'Vrijdag om 21.00 uur'], 1, 'Mercredi de 19 h à 20 h.']]),
  T('rt06', 'Afspraak bij de tandarts', 'grey',
    'Herinnering: u heeft een afspraak bij tandarts Visser op donderdag 12 maart om 10.15 uur. Kunt u niet komen? Bel dan uiterlijk 24 uur van tevoren. Anders betaalt u € 25.',
    [['Hoe laat is de afspraak?', 'À quelle heure est le rendez-vous ?', ['Om 10.15 uur', 'Om 12.00 uur', 'Om 24.00 uur'], 0, '« om 10.15 uur » = à 10 h 15.'],
     ['Wat gebeurt er als u niet op tijd afzegt?', 'Que se passe-t-il si vous n’annulez pas à temps ?', ['Niets', 'U betaalt € 25', 'U krijgt een nieuwe afspraak'], 1, '« Anders betaalt u € 25 » = sinon vous payez 25 €.']]),
  T('rt07', 'Te huur', 'amber',
    'TE HUUR: appartement in het centrum. 2 slaapkamers, balkon, 3e verdieping, geen lift. Huur: € 950 per maand, inclusief water. Geen huisdieren. Bel 06-12345678.',
    [['Hoeveel slaapkamers heeft het appartement?', 'Combien de chambres a l’appartement ?', ['1', '2', '3'], 1, '« 2 slaapkamers ».'],
     ['Wat is niet toegestaan?', 'Qu’est-ce qui n’est pas permis ?', ['Huisdieren', 'Een fiets', 'Bezoek'], 0, '« Geen huisdieren » = pas d’animaux.']]),
  T('rt08', 'Bericht van Ahmed', 'blue',
    'Hoi Sara! Ik ben ziek, dus ik kan vanavond niet naar de cursus. Wil jij het huiswerk voor mij opschrijven? Dank je! Groetjes, Ahmed',
    [['Waarom gaat Ahmed niet naar de cursus?', 'Pourquoi Ahmed ne va-t-il pas au cours ?', ['Hij moet werken', 'Hij is ziek', 'Hij is op vakantie'], 1, '« Ik ben ziek ».'],
     ['Wat vraagt Ahmed aan Sara?', 'Que demande Ahmed à Sara ?', ['Het huiswerk opschrijven', 'Hem ophalen', 'Medicijnen kopen'], 0, '« het huiswerk voor mij opschrijven » = noter les devoirs pour lui.']]),
  T('rt09', 'Menu van café De Hoek', 'orange',
    '<table class="w-full text-sm"><tr><td class="pr-3">Koffie / thee</td><td>€ 2,80</td></tr><tr><td class="pr-3">Tosti kaas</td><td>€ 4,50</td></tr><tr><td class="pr-3">Soep van de dag</td><td>€ 5,75</td></tr><tr><td class="pr-3">Appeltaart</td><td>€ 3,90</td></tr></table>Keuken open tot 16.00 uur.',
    [['Hoeveel kost de soep?', 'Combien coûte la soupe ?', ['€ 2,80', '€ 4,50', '€ 5,75'], 2, '« Soep van de dag: € 5,75 ».'],
     ['Tot hoe laat kunt u eten bestellen?', 'Jusqu’à quelle heure peut-on commander à manger ?', ['Tot 12.00 uur', 'Tot 16.00 uur', 'Tot 22.00 uur'], 1, '« Keuken open tot 16.00 uur ».']]),
  T('rt10', 'Brief van de gemeente', 'plain',
    'Beste mevrouw Haddad,<br>Uw nieuwe identiteitskaart is klaar. U kunt de kaart ophalen bij het gemeentehuis, balie 3. Neem uw oude kaart mee. Maak eerst een afspraak via onze website.',
    [['Wat is klaar?', 'Qu’est-ce qui est prêt ?', ['Een paspoort', 'Een identiteitskaart', 'Een rijbewijs'], 1, '« Uw nieuwe identiteitskaart is klaar ».'],
     ['Wat moet mevrouw Haddad eerst doen?', 'Que doit faire Mme Haddad d’abord ?', ['Een afspraak maken', 'Geld overmaken', 'Een foto sturen'], 0, '« Maak eerst een afspraak ».']]),
  T('rt11', 'Bijsluiter hoestdrank', 'grey',
    'Hoestdrank. Volwassenen: 3 keer per dag 10 ml. Kinderen van 6 tot 12 jaar: 3 keer per dag 5 ml. Niet voor kinderen onder de 6 jaar. Goed schudden voor gebruik.',
    [['Hoeveel neemt een volwassene per keer?', 'Combien un adulte prend-il à chaque fois ?', ['5 ml', '10 ml', '15 ml'], 1, 'Adultes : 10 ml.'],
     ['Wat moet u doen voordat u de hoestdrank neemt?', 'Que faut-il faire avant de prendre le sirop ?', ['De fles goed schudden', 'Iets eten', 'Water toevoegen'], 0, '« Goed schudden voor gebruik » = bien agiter.']]),
  T('rt12', 'Vertrektijden bus 5', 'blue',
    '<table class="w-full text-sm"><tr><th class="text-left pr-3">Station</th><th class="text-left pr-3">Ziekenhuis</th><th class="text-left">Centrum</th></tr><tr><td>08.10</td><td>08.22</td><td>08.30</td></tr><tr><td>08.40</td><td>08.52</td><td>09.00</td></tr><tr><td>09.10</td><td>09.22</td><td>09.30</td></tr></table>',
    [['U neemt om 08.40 uur de bus bij het station. Hoe laat bent u bij het ziekenhuis?', 'Vous prenez le bus de 8 h 40 à la gare. À quelle heure êtes-vous à l’hôpital ?', ['08.22 uur', '08.52 uur', '09.22 uur'], 1, 'Même ligne du tableau : 08.52.'],
     ['Hoe vaak rijdt de bus?', 'À quelle fréquence passe le bus ?', ['Elk kwartier', 'Elk half uur', 'Elk uur'], 1, '08.10, 08.40, 09.10 : toutes les 30 minutes.']]),
  T('rt13', 'Een nieuwe baan', 'plain',
    'Yusuf werkt sinds maandag in een bakkerij. Hij begint elke dag om vijf uur. Dat is vroeg, maar hij vindt het werk leuk. Om twaalf uur is hij klaar. ’s Middags gaat hij naar zijn taalles.',
    [['Waar werkt Yusuf?', 'Où travaille Yusuf ?', ['In een supermarkt', 'In een bakkerij', 'In een restaurant'], 1, '« in een bakkerij » = dans une boulangerie.'],
     ['Wat doet Yusuf ’s middags?', 'Que fait Yusuf l’après-midi ?', ['Hij slaapt', 'Hij gaat naar taalles', 'Hij werkt'], 1, '« ’s Middags gaat hij naar zijn taalles ».']]),
  T('rt14', 'Folder: gratis griepprik', 'green',
    'Bent u 60 jaar of ouder? Dan krijgt u een gratis griepprik. U krijgt een uitnodiging van uw huisarts. Neem de uitnodiging en uw identiteitsbewijs mee naar de prikdag.',
    [['Wie krijgt een gratis griepprik?', 'Qui reçoit un vaccin gratuit contre la grippe ?', ['Iedereen', 'Mensen van 60 jaar of ouder', 'Alleen kinderen'], 1, '« 60 jaar of ouder ».'],
     ['Wat neemt u mee?', 'Qu’apportez-vous ?', ['De uitnodiging en uw identiteitsbewijs', 'Geld', 'Uw zorgpas en een foto'], 0, '« Neem de uitnodiging en uw identiteitsbewijs mee ».']]),
  T('rt15', 'Bord bij de ingang', 'red',
    'Let op! De hoofdingang is gesloten wegens werkzaamheden. Gebruik de ingang aan de achterkant van het gebouw. Rolstoelen: bel aan bij de zijdeur.',
    [['Waarom is de hoofdingang dicht?', 'Pourquoi l’entrée principale est-elle fermée ?', ['Er zijn werkzaamheden', 'Het is zondag', 'Er is brand'], 0, '« wegens werkzaamheden » = à cause de travaux.'],
     ['Welke ingang gebruikt u met een rolstoel?', 'Quelle entrée utilisez-vous en fauteuil roulant ?', ['De hoofdingang', 'De achteringang', 'De zijdeur'], 2, '« Rolstoelen: bel aan bij de zijdeur ».']]),
  T('rt16', 'E-mail van de verhuurder', 'plain',
    'Beste bewoners,<br>Op dinsdag 4 juni is er geen warm water tussen 9.00 en 13.00 uur. De cv-ketel krijgt dan onderhoud. Excuses voor het ongemak.<br>Woonstichting Oost',
    [['Wat is er op dinsdag 4 juni niet?', 'Qu’est-ce qui manque le mardi 4 juin ?', ['Stroom', 'Warm water', 'Internet'], 1, '« geen warm water ».'],
     ['Waarom?', 'Pourquoi ?', ['De cv-ketel krijgt onderhoud', 'Er is een storing', 'De rekening is niet betaald'], 0, '« De cv-ketel krijgt dan onderhoud » = entretien de la chaudière.']]),
  T('rt17', 'Aanmeldformulier sportschool', 'grey',
    'Naam: ……… Geboortedatum: ……… Adres: ………<br>Abonnement: ☐ 1 keer per week (€ 20 per maand) ☐ onbeperkt (€ 35 per maand)<br>Eerste les gratis!',
    [['Hoeveel kost onbeperkt sporten?', 'Combien coûte l’abonnement illimité ?', ['€ 20 per maand', '€ 35 per maand', 'Gratis'], 1, '« onbeperkt (€ 35 per maand) ».'],
     ['Wat is gratis?', 'Qu’est-ce qui est gratuit ?', ['De eerste les', 'De eerste maand', 'Het abonnement'], 0, '« Eerste les gratis! »']]),
  T('rt18', 'Op de markt', 'amber',
    'Elke zaterdag gaat Maria met haar dochter naar de markt. Ze kopen groente, fruit en vis. De vis is duur, maar heel vers. Daarna eten ze samen een ijsje.',
    [['Wanneer gaat Maria naar de markt?', 'Quand Maria va-t-elle au marché ?', ['Elke zondag', 'Elke zaterdag', 'Elke dag'], 1, '« Elke zaterdag ».'],
     ['Wat zegt Maria over de vis?', 'Que dit Maria du poisson ?', ['Hij is goedkoop', 'Hij is duur maar vers', 'Hij is niet lekker'], 1, '« duur, maar heel vers ».']]),
  T('rt19', 'Afvalwijzer: grofvuil', 'green',
    'Grofvuil ophalen? Maak een afspraak via de app of bel 14 020. Zet het grofvuil op de afgesproken dag vóór 7.30 uur buiten. Maximaal 2 m³ per keer.',
    [['Hoe maakt u een afspraak?', 'Comment prenez-vous rendez-vous ?', ['Via de app of telefonisch', 'Bij de supermarkt', 'Per brief'], 0, '« via de app of bel 14 020 ».'],
     ['Wanneer zet u het grofvuil buiten?', 'Quand sortez-vous les encombrants ?', ['De avond ervoor', 'Op de afgesproken dag vóór 7.30 uur', 'Wanneer u wilt'], 1, '« vóór 7.30 uur » le jour convenu.']]),
  T('rt20', 'Uitnodiging verjaardag', 'orange',
    'Hoera! Noor wordt 6 jaar! Kom je op zaterdag 9 mei naar haar feestje? Van 14.00 tot 17.00 uur, Lindelaan 12. Laat je het weten vóór 5 mei? Groetjes, mama van Noor',
    [['Hoe oud wordt Noor?', 'Quel âge va avoir Noor ?', ['5 jaar', '6 jaar', '9 jaar'], 1, '« Noor wordt 6 jaar ».'],
     ['Wat moet je doen vóór 5 mei?', 'Que faut-il faire avant le 5 mai ?', ['Een cadeau kopen', 'Laten weten of je komt', 'Taart bakken'], 1, '« Laat je het weten » = préviens si tu viens.']]),
  T('rt21', 'Huisregels flat', 'plain',
    'Huisregels: fietsen niet in de hal zetten. Afval alleen in de container beneden. Geen harde muziek na 22.00 uur. Huisdieren altijd aan de lijn in de gang.',
    [['Waar mag u uw fiets niet zetten?', 'Où ne pouvez-vous pas mettre votre vélo ?', ['In de fietsenstalling', 'In de hal', 'Buiten'], 1, '« niet in de hal ».'],
     ['Wat mag niet na 22.00 uur?', 'Qu’est-ce qui est interdit après 22 h ?', ['Koken', 'Harde muziek', 'Douchen'], 1, '« Geen harde muziek na 22.00 uur ».']]),
  T('rt22', 'De eerste schooldag', 'blue',
    'Vandaag is Adam voor het eerst naar school. Hij is vier jaar. Zijn juf heet Petra. Adam speelt met blokken en tekent een huis. Om drie uur haalt papa hem op.',
    [['Hoe heet de juf van Adam?', 'Comment s’appelle la maîtresse d’Adam ?', ['Petra', 'Noor', 'Maria'], 0, '« Zijn juf heet Petra ».'],
     ['Wie haalt Adam op?', 'Qui vient chercher Adam ?', ['Mama', 'Papa', 'Opa'], 1, '« haalt papa hem op ».']]),
  T('rt23', 'Energierekening', 'plain',
    'Jaarafrekening 2025. U betaalde elke maand € 110. Uw echte verbruik was lager. U krijgt € 240 terug. Dit bedrag staat binnen 10 werkdagen op uw rekening.',
    [['Krijgt u geld terug of moet u betalen?', 'Recevez-vous de l’argent ou devez-vous payer ?', ['U krijgt geld terug', 'U moet € 240 betalen', 'U moet € 110 extra betalen'], 0, '« U krijgt € 240 terug » = on vous rembourse.'],
     ['Wanneer staat het geld op uw rekening?', 'Quand l’argent sera-t-il sur votre compte ?', ['Vandaag', 'Binnen 10 werkdagen', 'Volgend jaar'], 1, '« binnen 10 werkdagen ».']]),
  T('rt24', 'Vacature schoonmaker', 'orange',
    'Gezocht: schoonmaker (m/v) voor kantoren. Werktijden: maandag t/m vrijdag van 18.00 tot 21.00 uur. Geen ervaring nodig. Salaris: € 14 per uur. Mail naar werk@schoonbv.nl.',
    [['Wanneer werkt de schoonmaker?', 'Quand travaille l’agent d’entretien ?', ['In het weekend', '’s Avonds op werkdagen', '’s Ochtends vroeg'], 1, 'Du lundi au vendredi de 18 h à 21 h.'],
     ['Hoe solliciteert u?', 'Comment postulez-vous ?', ['Door te bellen', 'Door een e-mail te sturen', 'Door langs te komen'], 1, '« Mail naar … » = envoyez un e-mail.']]),
  T('rt25', 'Bericht in de trein', 'red',
    'Let op: deze trein stopt niet in Gouda. Reizigers naar Gouda stappen over in Utrecht Centraal op spoor 7.',
    [['Stopt deze trein in Gouda?', 'Ce train s’arrête-t-il à Gouda ?', ['Ja', 'Nee', 'Alleen in het weekend'], 1, '« stopt niet in Gouda ».'],
     ['Waar stappen reizigers naar Gouda over?', 'Où changent les voyageurs pour Gouda ?', ['In Utrecht Centraal', 'In Gouda', 'In Amsterdam'], 0, '« stappen over in Utrecht Centraal » (voie 7).']]),
  T('rt26', 'Kaartje van de buren', 'amber',
    'Beste buren, wij krijgen zaterdag een grote verhuiswagen. Die staat van 9.00 tot 15.00 uur voor de deur. Sorry voor de overlast! Groeten, Tom en Lisa (nr. 14)',
    [['Wat gebeurt er zaterdag?', 'Que se passe-t-il samedi ?', ['De buren gaan verhuizen', 'Er is een feest', 'De straat wordt schoongemaakt'], 0, '« verhuiswagen » = camion de déménagement.'],
     ['Hoe lang staat de wagen voor de deur?', 'Combien de temps le camion reste-t-il devant la porte ?', ['Van 9.00 tot 15.00 uur', 'De hele dag', 'Twee dagen'], 0, 'De 9 h à 15 h.']]),
  T('rt27', 'Bij de huisartsenpost', 'grey',
    'Huisartsenpost: alleen voor spoed. Avond, nacht en weekend. Bel altijd eerst: 088 123 0000. Kom niet zonder afspraak. Bij levensgevaar: bel 112.',
    [['Wat doet u eerst?', 'Que faites-vous d’abord ?', ['Langskomen', 'Bellen', 'Een e-mail sturen'], 1, '« Bel altijd eerst ».'],
     ['Wanneer belt u 112?', 'Quand appelez-vous le 112 ?', ['Bij levensgevaar', 'Voor een afspraak', 'Voor een recept'], 0, '« Bij levensgevaar: bel 112 ».']]),
  T('rt28', 'Een weekend weg', 'plain',
    'Sanne en haar man gaan een weekend naar Zeeland. Ze gaan met de trein en daarna met de bus. Ze slapen in een klein hotel bij het strand. Op zondag fietsen ze langs de zee.',
    [['Hoe reizen Sanne en haar man?', 'Comment voyagent Sanne et son mari ?', ['Met de auto', 'Met de trein en de bus', 'Met de fiets'], 1, '« met de trein en daarna met de bus ».'],
     ['Wat doen ze op zondag?', 'Que font-ils dimanche ?', ['Ze zwemmen', 'Ze fietsen langs de zee', 'Ze gaan winkelen'], 1, '« fietsen ze langs de zee ».']]),
  T('rt29', 'Aanbieding drogist', 'blue',
    'Deze week: tandpasta 1 + 1 gratis. Shampoo: 25% korting. Alleen met de klantenkaart. Geldig t/m zondag.',
    [['Wat krijgt u bij tandpasta?', 'Que recevez-vous avec le dentifrice ?', ['25% korting', 'De tweede gratis', 'Een klantenkaart'], 1, '« 1 + 1 gratis » = le deuxième est offert.'],
     ['Wat heeft u nodig voor de korting?', 'De quoi avez-vous besoin pour la réduction ?', ['Een klantenkaart', 'Een bon uit de krant', 'Niets'], 0, '« Alleen met de klantenkaart ».']]),
  T('rt30', 'Oudergesprek', 'green',
    'Beste ouders, de tienminutengesprekken zijn op dinsdag 18 en woensdag 19 november. Kies een tijd via de schoolapp. Kunt u niet? Stuur dan een bericht naar de leerkracht.',
    [['Hoe kiest u een tijd?', 'Comment choisissez-vous un horaire ?', ['Via de schoolapp', 'Door te bellen', 'Bij de directeur'], 0, '« Kies een tijd via de schoolapp ».'],
     ['Wat doet u als u niet kunt?', 'Que faites-vous si vous ne pouvez pas venir ?', ['Niets', 'Een bericht sturen naar de leerkracht', 'Een andere school zoeken'], 1, '« Stuur dan een bericht naar de leerkracht ».']]),
];
