// Manuel « Connaissance de la société néerlandaise » en français.
// Organisé selon les 7 thèmes officiels du KNS + la vie quotidienne.
// Chaque page : titre, texte, vocabulaire clé (nl → fr), à retenir, mini-quiz.
// Rédigé d’après des sources publiques (listées par chapitre). Dernière vérification : septembre 2026.

const P = (id, title, txt, vocab, tip, q, opts, corr = 0) => ({ id, title, txt, vocab, tip, q, opts, corr });
const S = (label, url) => ({ label, url });

export const MANUEL = [
  { id: 'wonen', cat: 'wonen', t: 'Géographie & logement', nl: 'Aardrijkskunde en wonen', icon: '🏠',
    sources: [S('Rijksoverheid.nl — Wonen', 'https://www.rijksoverheid.nl/onderwerpen/huurwoning-zoeken'), S('Government.nl', 'https://www.government.nl'), S('Rijkswaterstaat', 'https://www.rijkswaterstaat.nl')],
    pages: [
      P('m6p3', 'Le pays en quelques chiffres',
        'Les Pays-Bas comptent environ 18 millions d’habitants et 12 provinces. C’est l’un des pays les plus densément peuplés d’Europe. La capitale est Amsterdam, mais le gouvernement et le parlement siègent à La Haye (Den Haag). À l’ouest, la « Randstad » réunit les quatre grandes villes : Amsterdam, Rotterdam, La Haye et Utrecht. Les pays voisins sont la Belgique au sud et l’Allemagne à l’est ; au nord et à l’ouest, il y a la mer du Nord. Le Rhin et la Meuse traversent le pays jusqu’au port de Rotterdam, l’un des plus grands du monde.',
        [{ d: 'de hoofdstad', f: 'la capitale' }, { d: 'de provincie', f: 'la province' }, { d: 'de Randstad', f: 'la région des 4 grandes villes' }, { d: 'de Noordzee', f: 'la mer du Nord' }],
        'Capitale : Amsterdam. Gouvernement : La Haye. 12 provinces.',
        'Où siègent le gouvernement et le parlement ?', ['À La Haye', 'À Amsterdam', 'À Rotterdam']),
      P('m-royaume', 'Le Royaume des Pays-Bas',
        'Le Royaume des Pays-Bas (Koninkrijk der Nederlanden) est formé de quatre pays : les Pays-Bas, Aruba, Curaçao et Saint-Martin. Ces trois îles se trouvent dans la mer des Caraïbes. Trois autres îles, Bonaire, Saint-Eustache et Saba, sont des communes spéciales des Pays-Bas. Sur les îles, on parle aussi le papiamento ou l’anglais. Le roi est chef d’État de tout le Royaume.',
        [{ d: 'het Koninkrijk', f: 'le Royaume' }, { d: 'het eiland', f: 'l’île' }, { d: 'de Caraïben', f: 'les Caraïbes' }, { d: 'het land', f: 'le pays' }],
        'Royaume = Pays-Bas + Aruba + Curaçao + Saint-Martin.',
        'Combien de pays forment le Royaume des Pays-Bas ?', ['Quatre', 'Un seul', 'Douze']),
      P('m6p1', 'L’eau, les digues et les polders',
        'Environ un quart du pays se trouve sous le niveau de la mer. Pour se protéger, les Néerlandais ont construit des digues (dijken) et, après l’inondation de 1953, les Deltawerken, un grand ensemble de barrages. Ils ont aussi gagné des terres sur l’eau : les polders. Autrefois, des moulins pompaient l’eau. Aujourd’hui, des autorités régionales élues, les « waterschappen », gèrent les digues et le niveau de l’eau. L’eau du robinet, elle, vient d’une compagnie des eaux et peut se boire sans problème.',
        [{ d: 'de dijk', f: 'la digue' }, { d: 'de polder', f: 'la terre gagnée sur l’eau' }, { d: 'de molen', f: 'le moulin' }, { d: 'het waterschap', f: 'l’autorité de gestion de l’eau' }],
        'Polder = terre asséchée, souvent sous le niveau de la mer.',
        'Qu’est-ce qu’un polder ?', ['Une terre gagnée sur l’eau', 'Une montagne', 'Une forêt']),
      P('m-woning', 'Trouver un logement',
        'Il y a trois grandes possibilités : louer un logement social à une « woningcorporatie », louer à un propriétaire privé, ou acheter. Les logements sociaux sont moins chers, mais il faut s’inscrire sur une liste d’attente, parfois pendant des années dans les grandes villes. Méfiez-vous des annonces qui demandent de l’argent avant la visite : c’est souvent une arnaque. Avant de signer, lisez bien le contrat. Avec un petit revenu, vous pouvez demander une allocation logement (huurtoeslag).',
        [{ d: 'de huurwoning', f: 'le logement en location' }, { d: 'de woningcorporatie', f: 'le bailleur social' }, { d: 'de wachtlijst', f: 'la liste d’attente' }, { d: 'de borg', f: 'la caution' }],
        'Logement social = inscription + attente. Inscrivez-vous tôt.',
        'Comment obtient-on un logement social ?', ['On s’inscrit et on attend son tour', 'La commune le donne tout de suite', 'On le tire au sort au marché']),
      P('m3p1', 'Locataire et propriétaire',
        'Le contrat de location (huurcontract) lie le locataire (huurder) et le propriétaire (verhuurder). Pour les gros travaux, comme abattre un mur ou changer la cuisine, il faut l’accord écrit du propriétaire. Les petits changements, comme peindre à l’intérieur ou fixer une étagère, sont en général permis, mais il faut parfois tout remettre en état en partant. Le gros entretien (toit, chauffage) est à la charge du propriétaire. Si vous ne pouvez pas payer le loyer à temps, prévenez-le tout de suite.',
        [{ d: 'de huurder', f: 'le locataire' }, { d: 'de verhuurder', f: 'le propriétaire bailleur' }, { d: 'de huur', f: 'le loyer' }, { d: 'het onderhoud', f: 'l’entretien' }],
        'Avant de faire des travaux, demandez l’accord du verhuurder par écrit.',
        'Vous voulez changer la cuisine de votre logement loué. Que faites-vous ?', ['Je demande l’accord écrit du propriétaire', 'Je demande au voisin', 'Je le fais sans rien dire']),
      P('m3p2', 'Le tri des déchets et la sécurité',
        'Le tri est pris au sérieux. Les déchets de cuisine et de jardin vont dans la poubelle GFT (groente, fruit, tuin). Plastique, emballages métalliques et briques de boisson vont dans le PMD, selon les règles de votre commune. Le papier et le verre ont chacun leur conteneur. Les encombrants (vieux meubles) vont à la déchetterie (milieustraat) ou sont enlevés sur rendez-vous. Dans chaque logement, un détecteur de fumée est obligatoire à chaque étage depuis 2022.',
        [{ d: 'de gft-bak', f: 'la poubelle déchets organiques' }, { d: 'de glasbak', f: 'le conteneur à verre' }, { d: 'het grofvuil', f: 'les encombrants' }, { d: 'de rookmelder', f: 'le détecteur de fumée' }],
        'Chaque commune a ses règles : consultez son calendrier des déchets (afvalkalender).',
        'Où va un vieux canapé ?', ['À la milieustraat, ou enlevé comme encombrant', 'Dans la poubelle à papier', 'Sur le trottoir']),
    ] },

  { id: 'geschiedenis', cat: 'geschiedenis', t: 'Histoire', nl: 'Geschiedenis', icon: '📜',
    sources: [S('Canon van Nederland', 'https://www.canonvannederland.nl'), S('Rijksoverheid.nl — Slavernijverleden', 'https://www.rijksoverheid.nl/onderwerpen/slavernijverleden'), S('Nationaal Comité 4 en 5 mei', 'https://www.4en5mei.nl')],
    pages: [
      P('m-gouden', 'Guillaume d’Orange et le Siècle d’or',
        'Au XVIe siècle, les Pays-Bas appartenaient au roi d’Espagne. Guillaume d’Orange (Willem van Oranje) a mené la révolte contre l’Espagne : on l’appelle le « Père de la Patrie ». La famille royale actuelle descend de lui, et l’hymne national, le Wilhelmus, parle de lui. Au XVIIe siècle, le « Siècle d’or », le pays devient très riche grâce au commerce, avec la VOC, fondée en 1602. C’est aussi l’époque de peintres comme Rembrandt.',
        [{ d: 'de opstand', f: 'la révolte' }, { d: 'de Gouden Eeuw', f: 'le Siècle d’or' }, { d: 'de VOC', f: 'la Compagnie des Indes orientales' }, { d: 'het Wilhelmus', f: 'l’hymne national' }],
        'Guillaume d’Orange = révolte contre l’Espagne, « Père de la Patrie ».',
        'Comment appelle-t-on le XVIIe siècle aux Pays-Bas ?', ['Le Siècle d’or', 'Le siècle de fer', 'La Renaissance']),
      P('m-slavernij', 'Colonies et esclavage',
        'Le Siècle d’or a une face sombre. Les Pays-Bas ont eu des colonies, en Asie (l’actuelle Indonésie) et en Amérique (Suriname, îles des Caraïbes). Des commerçants néerlandais ont participé à la traite des esclaves. L’esclavage a été aboli le 1er juillet 1863, mais beaucoup ont dû travailler encore dix ans. Chaque 1er juillet, on commémore cette histoire (Keti Koti). En 2022, le Premier ministre, puis en 2023 le roi, ont présenté des excuses.',
        [{ d: 'de kolonie', f: 'la colonie' }, { d: 'de slavernij', f: 'l’esclavage' }, { d: 'afschaffen', f: 'abolir' }, { d: 'Keti Koti', f: 'commémoration du 1er juillet' }],
        'Abolition : 1863. Commémoration : 1er juillet (Keti Koti).',
        'En quelle année l’esclavage a-t-il été aboli dans les colonies néerlandaises ?', ['1863', '1945', '1975']),
      P('m6p2', 'La Seconde Guerre mondiale',
        'De 1940 à 1945, les Pays-Bas ont été occupés par l’Allemagne nazie. Plus de 100 000 Juifs néerlandais ont été déportés et assassinés. Anne Frank, une jeune fille juive, s’est cachée avec sa famille dans une annexe à Amsterdam, où elle a écrit son célèbre journal. Elle est morte en 1945 dans un camp. Le 4 mai à 20 h, tout le pays observe deux minutes de silence pour les victimes de la guerre (Dodenherdenking). Le 5 mai, on fête la Libération (Bevrijdingsdag).',
        [{ d: 'de Tweede Wereldoorlog', f: 'la Seconde Guerre mondiale' }, { d: 'de bezetting', f: 'l’occupation' }, { d: 'de Dodenherdenking', f: 'la commémoration du 4 mai' }, { d: 'Bevrijdingsdag', f: 'la fête de la Libération (5 mai)' }],
        '4 mai = silence et souvenir ; 5 mai = fête de la liberté.',
        'Que se passe-t-il le 4 mai à 20 h ?', ['Deux minutes de silence', 'Un feu d’artifice', 'La fête du Roi']),
      P('m-na1945', 'Après 1945 : un pays qui change',
        'En 1953, une tempête a provoqué une inondation terrible en Zélande : plus de 1 800 morts. Le pays a ensuite construit les Deltawerken. L’Indonésie est devenue indépendante (reconnue en 1949), puis le Suriname en 1975 ; beaucoup de leurs habitants sont venus aux Pays-Bas. Dans les années 1960 et 1970, des travailleurs sont venus d’Italie, d’Espagne, de Turquie et du Maroc pour travailler dans les usines. Les Pays-Bas font partie des fondateurs de l’Union européenne ; depuis 2002, on paie en euros.',
        [{ d: 'de watersnoodramp', f: 'l’inondation de 1953' }, { d: 'onafhankelijk', f: 'indépendant' }, { d: 'de gastarbeider', f: 'le travailleur immigré' }, { d: 'de euro', f: 'l’euro' }],
        'Suriname indépendant : 1975. Euro : 2002.',
        'Pourquoi beaucoup de travailleurs sont-ils venus dans les années 60 ?', ['Il manquait de main-d’œuvre dans les usines', 'Pour les vacances', 'Pour étudier']),
      P('m-feesten', 'Les fêtes et les jours de souvenir',
        'Koningsdag, le 27 avril, est l’anniversaire du roi : on s’habille en orange et il y a des marchés dans la rue. Le 4 mai, on commémore les morts de la guerre ; le 5 mai, on fête la Libération. Le 1er juillet, Keti Koti rappelle l’abolition de l’esclavage. Le 5 décembre, les enfants fêtent Sinterklaas avec des cadeaux. Noël, Pâques et le Nouvel An sont aussi des jours fériés. Les femmes ont obtenu le droit de vote en 1919.',
        [{ d: 'Koningsdag', f: 'la fête du Roi (27 avril)' }, { d: 'de feestdag', f: 'le jour férié' }, { d: 'Sinterklaas', f: 'la Saint-Nicolas (5 décembre)' }, { d: 'oranje', f: 'orange (couleur nationale)' }],
        '27 avril : fête du Roi. 5 décembre : Sinterklaas.',
        'Quand a lieu la fête du Roi ?', ['Le 27 avril', 'Le 5 mai', 'Le 5 décembre']),
    ] },

  { id: 'staat', cat: 'staat', t: 'État, droits & démarches', nl: 'Staatsinrichting en rechtsstaat', icon: '🏛️',
    sources: [S('Rijksoverheid.nl', 'https://www.rijksoverheid.nl'), S('Tweede Kamer', 'https://www.tweedekamer.nl'), S('IND', 'https://ind.nl'), S('Juridisch Loket', 'https://www.juridischloket.nl')],
    pages: [
      P('m5p1', 'Le roi et le gouvernement',
        'Les Pays-Bas sont une monarchie constitutionnelle. Le roi Willem-Alexander est le chef de l’État (staatshoofd), mais il ne gouverne pas : ce sont les ministres qui sont responsables. Le gouvernement est dirigé par le Premier ministre (minister-president). Aucun parti n’a la majorité seul : le gouvernement est toujours une coalition de plusieurs partis.',
        [{ d: 'het staatshoofd', f: 'le chef de l’État' }, { d: 'de koning', f: 'le roi' }, { d: 'de minister-president', f: 'le Premier ministre' }, { d: 'de regering', f: 'le gouvernement' }],
        'Retenez : le roi règne, les ministres gouvernent.',
        'Quel est le rôle du roi ?', ['Chef de l’État, sans gouverner lui-même', 'Il vote seul toutes les lois', 'Il dirige la police']),
      P('m5p2', 'Le parlement et les élections',
        'Le parlement siège à La Haye. La Tweede Kamer compte 150 députés élus tous les 4 ans ; elle vote les lois et peut les modifier. La Eerste Kamer (Sénat) les contrôle ensuite et vote pour ou contre. On vote aussi pour la province, le conseil municipal (gemeenteraad), les waterschappen et le Parlement européen. Le maire (burgemeester) n’est pas élu : il est nommé par le gouvernement. Aux élections communales, les étrangers en séjour légal depuis 5 ans peuvent voter.',
        [{ d: 'de Tweede Kamer', f: 'la Chambre des représentants (150 sièges)' }, { d: 'de Eerste Kamer', f: 'le Sénat' }, { d: 'de verkiezingen', f: 'les élections' }, { d: 'stemmen', f: 'voter' }],
        'Tweede Kamer : 150 sièges, élue pour 4 ans.',
        'Combien de sièges compte la Tweede Kamer ?', ['150', '100', '200']),
      P('m5p3', 'La Constitution et l’égalité',
        'La Constitution s’appelle la « Grondwet ». Son article 1 dit que tout le monde est traité de la même façon dans les mêmes situations et interdit la discrimination (religion, convictions, origine, sexe, handicap, orientation sexuelle…). La Constitution garantit aussi la liberté d’expression et de religion. Églises et État sont séparés : les règles religieuses ne passent jamais avant la loi. Hommes et femmes ont les mêmes droits ; depuis 2001, deux personnes du même sexe peuvent se marier.',
        [{ d: 'de Grondwet', f: 'la Constitution' }, { d: 'de gelijkheid', f: 'l’égalité' }, { d: 'de discriminatie', f: 'la discrimination' }, { d: 'de vrijheid van meningsuiting', f: 'la liberté d’expression' }],
        'Article 1 = égalité et interdiction de la discrimination.',
        'Que garantit l’article 1 de la Constitution ?', ['L’égalité et l’interdiction de la discrimination', 'L’obligation de voter', 'Une religion d’État']),
      P('m-recht', 'La justice et vos droits',
        'Aux Pays-Bas, des juges indépendants jugent les affaires ; le gouvernement ne peut pas leur donner d’ordres. La violence est interdite, y compris à la maison : en cas de violence domestique, appelez Veilig Thuis (0800-2000, gratuit). Si vous êtes victime de discrimination, vous pouvez le signaler à un service anti-discrimination ou porter plainte à la police. Pour un problème juridique, le Juridisch Loket donne des conseils gratuits. À partir de 14 ans, il faut pouvoir montrer une pièce d’identité si la police le demande.',
        [{ d: 'de rechter', f: 'le juge' }, { d: 'de advocaat', f: 'l’avocat' }, { d: 'aangifte doen', f: 'porter plainte' }, { d: 'het identiteitsbewijs', f: 'la pièce d’identité' }],
        'Conseil juridique gratuit : Juridisch Loket. Violence à la maison : Veilig Thuis.',
        'À partir de quel âge faut-il pouvoir montrer une pièce d’identité à la police ?', ['14 ans', '18 ans', '21 ans']),
      P('m-ind', 'Titre de séjour et naturalisation',
        'L’IND (Immigratie- en Naturalisatiedienst) décide des visas et des titres de séjour, dont le visa MVV pour rejoindre votre partenaire. Après votre arrivée, vous recevez un titre de séjour (verblijfsvergunning) : vérifiez sa date de fin et demandez son renouvellement à temps. Signalez à l’IND les changements importants, comme une séparation. Après plusieurs années de séjour légal et l’examen d’intégration réussi, on peut demander un séjour permanent ou la nationalité néerlandaise.',
        [{ d: 'de IND', f: 'le service d’immigration' }, { d: 'de verblijfsvergunning', f: 'le titre de séjour' }, { d: 'verlengen', f: 'prolonger' }, { d: 'de naturalisatie', f: 'la naturalisation' }],
        'Surveillez la date de fin de votre titre de séjour.',
        'Quel organisme décide des titres de séjour ?', ['L’IND', 'DUO', 'La commune']),
      P('m7p1', 'La commune, le BSN et DigiD',
        'Dès votre arrivée, vous vous inscrivez à la commune (gemeente). Vous recevez alors un numéro personnel, le BSN (burgerservicenummer), indispensable pour travailler, ouvrir un compte bancaire ou aller chez le médecin. Avec DigiD, votre identifiant numérique, vous faites vos démarches en ligne (commune, impôts, DUO, assurance). Ne donnez jamais votre DigiD à quelqu’un d’autre. La commune délivre aussi passeports et cartes d’identité, enregistre naissances et mariages, et doit être prévenue de tout déménagement (au plus tard 5 jours après).',
        [{ d: 'het BSN', f: 'le numéro personnel' }, { d: 'DigiD', f: 'l’identifiant numérique de l’État' }, { d: 'de gemeente', f: 'la commune' }, { d: 'inschrijven', f: 's’inscrire' }],
        'BSN = votre numéro ; DigiD = votre clé pour les sites officiels.',
        'À quoi sert DigiD ?', ['À faire ses démarches officielles en ligne', 'À acheter des billets de train', 'À faire ses courses']),
      P('m7p2', 'Police : 112 ou 0900-8844 ?',
        'Le 112 est réservé aux urgences : danger immédiat, crime en cours, accident avec blessés, incendie. Pour contacter la police sans urgence, par exemple pour signaler un vélo volé la veille, on appelle le 0900-8844. Certains vols peuvent aussi être déclarés en ligne. La police est là pour aider : vous pouvez lui demander de l’aide sans crainte.',
        [{ d: 'de politie', f: 'la police' }, { d: 'de diefstal', f: 'le vol' }, { d: 'het noodnummer', f: 'le numéro d’urgence' }, { d: 'de melding', f: 'le signalement' }],
        'Vélo volé hier, pas de danger : 0900-8844.',
        'Quel numéro pour signaler un vol de vélo sans urgence ?', ['0900-8844', '112', '911']),
    ] },

  { id: 'taal', cat: 'taal', t: 'La langue néerlandaise', nl: 'Nederlandse taal', icon: '💬',
    sources: [S('Rijksoverheid.nl — Inburgeren', 'https://www.rijksoverheid.nl/onderwerpen/inburgering-en-integratie'), S('Inburgeren.nl (DUO)', 'https://www.inburgeren.nl'), S('Naar Nederland (DUO)', 'https://www.naarnederland.nl')],
    pages: [
      P('m-taal1', 'Où parle-t-on néerlandais ?',
        'Le néerlandais (Nederlands) est la langue officielle des Pays-Bas. On le parle aussi en Flandre, dans le nord de la Belgique, au Suriname et dans les îles néerlandaises des Caraïbes. En Frise, le frison est aussi une langue officielle. Dans certaines régions, les gens parlent un dialecte, mais tout le monde comprend le néerlandais standard. Beaucoup de Néerlandais parlent anglais, mais au travail, à l’école et dans les administrations, tout se passe en néerlandais.',
        [{ d: 'het Nederlands', f: 'le néerlandais' }, { d: 'het Fries', f: 'le frison' }, { d: 'Vlaanderen', f: 'la Flandre' }, { d: 'het dialect', f: 'le dialecte' }],
        'Néerlandais : Pays-Bas, Flandre, Suriname, Caraïbes néerlandaises.',
        'Dans quelle province le frison est-il aussi langue officielle ?', ['La Frise', 'Le Limbourg', 'La Zélande']),
      P('m-taal2', 'Après l’arrivée, l’intégration continue',
        'L’examen à l’étranger n’est que la première étape. Aux Pays-Bas, la plupart des nouveaux arrivants doivent continuer : la commune vous invite à un entretien (brede intake) et fait avec vous un plan (PIP). Il faut ensuite réussir l’examen d’intégration, en général au niveau B1, dans un délai de 3 ans. Il comprend la langue (lire, écouter, écrire, parler) et la connaissance de la société. Les personnes venues rejoindre un partenaire paient elles-mêmes leurs cours ; DUO peut prêter l’argent.',
        [{ d: 'inburgeren', f: 's’intégrer (parcours officiel)' }, { d: 'de inburgeringsplicht', f: 'l’obligation d’intégration' }, { d: 'de brede intake', f: 'l’entretien d’accueil' }, { d: 'de lening', f: 'le prêt' }],
        'Après l’arrivée : entretien à la commune, puis examen (souvent B1) en 3 ans.',
        'Qui paie en général les cours d’un migrant venu rejoindre son partenaire ?', ['Lui-même (prêt DUO possible)', 'La commune', 'L’employeur']),
      P('m-taal3', 'Pratiquer au quotidien',
        'On apprend plus vite en parlant tous les jours. Les bibliothèques proposent souvent un « Taalhuis » ou un « taalcafé » pour pratiquer avec des bénévoles. Le bénévolat (vrijwilligerswerk) est aussi un bon moyen de rencontrer des gens. Osez dire : « Wilt u dat herhalen? » (Pouvez-vous répéter ?), « Wilt u langzaam praten? » (Pouvez-vous parler lentement ?). Les Néerlandais tutoient vite (« je »), mais on vouvoie (« u ») les inconnus, les personnes âgées et les administrations.',
        [{ d: 'de bibliotheek', f: 'la bibliothèque' }, { d: 'de vrijwilliger', f: 'le bénévole' }, { d: 'herhalen', f: 'répéter' }, { d: 'u / je', f: 'vous / tu' }],
        'Demander de répéter est normal et poli.',
        'Où peut-on souvent pratiquer le néerlandais avec des bénévoles ?', ['À la bibliothèque (taalcafé)', 'À la police', 'À la banque']),
    ] },

  { id: 'onderwijs', cat: 'onderwijs', t: 'Enfants & école', nl: 'Opvoeding en onderwijs', icon: '🎒',
    sources: [S('Rijksoverheid.nl — Onderwijs', 'https://www.rijksoverheid.nl/onderwerpen/leerplicht'), S('SVB — Kinderbijslag', 'https://www.svb.nl'), S('Rijksvaccinatieprogramma', 'https://rijksvaccinatieprogramma.nl')],
    pages: [
      P('m-klein', 'Les petits enfants : consultatiebureau et garde',
        'Après la naissance, les parents vont régulièrement au « consultatiebureau » avec leur bébé. On y suit gratuitement la croissance et le développement de l’enfant jusqu’à 4 ans et on y fait les vaccins. La vaccination est volontaire, mais presque tous les parents la font. Pour les parents qui travaillent, il existe des crèches (kinderdagverblijf) et des assistantes maternelles (gastouder). L’État aide à payer ces frais (kinderopvangtoeslag) et verse chaque trimestre des allocations familiales (kinderbijslag) via la SVB.',
        [{ d: 'het consultatiebureau', f: 'le centre de suivi des bébés' }, { d: 'de vaccinatie', f: 'la vaccination' }, { d: 'de kinderopvang', f: 'la garde d’enfants' }, { d: 'de kinderbijslag', f: 'les allocations familiales' }],
        'Consultatiebureau : suivi et vaccins gratuits jusqu’à 4 ans.',
        'Que fait-on au consultatiebureau ?', ['On suit la santé du bébé et on le vaccine', 'On inscrit l’enfant à l’école', 'On paie les impôts']),
      P('m4p1', 'L’obligation scolaire (leerplicht)',
        'La plupart des enfants vont à l’école dès 4 ans. L’obligation scolaire commence le premier jour du mois qui suit le 5e anniversaire. Ensuite, les jeunes doivent aller à l’école jusqu’à 18 ans, ou jusqu’à ce qu’ils aient un diplôme de base (startkwalificatie). Partir en vacances en dehors des vacances scolaires n’est possible que dans des cas particuliers, avec l’accord du directeur de l’école.',
        [{ d: 'de leerplicht', f: 'l’obligation scolaire' }, { d: 'de schoolvakantie', f: 'les vacances scolaires' }, { d: 'de basisschool', f: 'l’école primaire' }, { d: 'de directeur', f: 'le directeur' }],
        'Sans l’accord du directeur, l’absence est signalée et les parents peuvent recevoir une amende.',
        'À quel âge commence l’obligation scolaire ?', ['5 ans', '4 ans', '6 ans']),
      P('m4p2', 'Les parents et l’école',
        'Les parents participent à la vie de l’école. Plusieurs fois par an, il y a un court rendez-vous avec l’enseignant, le « tienminutengesprek », pour parler des progrès de l’enfant. L’école demande souvent une contribution (ouderbijdrage) pour les sorties et les fêtes. Elle est toujours facultative : un enfant ne peut pas être exclu d’une activité parce que les parents n’ont pas payé. Si votre enfant est harcelé (gepest), parlez-en à l’enseignant : l’école doit agir.',
        [{ d: 'het tienminutengesprek', f: 'l’entretien parents-enseignant' }, { d: 'de ouderbijdrage', f: 'la contribution des parents' }, { d: 'de leerkracht', f: 'l’enseignant' }, { d: 'pesten', f: 'harceler' }],
        'Aller aux rendez-vous de l’école montre que vous vous impliquez : c’est attendu.',
        'À quoi sert le « tienminutengesprek » ?', ['Parler des progrès de l’enfant avec l’enseignant', 'Passer un examen de langue', 'Payer la cantine']),
      P('m4p3', 'Le parcours scolaire',
        'L’école primaire (basisschool) dure 8 ans, de groep 1 à groep 8. En groep 8, un test (doorstroomtoets) et l’avis de l’enseignant aident à choisir la suite : vmbo (professionnel), havo ou vwo (prépare aux études supérieures). Ensuite viennent le mbo (formation professionnelle), le hbo ou l’université. L’agence DUO gère les bourses d’études et aussi les examens d’intégration.',
        [{ d: 'DUO', f: 'l’agence de l’éducation et des examens' }, { d: 'het vmbo', f: 'le collège professionnel' }, { d: 'het mbo', f: 'la formation professionnelle' }, { d: 'de universiteit', f: 'l’université' }],
        'Primaire : 8 ans (groep 1 à 8), puis vmbo, havo ou vwo.',
        'Combien d’années dure l’école primaire ?', ['8 ans', '5 ans', '12 ans']),
      P('m-opvoeding', 'Élever ses enfants : droits et devoirs',
        'Aux Pays-Bas, la violence dans l’éducation est interdite par la loi depuis 2007 : on ne frappe pas un enfant, même pour le punir. Le père et la mère ont les mêmes droits et devoirs, aussi après une séparation. Les enfants sont mineurs jusqu’à 18 ans. Les parents qui ont des questions sur l’éducation peuvent demander conseil gratuitement, par exemple au consultatiebureau ou au centre pour la jeunesse et la famille de leur commune.',
        [{ d: 'de opvoeding', f: 'l’éducation (à la maison)' }, { d: 'de ouders', f: 'les parents' }, { d: 'minderjarig', f: 'mineur' }, { d: 'het geweld', f: 'la violence' }],
        'Frapper un enfant est interdit. Les deux parents décident ensemble.',
        'Peut-on frapper son enfant pour le punir ?', ['Non, c’est interdit', 'Oui, à la maison', 'Seulement un peu']),
    ] },

  { id: 'zorg', cat: 'zorg', t: 'Santé & soins', nl: 'Gezondheidszorg', icon: '🩺',
    sources: [S('Rijksoverheid.nl — Zorgverzekering', 'https://www.rijksoverheid.nl/onderwerpen/zorgverzekering'), S('Thuisarts.nl', 'https://www.thuisarts.nl'), S('Belastingdienst — Toeslagen', 'https://www.belastingdienst.nl/toeslagen')],
    pages: [
      P('m1p1', 'Le médecin généraliste (huisarts)',
        'Aux Pays-Bas, le médecin généraliste (de huisarts) est la porte d’entrée de tout le système de santé. Vous vous inscrivez dans un cabinet près de chez vous. Au téléphone, c’est souvent l’assistante qui répond et décide si vous avez besoin d’un rendez-vous. Pour voir un spécialiste à l’hôpital, il faut d’abord une lettre d’orientation, la « verwijsbrief », délivrée par votre huisarts. Le huisarts aide aussi en cas de problèmes psychologiques (stress, déprime) et peut orienter vers un psychologue.',
        [{ d: 'de huisarts', f: 'le médecin généraliste' }, { d: 'de verwijsbrief', f: 'la lettre d’orientation' }, { d: 'de afspraak', f: 'le rendez-vous' }, { d: 'de assistente', f: 'l’assistante médicale' }],
        'Pour tout problème de santé, même psychologique : d’abord le huisarts.',
        'Que faut-il pour voir un spécialiste à l’hôpital ?', ['Une lettre d’orientation du huisarts', 'Une carte bancaire', 'Une lettre de la commune']),
      P('m1p2', 'Urgences : 112 ou huisartsenpost ?',
        'Le numéro 112 est réservé aux situations où la vie est en danger : accident grave, incendie, malaise cardiaque, crime en cours. Le soir, la nuit et le week-end, si vous avez un problème de santé urgent qui ne peut pas attendre le lendemain, appelez la « huisartsenpost » (HAP). On ne va pas directement aux urgences de l’hôpital sans avoir appelé. Pour une rage de dents, le répondeur de votre dentiste indique le dentiste de garde.',
        [{ d: 'het alarmnummer 112', f: 'le numéro d’urgence vitale' }, { d: 'de huisartsenpost', f: 'le service médical de garde' }, { d: 'de ambulance', f: 'l’ambulance' }, { d: 'de spoedeisende hulp', f: 'les urgences de l’hôpital' }],
        'Soir et week-end : téléphonez toujours à la HAP avant de vous déplacer.',
        'Dimanche, votre enfant a beaucoup de fièvre. Que faites-vous ?', ['Appeler la huisartsenpost', 'Appeler le 112', 'Aller directement à l’hôpital']),
      P('m1p3', 'Assurance maladie et « eigen risico »',
        'Toute personne qui habite ou travaille aux Pays-Bas doit avoir une assurance maladie de base (basisverzekering). À partir de 18 ans, on paie soi-même une prime chaque mois. Les enfants de moins de 18 ans sont assurés gratuitement avec un parent. Les adultes ont une franchise annuelle, l’« eigen risico » ; la visite chez le huisarts n’en fait pas partie. Le dentiste des adultes n’est en général pas remboursé par l’assurance de base : il faut une assurance complémentaire. Avec un petit revenu, on peut recevoir une aide pour la prime : la « zorgtoeslag ».',
        [{ d: 'de zorgverzekering', f: 'l’assurance maladie' }, { d: 'het eigen risico', f: 'la franchise annuelle' }, { d: 'de aanvullende verzekering', f: 'l’assurance complémentaire' }, { d: 'de zorgtoeslag', f: 'l’aide pour la prime' }],
        'Le montant de l’eigen risico change chaque année : vérifiez-le chez votre assureur.',
        'Combien coûte l’assurance maladie d’un enfant de 10 ans ?', ['Rien : il est assuré gratuitement avec ses parents', 'Le même prix que pour un adulte', 'La moitié du prix adulte']),
      P('m-zwanger', 'Grossesse et naissance',
        'Pendant une grossesse normale, on est suivie par une sage-femme (verloskundige), sans passer par le médecin. On peut accoucher à la maison ou à l’hôpital. Après la naissance, une aide à domicile (kraamzorg) vient pendant environ une semaine pour aider la mère et le bébé : il faut la réserver tôt pendant la grossesse. La naissance doit être déclarée à la commune dans les 3 jours.',
        [{ d: 'zwanger', f: 'enceinte' }, { d: 'de verloskundige', f: 'la sage-femme' }, { d: 'de kraamzorg', f: 'l’aide après la naissance' }, { d: 'de geboorte', f: 'la naissance' }],
        'Grossesse normale : sage-femme. Naissance : déclarer à la commune dans les 3 jours.',
        'Qui suit en général une grossesse normale ?', ['Une sage-femme (verloskundige)', 'Le dentiste', 'Le pharmacien']),
    ] },

  { id: 'werk', cat: 'werk', t: 'Travail & argent', nl: 'Werk en inkomen', icon: '💼',
    sources: [S('Rijksoverheid.nl — Werk', 'https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao'), S('UWV / werk.nl', 'https://www.werk.nl'), S('SVB — AOW', 'https://www.svb.nl'), S('Belastingdienst', 'https://www.belastingdienst.nl')],
    pages: [
      P('m-werkzoeken', 'Chercher du travail',
        'Pour trouver du travail, on peut chercher sur des sites d’offres, s’inscrire dans une agence d’intérim (uitzendbureau) ou utiliser son réseau. Le site werk.nl de l’UWV publie aussi des offres. Préparez un CV court et une lettre de motivation. Vous pouvez faire évaluer votre diplôme étranger pour montrer son équivalent néerlandais. Le néerlandais est souvent demandé, même pour un emploi simple : c’est une raison de plus pour l’apprendre.',
        [{ d: 'de vacature', f: 'l’offre d’emploi' }, { d: 'solliciteren', f: 'postuler' }, { d: 'het uitzendbureau', f: 'l’agence d’intérim' }, { d: 'het cv', f: 'le CV' }],
        'Agence d’intérim et réseau : deux bonnes pistes pour un premier emploi.',
        'Qu’est-ce qu’un uitzendbureau ?', ['Une agence qui aide à trouver du travail (temporaire)', 'Une agence de voyage', 'Un bureau de poste']),
      P('m2p1', 'Le contrat et la période d’essai',
        'Un emploi salarié repose sur un contrat de travail (arbeidsovereenkomst). Il peut être à durée déterminée ou indéterminée (vast contract). Au début, il y a parfois une période d’essai (proeftijd) : 1 mois au maximum pour un contrat de moins de 2 ans, 2 mois pour un contrat plus long ou un CDI. Pendant cette période, chacun peut arrêter le contrat du jour au lendemain. Le salaire minimum légal est fixé par heure. Une femme et un homme doivent recevoir le même salaire pour le même travail.',
        [{ d: 'de proeftijd', f: 'la période d’essai' }, { d: 'het vaste contract', f: 'le CDI' }, { d: 'de werkgever', f: 'l’employeur' }, { d: 'het minimumloon', f: 'le salaire minimum' }],
        'Lisez bien votre contrat avant de signer : salaire, horaires, congés, durée.',
        'Que peut-il se passer pendant la proeftijd ?', ['Le contrat peut être arrêté du jour au lendemain', 'Vous ne recevez pas de salaire', 'Vous ne pouvez pas être malade']),
      P('m2p2', 'Maladie, congés et travail au noir',
        'Si vous êtes malade, prévenez votre employeur (ziek melden) le jour même, avant l’heure de début. Avec un temps plein, vous avez droit à au moins 4 semaines de congés payés par an, et en général à un pécule de vacances (vakantiegeld) d’environ 8 % du salaire. Le travail au noir (zwartwerken), c’est travailler sans que le revenu soit déclaré aux impôts : c’est illégal, et le travailleur n’a alors aucune protection. Un syndicat (vakbond) défend les intérêts des salariés.',
        [{ d: 'ziek melden', f: 'se déclarer malade' }, { d: 'het vakantiegeld', f: 'le pécule de vacances' }, { d: 'zwartwerken', f: 'travailler au noir' }, { d: 'de vakbond', f: 'le syndicat' }],
        'Malade ? Prévenez l’employeur avant l’heure de début.',
        'Qu’est-ce que le « zwartwerken » ?', ['Travailler sans déclarer son revenu', 'Travailler la nuit', 'Faire des heures supplémentaires']),
      P('m2p3', 'Fiche de paie et impôts',
        'L’employeur retient directement les impôts et les cotisations sur votre salaire brut. Ce qui arrive sur votre compte, c’est le salaire net. La fiche de paie (loonstrook) montre les heures, le brut, les retenues et le net. Chaque année, si vous recevez une lettre, vous faites votre déclaration de revenus (aangifte), en général avant le 1er mai. La Belastingdienst perçoit les impôts et verse, par son service Toeslagen, les aides comme la huurtoeslag ou la zorgtoeslag.',
        [{ d: 'de loonstrook', f: 'la fiche de paie' }, { d: 'het brutoloon', f: 'le salaire brut' }, { d: 'het nettoloon', f: 'le salaire net' }, { d: 'de aangifte', f: 'la déclaration (d’impôts)' }],
        'Déclaration de revenus : en général avant le 1er mai.',
        'Quel organisme perçoit les impôts et verse les aides ?', ['La Belastingdienst', 'La police', 'La commune']),
      P('m-geld', 'Argent : banque, aides et pension',
        'Aux Pays-Bas, on paie presque partout par carte (pinnen) ou avec le téléphone : ouvrez vite un compte bancaire, avec votre BSN. Les aides principales sont la huurtoeslag (loyer), la zorgtoeslag (assurance maladie), la kinderopvangtoeslag (garde) et la kinderbijslag (enfants). Signalez tout changement de revenu pour éviter de devoir rembourser. En cas de dettes, la commune aide gratuitement (schuldhulpverlening). À partir de 67 ans environ, on reçoit la pension de base de l’État, l’AOW ; son montant dépend des années vécues aux Pays-Bas.',
        [{ d: 'pinnen', f: 'payer par carte' }, { d: 'de toeslag', f: 'l’aide financière' }, { d: 'de schulden', f: 'les dettes' }, { d: 'de AOW', f: 'la pension de base de l’État' }],
        'Aides : signalez chaque changement de revenu. Dettes : demandez vite l’aide de la commune.',
        'Qu’est-ce que l’AOW ?', ['La pension de base de l’État', 'Une allocation pour étudiants', 'Une taxe sur les voitures']),
    ] },

  { id: 'usages', cat: 'usages', t: 'Vie quotidienne & usages', nl: 'Omgangsvormen en dagelijks leven', icon: '🤝',
    sources: [S('Rijksoverheid.nl — Verkeersregels', 'https://www.rijksoverheid.nl/onderwerpen/verkeersregels'), S('Government.nl', 'https://www.government.nl')],
    pages: [
      P('m8p1', 'La ponctualité et les rendez-vous',
        'Être à l’heure (op tijd komen) est très important, que ce soit pour un entretien, un rendez-vous médical ou une visite chez des amis. Arriver en retard sans prévenir est considéré comme impoli. En cas d’imprévu, on téléphone ou on envoie un message à l’avance. On prend souvent rendez-vous même pour une simple visite, et on dîne tôt, souvent vers 18 h.',
        [{ d: 'op tijd komen', f: 'arriver à l’heure' }, { d: 'de afspraak', f: 'le rendez-vous' }, { d: 'de agenda', f: 'l’agenda' }, { d: 'te laat', f: 'en retard' }],
        'En retard ? Prévenez toujours avant l’heure.',
        'Comment voit-on un retard non annoncé ?', ['Comme impoli', 'Comme normal', 'Comme amusant']),
      P('m8p2', 'Anniversaires, salutations et franchise',
        'À un anniversaire, les invités sont souvent assis en cercle (kringverjaardag). On félicite la personne fêtée, mais aussi sa famille : « Gefeliciteerd met je vrouw ! ». Quand on rencontre quelqu’un pour la première fois, on serre la main et on dit son nom ; les trois bises sont réservées aux proches. Les Néerlandais sont souvent directs : un « non » clair n’est pas impoli.',
        [{ d: 'de verjaardag', f: 'l’anniversaire' }, { d: 'feliciteren', f: 'féliciter' }, { d: 'een hand geven', f: 'serrer la main' }, { d: 'direct', f: 'direct, franc' }],
        'Première rencontre = poignée de main et votre nom.',
        'Qui félicite-t-on lors d’un anniversaire en cercle ?', ['La personne fêtée et ses proches', 'Seulement la personne fêtée', 'Personne']),
      P('m3p3', 'Les voisins',
        'Quand on emménage, on se présente souvent aux voisins. Après 22 h, on évite le bruit : ce n’est pas une loi nationale, mais c’est l’usage, et souvent la règle de l’immeuble ou de la commune. En cas de problème avec un voisin, on va d’abord lui parler calmement. Si cela ne suffit pas, on peut contacter le propriétaire ou un service de médiation (buurtbemiddeling), et en dernier recours la police.',
        [{ d: 'de buren', f: 'les voisins' }, { d: 'de overlast', f: 'la nuisance' }, { d: 'de buurtbemiddeling', f: 'la médiation de voisinage' }, { d: 'rustig', f: 'calme' }],
        'Parler d’abord directement et poliment : c’est la réponse attendue à l’examen.',
        'Le voisin fait du bruit tard le soir. Que faites-vous d’abord ?', ['Je vais lui parler calmement', 'J’appelle le 112', 'Je fais du bruit moi aussi']),
      P('m-verkeer', 'Circuler : vélo et transports',
        'Le vélo est partout. À un carrefour sans panneaux, la priorité est à droite, aussi pour les vélos. La nuit, il faut une lumière blanche devant et rouge derrière. Pour tourner, on tend le bras. Téléphoner en tenant son téléphone à vélo est interdit. Aux passages piétons, on laisse passer les piétons. Dans le train, le bus et le tram, on valide à la montée et à la descente (inchecken / uitchecken) avec une carte OV-chipkaart ou sa carte bancaire. Attachez toujours votre vélo : les vols sont fréquents.',
        [{ d: 'de fiets', f: 'le vélo' }, { d: 'voorrang', f: 'la priorité' }, { d: 'inchecken', f: 'valider à la montée' }, { d: 'het fietspad', f: 'la piste cyclable' }],
        'Priorité à droite ; lumières la nuit ; check in / check out dans les transports.',
        'Qui a la priorité à un carrefour sans panneaux ?', ['Celui qui vient de droite', 'Celui qui vient de gauche', 'Le plus rapide']),
    ] },
];
