// Illustrations des questions « Société » : une petite scène en symboles, choisie d’après le sujet de la question.
// (À l’examen officiel, chaque question accompagne une photo du pack « Naar Nederland » ; ici, une illustration simple.)

const RULES = [
  [/verwijsbrief|specialist/i, '🩺📄➡️🏥'],
  [/huisartsenpost/i, '🌙📞🩺'],
  [/huisarts|dokter|consult/i, '👩‍⚕️🩺'],
  [/112|alarmnummer|brand in je huis|levensgevaar/i, '🚨📞'],
  [/apotheek|medicijn/i, '💊🏪'],
  [/tandarts|kiespijn/i, '🦷😣'],
  [/zwanger|verloskundige/i, '🤰👩‍⚕️'],
  [/kraamzorg/i, '👶🏠👩‍⚕️'],
  [/vaccin|consultatiebureau/i, '👶💉'],
  [/zorgpas|zorgverzekering|eigen risico|zorgtoeslag|basisverzekering/i, '💳🩺'],
  [/somber|gestrest/i, '😔💬👩‍⚕️'],
  [/rookmelder/i, '🔥🔔'],
  [/brandblusser/i, '🧯🔥'],
  [/glas/i, '🍾♻️'],
  [/gft|groente- en fruitafval/i, '🥕🗑️'],
  [/kast|grofvuil|milieustraat/i, '🛋️🚛'],
  [/huurtoeslag|huur niet|huurwoning|woningcorporatie/i, '🏠💶'],
  [/muur|verhuurder|onderhoud|dak/i, '🏠🔨'],
  [/buren|muziek|nachtrust|rustig zijn/i, '🏢🎵🤫'],
  [/verhuizen|nieuwe adres/i, '📦🚚🏠'],
  [/fiets|linksaf/i, '🚲'],
  [/rotonde|kruispunt|voorrang/i, '🚦🚗🚲'],
  [/zebrapad/i, '🚶🦓🚗'],
  [/gordel/i, '🚗🔒'],
  [/alcohol/i, '🍺🚫🚗'],
  [/verkeerslicht/i, '🚦'],
  [/bebouwde kom|km per uur/i, '🏘️🚗'],
  [/trein|bus|tram|ov-chipkaart/i, '🚆🎫'],
  [/proeftijd|arbeidsovereenkomst|vast contract|contract/i, '📄✍️💼'],
  [/ziek en kunt niet werken|ziek melden/i, '🤒📞💼'],
  [/zwartwerken/i, '💶🚫🧾'],
  [/uwv|werk kwijt|ww-uitkering|ontslag/i, '💼❌📄'],
  [/loonstrook|minimumloon|vrouw minder betalen/i, '🧾💶'],
  [/vakantie/i, '🏖️📅'],
  [/uitzendbureau|vakbond/i, '👷🤝'],
  [/aow/i, '👴💶'],
  [/pinnen|winkel|webwinkel/i, '🛒💳'],
  [/schulden|rekeningen/i, '📄💸'],
  [/belastingdienst|aangifte/i, '🏛️🧾'],
  [/bijstand/i, '🏛️💶'],
  [/kamer van koophandel|kvk/i, '🏢📋'],
  [/leerplicht|school gaan|naar school|basisschool|4 jaar worden/i, '🎒🏫'],
  [/tienminutengesprek|gepest/i, '👩‍🏫👨‍👩‍👧'],
  [/ouderbijdrage/i, '🏫💶'],
  [/kinderopvang|kinderdagverblijf/i, '🧸👶'],
  [/kinderbijslag/i, '👧💶'],
  [/slaan|opvoeding/i, '👨‍👩‍👧❤️'],
  [/vmbo|mbo|doorstroomtoets|duo/i, '🎓📚'],
  [/koning|staatshoofd|koningsdag/i, '👑🇳🇱'],
  [/tweede kamer|eerste kamer|parlement|verkiezingen|stemmen/i, '🏛️🗳️'],
  [/minister-president|regering/i, '🏛️👔'],
  [/grondwet|artikel 1|discrimin/i, '📜⚖️'],
  [/rechter|juridisch/i, '⚖️👩‍⚖️'],
  [/\bpolitie\b|0900|identiteit/i, '👮🚓'],
  [/burgemeester|gemeente/i, '🏛️🏙️'],
  [/\bind\b|verblijfsvergunning/i, '🛂📄'],
  [/bsn|digid|paspoort|identiteitskaart|brp/i, '🪪💻'],
  [/brief/i, '✉️❓'],
  [/trouwen|homoseksualiteit/i, '💍❤️'],
  [/religie/i, '⛪🕌🕍'],
  [/meningsuiting/i, '🗣️💬'],
  [/mannen en vrouwen|man zijn vrouw/i, '👩🟰👨'],
  [/omkoping|corruptie|ambtenaar vraagt geld/i, '💶🚫🤝'],
  [/slaan\?|niet eens/i, '✋🚫'],
  [/anne frank/i, '📔✍️'],
  [/bezet|tweede wereldoorlog|4 mei|5 mei|bevrijding/i, '🕊️🇳🇱'],
  [/deltawerken|1953|overstroming|dijk/i, '🌊🧱'],
  [/molens/i, '🌬️🏚️'],
  [/waterschap|polder/i, '💧🧱'],
  [/willem van oranje|wilhelmus/i, '🧡🎺'],
  [/gouden eeuw|voc/i, '⛵💰'],
  [/slavernij/i, '⛓️🕊️'],
  [/gastarbeiders/i, '🏭👷'],
  [/suriname/i, '🌴🇸🇷'],
  [/stemmen\?|sinds wanneer mogen vrouwen/i, '👩🗳️'],
  [/euro|geld/i, '💶'],
  [/sinterklaas/i, '🎁🍪'],
  [/verjaardag|jarig/i, '🎂🎉'],
  [/op tijd|18\.00 uur|uitgenodigd/i, '⏰🍽️'],
  [/begroet/i, '🤝🙂'],
  [/u’ in plaats van|je’/i, '🗨️👵🧑'],
  [/vrijwilliger/i, '🙋‍♀️🤝'],
  [/plassen/i, '🚻🚫'],
  [/oudere vrouw|bus staat/i, '🚌👵💺'],
  [/direct ‘nee’/i, '🙅💬'],
  [/nederlands leren|taal|fries|vlaanderen|begrijpt de huisarts niet|fijne dag|beterschap|bibliotheek/i, '💬📖'],
  [/provincies|hoofdstad|buurlanden|rivieren|koninkrijk|randstad|noordzee|zee/i, '🗺️🇳🇱'],
];

// Choix explicites quand le sujet n’est pas reconnu correctement par les règles.
const OVERRIDES = {
  kns049: '🏛️🗳️', kns062: '🛂🏛️', kns064: '👛💳🔒', kns066: '🚲👮', kns067: '🏛️📄', kns077: '✋🚫',
  kns097: '🎁🍪', kns101: '💬📖', kns105: '💬👩‍⚕️', kns106: '🎓🇳🇱', kns107: '🎓💶', kns118: '👩🗳️',
  kns120: '💶', kns137: '👶💉', kns144: '🧒➡️🧑', kns147: '💳🩺', kns162: '🏠🤝', kns163: '🚌👵💺',
};

export function knsPicture(q, fallbackIcon) {
  if (OVERRIDES[q.id]) return OVERRIDES[q.id];
  const text = `${q.q} ${q.opts[q.corr]}`;
  const hit = RULES.find(([re]) => re.test(text));
  return hit ? hit[1] : fallbackIcon;
}
