// Vocabulaire A1 supplémentaire (environ 490 mots), par thème.
// n(nl, article, pluriel, fr, exemple, traduction) · v / j / a (verbe, adjectif, adverbe/expression) : (nl, fr, exemple, traduction)

let theme = '';
const rows = [];
const T = (name) => { theme = name; };
const n = (nl, art, pl, fr, ex, exFr) => rows.push([nl, art, 'n', fr, ex, exFr, theme, pl]);
const v = (nl, fr, ex, exFr) => rows.push([nl, null, 'v', fr, ex, exFr, theme, null]);
const j = (nl, fr, ex, exFr) => rows.push([nl, null, 'adj', fr, ex, exFr, theme, null]);
const a = (nl, fr, ex, exFr) => rows.push([nl, null, 'x', fr, ex, exFr, theme, null]);
const b = (nl, fr, ex, exFr) => rows.push([nl, null, 'adv', fr, ex, exFr, theme, null]);

T('Personnes');
n('moeder', 'de', 'moeders', 'la mère', 'Mijn moeder woont in Rabat.', 'Ma mère habite à Rabat.');
n('vader', 'de', 'vaders', 'le père', 'Mijn vader is zestig jaar.', 'Mon père a soixante ans.');
n('broer', 'de', 'broers', 'le frère', 'Ik heb één broer.', 'J’ai un frère.');
n('zus', 'de', 'zussen', 'la sœur', 'Mijn zus is getrouwd.', 'Ma sœur est mariée.');
n('opa', 'de', 'opa’s', 'le grand-père', 'Opa leest de krant.', 'Grand-père lit le journal.');
n('oma', 'de', 'oma’s', 'la grand-mère', 'Oma bakt een taart.', 'Grand-mère fait un gâteau.');
n('baby', 'de', 'baby’s', 'le bébé', 'De baby slaapt.', 'Le bébé dort.');
n('jongen', 'de', 'jongens', 'le garçon', 'De jongen speelt voetbal.', 'Le garçon joue au foot.');
n('meisje', 'het', 'meisjes', 'la fille (jeune)', 'Het meisje lacht.', 'La fille rit.');
n('partner', 'de', 'partners', 'le/la partenaire', 'Mijn partner werkt in Utrecht.', 'Mon partenaire travaille à Utrecht.');
n('oom', 'de', 'ooms', 'l’oncle', 'Mijn oom heeft een winkel.', 'Mon oncle a un magasin.');
n('tante', 'de', 'tantes', 'la tante', 'Mijn tante komt morgen.', 'Ma tante vient demain.');
n('neef', 'de', 'neven', 'le cousin / le neveu', 'Mijn neef is student.', 'Mon cousin est étudiant.');
n('nicht', 'de', 'nichten', 'la cousine / la nièce', 'Mijn nicht woont in Parijs.', 'Ma cousine habite à Paris.');
n('buurvrouw', 'de', 'buurvrouwen', 'la voisine', 'De buurvrouw is aardig.', 'La voisine est gentille.');
n('mens', 'de', 'mensen', 'la personne, l’être humain', 'Er zijn veel mensen.', 'Il y a beaucoup de gens.');
n('leeftijd', 'de', 'leeftijden', 'l’âge', 'Wat is uw leeftijd?', 'Quel est votre âge ?');
n('verjaardag', 'de', 'verjaardagen', 'l’anniversaire', 'Mijn verjaardag is in mei.', 'Mon anniversaire est en mai.');
n('bruiloft', 'de', 'bruiloften', 'le mariage (fête)', 'De bruiloft is zaterdag.', 'Le mariage est samedi.');
n('achternaam', 'de', 'achternamen', 'le nom de famille', 'Wat is uw achternaam?', 'Quel est votre nom de famille ?');
n('voornaam', 'de', 'voornamen', 'le prénom', 'Mijn voornaam is Sara.', 'Mon prénom est Sara.');
n('land', 'het', 'landen', 'le pays', 'Uit welk land komt u?', 'De quel pays venez-vous ?');
n('taal', 'de', 'talen', 'la langue', 'Ik spreek drie talen.', 'Je parle trois langues.');
j('getrouwd', 'marié', 'Ik ben getrouwd.', 'Je suis marié.');
j('gescheiden', 'divorcé', 'Hij is gescheiden.', 'Il est divorcé.');
j('oud', 'vieux, âgé', 'Mijn opa is oud.', 'Mon grand-père est âgé.');
j('jong', 'jeune', 'Zij is nog jong.', 'Elle est encore jeune.');
j('aardig', 'gentil', 'De docent is aardig.', 'Le professeur est gentil.');
j('blij', 'content', 'Ik ben blij.', 'Je suis content.');
j('verdrietig', 'triste', 'Het kind is verdrietig.', 'L’enfant est triste.');
j('boos', 'fâché', 'Waarom ben je boos?', 'Pourquoi es-tu fâché ?');
j('lang', 'grand (taille), long', 'Mijn broer is lang.', 'Mon frère est grand.');
v('lachen', 'rire', 'Wij lachen veel.', 'Nous rions beaucoup.');
v('huilen', 'pleurer', 'De baby huilt.', 'Le bébé pleure.');
v('trouwen', 'se marier', 'Ze gaan in juni trouwen.', 'Ils se marient en juin.');
v('kennen', 'connaître', 'Ken je mijn zus?', 'Tu connais ma sœur ?');

T('Corps & santé');
n('hoofd', 'het', 'hoofden', 'la tête', 'Mijn hoofd doet pijn.', 'J’ai mal à la tête.');
n('hoofdpijn', 'de', null, 'le mal de tête', 'Ik heb hoofdpijn.', 'J’ai mal à la tête.');
n('buik', 'de', 'buiken', 'le ventre', 'Ik heb buikpijn.', 'J’ai mal au ventre.');
n('rug', 'de', 'ruggen', 'le dos', 'Mijn rug doet pijn.', 'J’ai mal au dos.');
n('arm', 'de', 'armen', 'le bras', 'Hij heeft zijn arm gebroken.', 'Il s’est cassé le bras.');
n('been', 'het', 'benen', 'la jambe', 'Mijn been doet pijn.', 'J’ai mal à la jambe.');
n('hand', 'de', 'handen', 'la main', 'Was je handen.', 'Lave-toi les mains.');
n('voet', 'de', 'voeten', 'le pied', 'Ik heb koude voeten.', 'J’ai froid aux pieds.');
n('oog', 'het', 'ogen', 'l’œil', 'Zij heeft bruine ogen.', 'Elle a les yeux marron.');
n('oor', 'het', 'oren', 'l’oreille', 'Mijn oor doet pijn.', 'J’ai mal à l’oreille.');
n('neus', 'de', 'neuzen', 'le nez', 'Mijn neus is verstopt.', 'J’ai le nez bouché.');
n('mond', 'de', 'monden', 'la bouche', 'Doe je mond open.', 'Ouvre la bouche.');
n('tand', 'de', 'tanden', 'la dent', 'Ik poets mijn tanden.', 'Je me brosse les dents.');
n('keel', 'de', 'kelen', 'la gorge', 'Ik heb keelpijn.', 'J’ai mal à la gorge.');
n('hart', 'het', 'harten', 'le cœur', 'Het hart klopt snel.', 'Le cœur bat vite.');
n('koorts', 'de', null, 'la fièvre', 'Het kind heeft koorts.', 'L’enfant a de la fièvre.');
n('griep', 'de', null, 'la grippe', 'Ik heb griep.', 'J’ai la grippe.');
n('hoest', 'de', null, 'la toux', 'Hij heeft een hoest.', 'Il tousse.');
n('recept', 'het', 'recepten', 'l’ordonnance', 'De dokter geeft een recept.', 'Le médecin donne une ordonnance.');
n('pil', 'de', 'pillen', 'la pilule, le comprimé', 'Neem een pil met water.', 'Prends un comprimé avec de l’eau.');
n('patiënt', 'de', 'patiënten', 'le patient', 'De patiënt wacht.', 'Le patient attend.');
n('verpleegkundige', 'de', 'verpleegkundigen', 'l’infirmier / l’infirmière', 'De verpleegkundige helpt mij.', 'L’infirmière m’aide.');
n('ambulance', 'de', 'ambulances', 'l’ambulance', 'Bel een ambulance!', 'Appelle une ambulance !');
n('wachtkamer', 'de', 'wachtkamers', 'la salle d’attente', 'Ik zit in de wachtkamer.', 'Je suis dans la salle d’attente.');
j('gezond', 'en bonne santé, sain', 'Fruit is gezond.', 'Les fruits sont bons pour la santé.');
j('zwanger', 'enceinte', 'Mijn vrouw is zwanger.', 'Ma femme est enceinte.');
j('gebroken', 'cassé', 'Mijn arm is gebroken.', 'Mon bras est cassé.');
v('hoesten', 'tousser', 'Ik moet veel hoesten.', 'Je tousse beaucoup.');
v('voelen', 'sentir, ressentir', 'Ik voel me niet goed.', 'Je ne me sens pas bien.');
v('rusten', 'se reposer', 'U moet veel rusten.', 'Vous devez beaucoup vous reposer.');
v('bellen', 'appeler, téléphoner', 'Ik bel de huisarts.', 'J’appelle le médecin.');
v('wassen', 'laver', 'Ik was mijn handen.', 'Je me lave les mains.');
v('poetsen', 'brosser, nettoyer', 'Ik poets mijn tanden.', 'Je me brosse les dents.');
a('beterschap', 'bon rétablissement', 'Beterschap!', 'Bon rétablissement !');

T('Maison');
n('appartement', 'het', 'appartementen', 'l’appartement', 'Ik woon in een appartement.', 'J’habite dans un appartement.');
n('kamer', 'de', 'kamers', 'la pièce, la chambre', 'Het huis heeft vier kamers.', 'La maison a quatre pièces.');
n('woonkamer', 'de', 'woonkamers', 'le salon', 'De tv staat in de woonkamer.', 'La télé est dans le salon.');
n('keuken', 'de', 'keukens', 'la cuisine', 'Ik kook in de keuken.', 'Je cuisine dans la cuisine.');
n('badkamer', 'de', 'badkamers', 'la salle de bain', 'De badkamer is boven.', 'La salle de bain est en haut.');
n('toilet', 'het', 'toiletten', 'les toilettes', 'Waar is het toilet?', 'Où sont les toilettes ?');
n('douche', 'de', 'douches', 'la douche', 'Ik neem een douche.', 'Je prends une douche.');
n('bed', 'het', 'bedden', 'le lit', 'Het bed is groot.', 'Le lit est grand.');
n('tafel', 'de', 'tafels', 'la table', 'We eten aan tafel.', 'Nous mangeons à table.');
n('stoel', 'de', 'stoelen', 'la chaise', 'Ga op de stoel zitten.', 'Assieds-toi sur la chaise.');
n('bank', 'de', 'banken', 'le canapé / la banque', 'We zitten op de bank.', 'Nous sommes assis sur le canapé.');
n('kast', 'de', 'kasten', 'l’armoire, le placard', 'De borden staan in de kast.', 'Les assiettes sont dans le placard.');
n('lamp', 'de', 'lampen', 'la lampe', 'Doe de lamp aan.', 'Allume la lampe.');
n('vloer', 'de', 'vloeren', 'le sol', 'De vloer is schoon.', 'Le sol est propre.');
n('muur', 'de', 'muren', 'le mur', 'De muur is wit.', 'Le mur est blanc.');
n('dak', 'het', 'daken', 'le toit', 'Het dak lekt.', 'Le toit fuit.');
n('verdieping', 'de', 'verdiepingen', 'l’étage', 'Ik woon op de tweede verdieping.', 'J’habite au deuxième étage.');
n('lift', 'de', 'liften', 'l’ascenseur', 'De lift is kapot.', 'L’ascenseur est en panne.');
n('balkon', 'het', 'balkons', 'le balcon', 'We hebben een klein balkon.', 'Nous avons un petit balcon.');
n('verwarming', 'de', null, 'le chauffage', 'De verwarming doet het niet.', 'Le chauffage ne marche pas.');
n('koelkast', 'de', 'koelkasten', 'le réfrigérateur', 'De melk staat in de koelkast.', 'Le lait est au frigo.');
n('wasmachine', 'de', 'wasmachines', 'la machine à laver', 'De wasmachine is kapot.', 'La machine à laver est en panne.');
n('vuilnisbak', 'de', 'vuilnisbakken', 'la poubelle', 'Gooi het in de vuilnisbak.', 'Jette-le à la poubelle.');
n('afval', 'het', null, 'les déchets', 'Het afval moet naar buiten.', 'Les déchets doivent être sortis.');
n('buurt', 'de', 'buurten', 'le quartier', 'Het is een rustige buurt.', 'C’est un quartier calme.');
n('huisnummer', 'het', 'huisnummers', 'le numéro de maison', 'Wat is uw huisnummer?', 'Quel est votre numéro ?');
n('bel', 'de', 'bellen', 'la sonnette', 'De bel doet het niet.', 'La sonnette ne marche pas.');
n('stroom', 'de', null, 'l’électricité', 'Er is geen stroom.', 'Il n’y a pas d’électricité.');
v('de was doen', 'faire la lessive', 'Ik doe de was.', 'Je fais la lessive.');
v('opruimen', 'ranger', 'Ruim je kamer op!', 'Range ta chambre !');
v('repareren', 'réparer', 'Kunt u de deur repareren?', 'Pouvez-vous réparer la porte ?');
v('openen', 'ouvrir', 'Kunt u het raam openen?', 'Pouvez-vous ouvrir la fenêtre ?');
v('sluiten', 'fermer', 'Sluit de deur, alstublieft.', 'Fermez la porte, s’il vous plaît.');
j('schoon', 'propre', 'De keuken is schoon.', 'La cuisine est propre.');
j('vies', 'sale', 'Mijn schoenen zijn vies.', 'Mes chaussures sont sales.');
j('kapot', 'cassé, en panne', 'Mijn fiets is kapot.', 'Mon vélo est cassé.');
j('open', 'ouvert', 'De winkel is open.', 'Le magasin est ouvert.');
j('dicht', 'fermé', 'De deur is dicht.', 'La porte est fermée.');
b('boven', 'en haut', 'De slaapkamer is boven.', 'La chambre est en haut.');
b('beneden', 'en bas', 'De keuken is beneden.', 'La cuisine est en bas.');

T('Alimentation');
n('kaas', 'de', 'kazen', 'le fromage', 'Ik eet brood met kaas.', 'Je mange du pain avec du fromage.');
n('ei', 'het', 'eieren', 'l’œuf', 'Ik eet een ei.', 'Je mange un œuf.');
n('boter', 'de', null, 'le beurre', 'Brood met boter.', 'Du pain avec du beurre.');
n('rijst', 'de', null, 'le riz', 'We eten rijst met kip.', 'Nous mangeons du riz au poulet.');
n('kip', 'de', 'kippen', 'le poulet', 'De kip is lekker.', 'Le poulet est bon.');
n('vis', 'de', 'vissen', 'le poisson', 'Op vrijdag eten we vis.', 'Le vendredi, nous mangeons du poisson.');
n('soep', 'de', 'soepen', 'la soupe', 'De soep is warm.', 'La soupe est chaude.');
n('aardappel', 'de', 'aardappelen', 'la pomme de terre', 'Ik kook aardappelen.', 'Je fais cuire des pommes de terre.');
n('tomaat', 'de', 'tomaten', 'la tomate', 'Twee tomaten, alstublieft.', 'Deux tomates, s’il vous plaît.');
n('ui', 'de', 'uien', 'l’oignon', 'Snijd de ui.', 'Coupe l’oignon.');
n('wortel', 'de', 'wortels', 'la carotte', 'Konijnen eten wortels.', 'Les lapins mangent des carottes.');
n('sla', 'de', null, 'la salade', 'Ik maak een sla.', 'Je fais une salade.');
n('banaan', 'de', 'bananen', 'la banane', 'Een banaan is gezond.', 'Une banane, c’est sain.');
n('sinaasappel', 'de', 'sinaasappels', 'l’orange', 'Ik pers een sinaasappel.', 'Je presse une orange.');
n('druif', 'de', 'druiven', 'le raisin', 'De druiven zijn zoet.', 'Les raisins sont sucrés.');
n('suiker', 'de', null, 'le sucre', 'Koffie zonder suiker.', 'Un café sans sucre.');
n('zout', 'het', null, 'le sel', 'Er is te veel zout in de soep.', 'Il y a trop de sel dans la soupe.');
n('peper', 'de', null, 'le poivre', 'Een beetje peper.', 'Un peu de poivre.');
n('sap', 'het', 'sappen', 'le jus', 'Een glas sap, alstublieft.', 'Un verre de jus, s’il vous plaît.');
n('glas', 'het', 'glazen', 'le verre', 'Het glas is leeg.', 'Le verre est vide.');
n('kopje', 'het', 'kopjes', 'la tasse', 'Wil je een kopje thee?', 'Tu veux une tasse de thé ?');
n('bord', 'het', 'borden', 'l’assiette', 'Zet de borden op tafel.', 'Mets les assiettes sur la table.');
n('mes', 'het', 'messen', 'le couteau', 'Het mes is scherp.', 'Le couteau est tranchant.');
n('vork', 'de', 'vorken', 'la fourchette', 'Ik eet met een vork.', 'Je mange avec une fourchette.');
n('lepel', 'de', 'lepels', 'la cuillère', 'Soep eet je met een lepel.', 'La soupe se mange avec une cuillère.');
n('lunch', 'de', 'lunches', 'le déjeuner', 'De lunch is om twaalf uur.', 'Le déjeuner est à midi.');
n('honger', 'de', null, 'la faim', 'Ik heb honger.', 'J’ai faim.');
n('dorst', 'de', null, 'la soif', 'Ik heb dorst.', 'J’ai soif.');
n('restaurant', 'het', 'restaurants', 'le restaurant', 'We eten in een restaurant.', 'Nous mangeons au restaurant.');
n('taart', 'de', 'taarten', 'le gâteau, la tarte', 'Er is taart voor de jarige.', 'Il y a un gâteau pour la personne fêtée.');
v('eten', 'manger', 'Wat eet je vandaag?', 'Que manges-tu aujourd’hui ?');
v('drinken', 'boire', 'Ik drink veel water.', 'Je bois beaucoup d’eau.');
v('bakken', 'cuire, faire frire', 'Ik bak een ei.', 'Je fais cuire un œuf.');
v('snijden', 'couper', 'Ik snijd het brood.', 'Je coupe le pain.');
v('proeven', 'goûter', 'Wil je de soep proeven?', 'Tu veux goûter la soupe ?');
j('zoet', 'sucré', 'De taart is zoet.', 'Le gâteau est sucré.');
j('warm', 'chaud', 'De thee is warm.', 'Le thé est chaud.');
j('koud', 'froid', 'Het water is koud.', 'L’eau est froide.');
j('vers', 'frais', 'Het brood is vers.', 'Le pain est frais.');
a('eet smakelijk', 'bon appétit', 'Eet smakelijk!', 'Bon appétit !');

T('Courses & argent');
n('winkel', 'de', 'winkels', 'le magasin', 'De winkel gaat om negen uur open.', 'Le magasin ouvre à neuf heures.');
n('supermarkt', 'de', 'supermarkten', 'le supermarché', 'Ik ga naar de supermarkt.', 'Je vais au supermarché.');
n('prijs', 'de', 'prijzen', 'le prix', 'Wat is de prijs?', 'Quel est le prix ?');
n('euro', 'de', 'euro’s', 'l’euro', 'Het kost vijf euro.', 'Ça coûte cinq euros.');
n('cent', 'de', 'centen', 'le centime', 'Het kost negentig cent.', 'Ça coûte quatre-vingt-dix centimes.');
n('bon', 'de', 'bonnen', 'le ticket de caisse', 'Wilt u de bon?', 'Voulez-vous le ticket ?');
n('korting', 'de', 'kortingen', 'la réduction', 'Er is 20 procent korting.', 'Il y a 20 % de réduction.');
n('aanbieding', 'de', 'aanbiedingen', 'la promotion', 'De appels zijn in de aanbieding.', 'Les pommes sont en promotion.');
n('pinpas', 'de', 'pinpassen', 'la carte bancaire', 'Ik betaal met mijn pinpas.', 'Je paie avec ma carte.');
n('rekening', 'de', 'rekeningen', 'la facture / le compte', 'Ik betaal de rekening.', 'Je paie la facture.');
n('portemonnee', 'de', 'portemonnees', 'le porte-monnaie', 'Mijn portemonnee is weg.', 'Mon porte-monnaie a disparu.');
n('klant', 'de', 'klanten', 'le client', 'De klant wacht bij de kassa.', 'Le client attend à la caisse.');
n('kilo', 'de', 'kilo’s', 'le kilo', 'Een kilo aardappelen.', 'Un kilo de pommes de terre.');
n('liter', 'de', 'liters', 'le litre', 'Een liter melk.', 'Un litre de lait.');
n('pak', 'het', 'pakken', 'le paquet, la brique', 'Een pak melk.', 'Une brique de lait.');
n('fles', 'de', 'flessen', 'la bouteille', 'Een fles water.', 'Une bouteille d’eau.');
n('stuk', 'het', 'stukken', 'le morceau, la pièce', 'Een stuk kaas.', 'Un morceau de fromage.');
n('boodschappen', 'de', null, 'les courses', 'Ik doe boodschappen.', 'Je fais les courses.');
v('kopen', 'acheter', 'Ik koop brood.', 'J’achète du pain.');
v('betalen', 'payer', 'Kan ik hier betalen?', 'Puis-je payer ici ?');
v('kosten', 'coûter', 'Wat kost dit?', 'Combien ça coûte ?');
v('pinnen', 'payer par carte', 'Kan ik pinnen?', 'Puis-je payer par carte ?');
v('verkopen', 'vendre', 'Hij verkoopt zijn fiets.', 'Il vend son vélo.');
v('sparen', 'économiser', 'Ik spaar voor een auto.', 'J’économise pour une voiture.');
v('zoeken', 'chercher', 'Ik zoek de melk.', 'Je cherche le lait.');
v('nodig hebben', 'avoir besoin de', 'Ik heb een tas nodig.', 'J’ai besoin d’un sac.');
j('gratis', 'gratuit', 'De koffie is gratis.', 'Le café est gratuit.');
j('contant', 'en espèces', 'Ik betaal contant.', 'Je paie en espèces.');
a('hoeveel', 'combien', 'Hoeveel kost het?', 'Combien ça coûte ?');
a('te koop', 'à vendre', 'Het huis is te koop.', 'La maison est à vendre.');

T('Vêtements & couleurs');
n('jas', 'de', 'jassen', 'le manteau', 'Doe je jas aan.', 'Mets ton manteau.');
n('broek', 'de', 'broeken', 'le pantalon', 'Deze broek is te lang.', 'Ce pantalon est trop long.');
n('rok', 'de', 'rokken', 'la jupe', 'Zij draagt een rok.', 'Elle porte une jupe.');
n('jurk', 'de', 'jurken', 'la robe', 'Wat een mooie jurk!', 'Quelle belle robe !');
n('trui', 'de', 'truien', 'le pull', 'Het is koud, neem een trui.', 'Il fait froid, prends un pull.');
n('shirt', 'het', 'shirts', 'le t-shirt', 'Een wit shirt.', 'Un t-shirt blanc.');
n('schoen', 'de', 'schoenen', 'la chaussure', 'Mijn schoenen zijn nieuw.', 'Mes chaussures sont neuves.');
n('sok', 'de', 'sokken', 'la chaussette', 'Ik zoek mijn sokken.', 'Je cherche mes chaussettes.');
n('hoed', 'de', 'hoeden', 'le chapeau', 'Opa draagt een hoed.', 'Grand-père porte un chapeau.');
n('muts', 'de', 'mutsen', 'le bonnet', 'In de winter draag ik een muts.', 'En hiver, je porte un bonnet.');
n('sjaal', 'de', 'sjaals', 'l’écharpe', 'Neem een sjaal mee.', 'Prends une écharpe.');
n('kleren', 'de', null, 'les vêtements', 'Ik koop nieuwe kleren.', 'J’achète de nouveaux vêtements.');
n('maat', 'de', 'maten', 'la taille', 'Welke maat heeft u?', 'Quelle taille faites-vous ?');
n('kleur', 'de', 'kleuren', 'la couleur', 'Wat is je lievelingskleur?', 'Quelle est ta couleur préférée ?');
v('dragen', 'porter', 'Ik draag een bril.', 'Je porte des lunettes.');
v('aantrekken', 'mettre (un vêtement)', 'Trek je jas aan.', 'Mets ton manteau.');
v('passen', 'essayer / aller (taille)', 'Mag ik deze broek passen?', 'Puis-je essayer ce pantalon ?');
j('rood', 'rouge', 'De appel is rood.', 'La pomme est rouge.');
j('blauw', 'bleu', 'De lucht is blauw.', 'Le ciel est bleu.');
j('groen', 'vert', 'Het gras is groen.', 'L’herbe est verte.');
j('geel', 'jaune', 'De banaan is geel.', 'La banane est jaune.');
j('zwart', 'noir', 'Een zwarte jas.', 'Un manteau noir.');
j('wit', 'blanc', 'De muur is wit.', 'Le mur est blanc.');
j('grijs', 'gris', 'Het weer is grijs.', 'Le temps est gris.');
j('bruin', 'marron', 'Bruin brood is gezond.', 'Le pain complet est sain.');
j('oranje', 'orange', 'Op Koningsdag dragen we oranje.', 'À la fête du Roi, nous portons de l’orange.');
j('roze', 'rose', 'Een roze jurk.', 'Une robe rose.');
j('mooi', 'beau', 'Wat een mooie tas!', 'Quel beau sac !');
j('nieuw', 'neuf, nouveau', 'Ik heb een nieuwe telefoon.', 'J’ai un nouveau téléphone.');

T('Temps & calendrier');
n('dag', 'de', 'dagen', 'le jour', 'Een week heeft zeven dagen.', 'Une semaine a sept jours.');
n('maand', 'de', 'maanden', 'le mois', 'Ik woon hier al drie maanden.', 'J’habite ici depuis trois mois.');
n('uur', 'het', 'uren', 'l’heure', 'Het is drie uur.', 'Il est trois heures.');
n('minuut', 'de', 'minuten', 'la minute', 'Wacht vijf minuten.', 'Attends cinq minutes.');
n('middag', 'de', 'middagen', 'l’après-midi', 'Tot vanmiddag!', 'À cet après-midi !');
n('nacht', 'de', 'nachten', 'la nuit', 'Goede nacht!', 'Bonne nuit !');
n('weekend', 'het', 'weekenden', 'le week-end', 'Fijn weekend!', 'Bon week-end !');
n('vakantie', 'de', 'vakanties', 'les vacances', 'In juli heb ik vakantie.', 'En juillet, je suis en vacances.');
n('lente', 'de', null, 'le printemps', 'In de lente zijn er bloemen.', 'Au printemps, il y a des fleurs.');
n('zomer', 'de', 'zomers', 'l’été', 'De zomer is warm.', 'L’été est chaud.');
n('herfst', 'de', null, 'l’automne', 'In de herfst regent het veel.', 'En automne, il pleut beaucoup.');
n('winter', 'de', 'winters', 'l’hiver', 'In de winter is het koud.', 'En hiver, il fait froid.');
n('kalender', 'de', 'kalenders', 'le calendrier', 'Kijk op de kalender.', 'Regarde le calendrier.');
n('datum', 'de', 'data', 'la date', 'Wat is de datum vandaag?', 'Quelle est la date aujourd’hui ?');
n('klok', 'de', 'klokken', 'l’horloge', 'De klok is stil.', 'L’horloge est arrêtée.');
n('kwartier', 'het', 'kwartieren', 'le quart d’heure', 'Over een kwartier.', 'Dans un quart d’heure.');
a('maandag', 'lundi', 'Op maandag werk ik.', 'Le lundi, je travaille.');
a('dinsdag', 'mardi', 'Dinsdag ga ik naar de les.', 'Mardi, je vais au cours.');
a('woensdag', 'mercredi', 'Woensdagmiddag zijn de kinderen vrij.', 'Le mercredi après-midi, les enfants sont libres.');
a('donderdag', 'jeudi', 'Donderdag is de markt.', 'Jeudi, c’est le marché.');
a('vrijdag', 'vendredi', 'Vrijdag eten we vis.', 'Vendredi, nous mangeons du poisson.');
a('zaterdag', 'samedi', 'Zaterdag doe ik boodschappen.', 'Samedi, je fais les courses.');
a('zondag', 'dimanche', 'Zondag rust ik uit.', 'Dimanche, je me repose.');
a('januari', 'janvier', 'In januari is het koud.', 'En janvier, il fait froid.');
a('februari', 'février', 'Februari is een korte maand.', 'Février est un mois court.');
a('maart', 'mars', 'In maart begint de lente.', 'En mars commence le printemps.');
a('april', 'avril', 'Koningsdag is in april.', 'La fête du Roi est en avril.');
a('mei', 'mai', 'Op 5 mei is Bevrijdingsdag.', 'Le 5 mai, c’est la fête de la Libération.');
a('juni', 'juin', 'In juni is het warm.', 'En juin, il fait chaud.');
a('juli', 'juillet', 'In juli is de zomervakantie.', 'En juillet, ce sont les vacances d’été.');
a('augustus', 'août', 'In augustus ga ik op reis.', 'En août, je pars en voyage.');
a('september', 'septembre', 'In september begint de school.', 'En septembre, l’école reprend.');
a('oktober', 'octobre', 'In oktober vallen de bladeren.', 'En octobre, les feuilles tombent.');
a('november', 'novembre', 'November is grijs.', 'Novembre est gris.');
a('december', 'décembre', 'In december is Sinterklaas.', 'En décembre, c’est la Saint-Nicolas.');
b('nu', 'maintenant', 'Ik kom nu.', 'J’arrive maintenant.');
b('straks', 'tout à l’heure', 'Tot straks!', 'À tout à l’heure !');
b('altijd', 'toujours', 'Hij is altijd op tijd.', 'Il est toujours à l’heure.');
b('nooit', 'jamais', 'Ik rook nooit.', 'Je ne fume jamais.');
b('soms', 'parfois', 'Soms fiets ik naar mijn werk.', 'Parfois, je vais au travail à vélo.');
b('vaak', 'souvent', 'Het regent vaak.', 'Il pleut souvent.');
a('elke dag', 'chaque jour', 'Ik leer elke dag Nederlands.', 'J’apprends le néerlandais chaque jour.');
a('op tijd', 'à l’heure', 'Kom op tijd!', 'Viens à l’heure !');
a('volgende week', 'la semaine prochaine', 'Volgende week heb ik vakantie.', 'La semaine prochaine, je suis en vacances.');
b('vanavond', 'ce soir', 'Vanavond kook ik.', 'Ce soir, je cuisine.');

T('Nombres');
a('één', 'un', 'Ik heb één kind.', 'J’ai un enfant.');
a('twee', 'deux', 'Twee koffie, alstublieft.', 'Deux cafés, s’il vous plaît.');
a('drie', 'trois', 'Ik woon hier al drie jaar.', 'J’habite ici depuis trois ans.');
a('vier', 'quatre', 'De les duurt vier uur.', 'Le cours dure quatre heures.');
a('vijf', 'cinq', 'Het kost vijf euro.', 'Ça coûte cinq euros.');
a('zes', 'six', 'We eten om zes uur.', 'Nous mangeons à six heures.');
a('zeven', 'sept', 'Een week heeft zeven dagen.', 'Une semaine a sept jours.');
a('acht', 'huit', 'De school begint om acht uur.', 'L’école commence à huit heures.');
a('negen', 'neuf', 'Bus negen komt eraan.', 'Le bus neuf arrive.');
a('tien', 'dix', 'Tien minuten wachten.', 'Attendre dix minutes.');
a('elf', 'onze', 'Mijn dochter is elf.', 'Ma fille a onze ans.');
a('twaalf', 'douze', 'Om twaalf uur eten we.', 'À midi, nous mangeons.');
a('vijftien', 'quinze', 'Het is vijftien graden.', 'Il fait quinze degrés.');
a('twintig', 'vingt', 'Ik ben twintig jaar.', 'J’ai vingt ans.');
a('dertig', 'trente', 'Hij is dertig jaar.', 'Il a trente ans.');
a('veertig', 'quarante', 'Veertig euro, alstublieft.', 'Quarante euros, s’il vous plaît.');
a('vijftig', 'cinquante', 'Mijn vader is vijftig.', 'Mon père a cinquante ans.');
a('honderd', 'cent', 'Honderd procent!', 'Cent pour cent !');
a('duizend', 'mille', 'Duizend euro is veel geld.', 'Mille euros, c’est beaucoup d’argent.');
a('eerste', 'premier', 'Dit is mijn eerste les.', 'C’est mon premier cours.');
a('tweede', 'deuxième', 'Ik woon op de tweede verdieping.', 'J’habite au deuxième étage.');
a('half', 'demi / et demie', 'Het is half drie.', 'Il est deux heures et demie.');
a('kwart over', 'et quart', 'Het is kwart over vier.', 'Il est quatre heures et quart.');
a('kwart voor', 'moins le quart', 'Het is kwart voor zes.', 'Il est six heures moins le quart.');
a('veel', 'beaucoup', 'Ik heb veel werk.', 'J’ai beaucoup de travail.');
a('weinig', 'peu', 'Ik heb weinig tijd.', 'J’ai peu de temps.');
a('een beetje', 'un peu', 'Ik spreek een beetje Nederlands.', 'Je parle un peu néerlandais.');

T('Ville & transports');
n('stad', 'de', 'steden', 'la ville', 'Utrecht is een mooie stad.', 'Utrecht est une belle ville.');
n('dorp', 'het', 'dorpen', 'le village', 'Mijn oma woont in een dorp.', 'Ma grand-mère habite dans un village.');
n('centrum', 'het', 'centra', 'le centre', 'De winkel is in het centrum.', 'Le magasin est dans le centre.');
n('plein', 'het', 'pleinen', 'la place', 'We wachten op het plein.', 'Nous attendons sur la place.');
n('brug', 'de', 'bruggen', 'le pont', 'Fiets over de brug.', 'Traverse le pont à vélo.');
n('kerk', 'de', 'kerken', 'l’église', 'De kerk is oud.', 'L’église est vieille.');
n('moskee', 'de', 'moskeeën', 'la mosquée', 'De moskee is dichtbij.', 'La mosquée est tout près.');
n('park', 'het', 'parken', 'le parc', 'De kinderen spelen in het park.', 'Les enfants jouent au parc.');
n('bushalte', 'de', 'bushaltes', 'l’arrêt de bus', 'De bushalte is om de hoek.', 'L’arrêt de bus est au coin.');
n('tram', 'de', 'trams', 'le tram', 'Ik neem de tram.', 'Je prends le tram.');
n('metro', 'de', 'metro’s', 'le métro', 'De metro is snel.', 'Le métro est rapide.');
n('taxi', 'de', 'taxi’s', 'le taxi', 'Ik bel een taxi.', 'J’appelle un taxi.');
n('vliegtuig', 'het', 'vliegtuigen', 'l’avion', 'Het vliegtuig vertrekt om tien uur.', 'L’avion part à dix heures.');
n('vliegveld', 'het', 'vliegvelden', 'l’aéroport', 'Ik ga naar het vliegveld.', 'Je vais à l’aéroport.');
n('kaartje', 'het', 'kaartjes', 'le billet', 'Een kaartje naar Utrecht, alstublieft.', 'Un billet pour Utrecht, s’il vous plaît.');
n('spoor', 'het', 'sporen', 'la voie (quai)', 'De trein vertrekt van spoor 5.', 'Le train part de la voie 5.');
n('vertraging', 'de', 'vertragingen', 'le retard', 'De bus heeft vertraging.', 'Le bus a du retard.');
n('weg', 'de', 'wegen', 'la route, le chemin', 'Weet u de weg?', 'Connaissez-vous le chemin ?');
n('hoek', 'de', 'hoeken', 'le coin', 'Ga rechtsaf op de hoek.', 'Tournez à droite au coin.');
n('kruispunt', 'het', 'kruispunten', 'le carrefour', 'Stop bij het kruispunt.', 'Arrête-toi au carrefour.');
n('fietspad', 'het', 'fietspaden', 'la piste cyclable', 'Fiets op het fietspad.', 'Roule sur la piste cyclable.');
n('stoep', 'de', 'stoepen', 'le trottoir', 'Loop op de stoep.', 'Marche sur le trottoir.');
n('parkeerplaats', 'de', 'parkeerplaatsen', 'la place de parking', 'Er is geen parkeerplaats.', 'Il n’y a pas de place de parking.');
n('kaart', 'de', 'kaarten', 'la carte, le plan', 'Kijk op de kaart.', 'Regarde sur le plan.');
n('post', 'de', null, 'le courrier, la poste', 'Is er post voor mij?', 'Y a-t-il du courrier pour moi ?');
n('pakket', 'het', 'pakketten', 'le colis', 'Ik wacht op een pakket.', 'J’attends un colis.');
v('lopen', 'marcher', 'Ik loop naar school.', 'Je vais à l’école à pied.');
v('fietsen', 'faire du vélo', 'Ik fiets elke dag.', 'Je fais du vélo tous les jours.');
v('vertrekken', 'partir', 'De trein vertrekt om acht uur.', 'Le train part à huit heures.');
v('aankomen', 'arriver', 'Hoe laat komt de bus aan?', 'À quelle heure arrive le bus ?');
v('instappen', 'monter (dans)', 'Stap hier in.', 'Montez ici.');
v('uitstappen', 'descendre (de)', 'Ik stap uit bij het station.', 'Je descends à la gare.');
v('overstappen', 'changer (de train)', 'U moet overstappen in Utrecht.', 'Vous devez changer à Utrecht.');
v('wachten', 'attendre', 'Ik wacht op de bus.', 'J’attends le bus.');
v('parkeren', 'se garer', 'Waar kan ik parkeren?', 'Où puis-je me garer ?');
v('oversteken', 'traverser', 'Steek hier over.', 'Traversez ici.');
b('rechtdoor', 'tout droit', 'Ga rechtdoor.', 'Allez tout droit.');
b('dichtbij', 'tout près', 'De winkel is dichtbij.', 'Le magasin est tout près.');
b('ver', 'loin', 'Het station is ver.', 'La gare est loin.');
b('hier', 'ici', 'Ik woon hier.', 'J’habite ici.');
b('daar', 'là-bas', 'De bus stopt daar.', 'Le bus s’arrête là-bas.');

T('Travail & école');
n('baan', 'de', 'banen', 'l’emploi, le poste', 'Ik zoek een baan.', 'Je cherche un emploi.');
n('werk', 'het', null, 'le travail', 'Ik ga naar mijn werk.', 'Je vais au travail.');
n('beroep', 'het', 'beroepen', 'le métier', 'Wat is uw beroep?', 'Quel est votre métier ?');
n('fabriek', 'de', 'fabrieken', 'l’usine', 'Hij werkt in een fabriek.', 'Il travaille dans une usine.');
n('bedrijf', 'het', 'bedrijven', 'l’entreprise', 'Het bedrijf is groot.', 'L’entreprise est grande.');
n('werkgever', 'de', 'werkgevers', 'l’employeur', 'Mijn werkgever is tevreden.', 'Mon employeur est satisfait.');
n('vacature', 'de', 'vacatures', 'l’offre d’emploi', 'Ik lees de vacature.', 'Je lis l’offre d’emploi.');
n('sollicitatie', 'de', 'sollicitaties', 'la candidature', 'Ik schrijf een sollicitatie.', 'J’écris une candidature.');
n('ervaring', 'de', 'ervaringen', 'l’expérience', 'Ik heb ervaring in de zorg.', 'J’ai de l’expérience dans le secteur des soins.');
n('computer', 'de', 'computers', 'l’ordinateur', 'Ik werk op de computer.', 'Je travaille sur l’ordinateur.');
n('telefoon', 'de', 'telefoons', 'le téléphone', 'Mijn telefoon is leeg.', 'Mon téléphone est déchargé.');
n('e-mail', 'de', 'e-mails', 'l’e-mail', 'Ik stuur een e-mail.', 'J’envoie un e-mail.');
n('kok', 'de', 'koks', 'le cuisinier', 'Hij is kok in een restaurant.', 'Il est cuisinier dans un restaurant.');
n('schoonmaker', 'de', 'schoonmakers', 'l’agent d’entretien', 'De schoonmaker komt om zes uur.', 'L’agent d’entretien vient à six heures.');
n('chauffeur', 'de', 'chauffeurs', 'le chauffeur', 'De chauffeur rijdt de bus.', 'Le chauffeur conduit le bus.');
n('les', 'de', 'lessen', 'le cours, la leçon', 'De les begint om negen uur.', 'Le cours commence à neuf heures.');
n('cursus', 'de', 'cursussen', 'le cours (formation)', 'Ik volg een cursus Nederlands.', 'Je suis un cours de néerlandais.');
n('huiswerk', 'het', null, 'les devoirs', 'Ik maak mijn huiswerk.', 'Je fais mes devoirs.');
n('pen', 'de', 'pennen', 'le stylo', 'Mag ik een pen?', 'Puis-je avoir un stylo ?');
n('papier', 'het', null, 'le papier', 'Een vel papier.', 'Une feuille de papier.');
n('woord', 'het', 'woorden', 'le mot', 'Wat betekent dit woord?', 'Que veut dire ce mot ?');
n('zin', 'de', 'zinnen', 'la phrase', 'Lees de zin.', 'Lis la phrase.');
n('antwoord', 'het', 'antwoorden', 'la réponse', 'Het antwoord is goed.', 'La réponse est bonne.');
n('examen', 'het', 'examens', 'l’examen', 'Ik doe volgende maand examen.', 'Je passe l’examen le mois prochain.');
n('diploma', 'het', 'diploma’s', 'le diplôme', 'Ik heb een diploma.', 'J’ai un diplôme.');
n('leerling', 'de', 'leerlingen', 'l’élève', 'De leerlingen luisteren.', 'Les élèves écoutent.');
n('student', 'de', 'studenten', 'l’étudiant', 'Zij is student.', 'Elle est étudiante.');
n('klas', 'de', 'klassen', 'la classe', 'Er zitten twintig kinderen in de klas.', 'Il y a vingt enfants dans la classe.');
v('beginnen', 'commencer', 'Het werk begint om acht uur.', 'Le travail commence à huit heures.');
v('stoppen', 'arrêter', 'Ik stop om vijf uur.', 'J’arrête à cinq heures.');
v('helpen', 'aider', 'Kunt u mij helpen?', 'Pouvez-vous m’aider ?');
v('vragen', 'demander', 'Mag ik iets vragen?', 'Puis-je demander quelque chose ?');
v('antwoorden', 'répondre', 'Antwoord in een hele zin.', 'Répondez par une phrase complète.');
v('luisteren', 'écouter', 'Luister goed.', 'Écoute bien.');
v('spreken', 'parler', 'Ik spreek Frans.', 'Je parle français.');
v('praten', 'parler, discuter', 'We praten over het werk.', 'Nous parlons du travail.');
v('zeggen', 'dire', 'Wat zegt u?', 'Que dites-vous ?');
v('oefenen', 'pratiquer, s’entraîner', 'Ik oefen elke dag.', 'Je m’entraîne chaque jour.');
v('herhalen', 'répéter', 'Kunt u dat herhalen?', 'Pouvez-vous répéter ?');
v('invullen', 'remplir', 'Vul het formulier in.', 'Remplissez le formulaire.');
v('studeren', 'étudier', 'Mijn zoon studeert in Leiden.', 'Mon fils étudie à Leyde.');
v('verdienen', 'gagner (de l’argent)', 'Hij verdient goed.', 'Il gagne bien sa vie.');
j('klaar', 'prêt, fini', 'Ik ben klaar.', 'J’ai fini.');
j('belangrijk', 'important', 'Dit is belangrijk.', 'C’est important.');
j('fout', 'faux', 'Het antwoord is fout.', 'La réponse est fausse.');
j('goed', 'juste, bien', 'Heel goed!', 'Très bien !');

T('Loisirs & météo');
n('weer', 'het', null, 'le temps (météo)', 'Wat voor weer is het?', 'Quel temps fait-il ?');
n('zon', 'de', null, 'le soleil', 'De zon schijnt.', 'Le soleil brille.');
n('regen', 'de', null, 'la pluie', 'Er komt regen.', 'La pluie arrive.');
n('wind', 'de', 'winden', 'le vent', 'Er is veel wind.', 'Il y a beaucoup de vent.');
n('sneeuw', 'de', null, 'la neige', 'Er ligt sneeuw.', 'Il y a de la neige.');
n('wolk', 'de', 'wolken', 'le nuage', 'Er zijn veel wolken.', 'Il y a beaucoup de nuages.');
n('graad', 'de', 'graden', 'le degré', 'Het is twintig graden.', 'Il fait vingt degrés.');
n('paraplu', 'de', 'paraplu’s', 'le parapluie', 'Neem een paraplu mee.', 'Prends un parapluie.');
n('hobby', 'de', 'hobby’s', 'le passe-temps', 'Mijn hobby is koken.', 'Mon passe-temps, c’est la cuisine.');
n('sport', 'de', 'sporten', 'le sport', 'Welke sport doe je?', 'Quel sport fais-tu ?');
n('voetbal', 'het', null, 'le football', 'Mijn zoon speelt voetbal.', 'Mon fils joue au football.');
n('zwembad', 'het', 'zwembaden', 'la piscine', 'We gaan naar het zwembad.', 'Nous allons à la piscine.');
n('strand', 'het', 'stranden', 'la plage', 'In de zomer gaan we naar het strand.', 'En été, nous allons à la plage.');
n('film', 'de', 'films', 'le film', 'We kijken een film.', 'Nous regardons un film.');
n('muziek', 'de', null, 'la musique', 'Ik luister naar muziek.', 'J’écoute de la musique.');
n('feest', 'het', 'feesten', 'la fête', 'Er is een feest bij de buren.', 'Il y a une fête chez les voisins.');
n('cadeau', 'het', 'cadeaus', 'le cadeau', 'Ik geef een cadeau.', 'J’offre un cadeau.');
n('krant', 'de', 'kranten', 'le journal', 'Opa leest de krant.', 'Grand-père lit le journal.');
n('televisie', 'de', 'televisies', 'la télévision', 'De televisie staat aan.', 'La télévision est allumée.');
n('foto', 'de', 'foto’s', 'la photo', 'Ik maak een foto.', 'Je prends une photo.');
n('reis', 'de', 'reizen', 'le voyage', 'Goede reis!', 'Bon voyage !');
n('hond', 'de', 'honden', 'le chien', 'De hond loopt in het park.', 'Le chien se promène au parc.');
n('kat', 'de', 'katten', 'le chat', 'De kat slaapt op de bank.', 'Le chat dort sur le canapé.');
n('bloem', 'de', 'bloemen', 'la fleur', 'Ik koop bloemen.', 'J’achète des fleurs.');
n('boom', 'de', 'bomen', 'l’arbre', 'De boom is hoog.', 'L’arbre est haut.');
n('bos', 'het', 'bossen', 'la forêt', 'We wandelen in het bos.', 'Nous nous promenons dans la forêt.');
n('zee', 'de', 'zeeën', 'la mer', 'De zee is koud.', 'La mer est froide.');
v('regenen', 'pleuvoir', 'Het regent.', 'Il pleut.');
v('sneeuwen', 'neiger', 'Het sneeuwt.', 'Il neige.');
v('schijnen', 'briller', 'De zon schijnt.', 'Le soleil brille.');
v('spelen', 'jouer', 'De kinderen spelen buiten.', 'Les enfants jouent dehors.');
v('zwemmen', 'nager', 'Ik zwem graag.', 'J’aime nager.');
v('wandelen', 'se promener', 'We wandelen in het park.', 'Nous nous promenons au parc.');
v('kijken', 'regarder', 'Ik kijk tv.', 'Je regarde la télé.');
v('dansen', 'danser', 'We dansen op het feest.', 'Nous dansons à la fête.');
v('reizen', 'voyager', 'Ik reis graag.', 'J’aime voyager.');
a('mooi weer', 'beau temps', 'Het is mooi weer.', 'Il fait beau.');
j('bewolkt', 'nuageux', 'Het is bewolkt.', 'Le temps est nuageux.');
j('nat', 'mouillé', 'Mijn jas is nat.', 'Mon manteau est mouillé.');
j('leuk', 'sympa, amusant', 'Het feest was leuk.', 'La fête était sympa.');
j('gezellig', 'convivial, agréable', 'Het is gezellig hier.', 'C’est agréable ici.');
b('graag', 'volontiers, aimer (faire)', 'Ik lees graag.', 'J’aime lire.');

T('Verbes courants');
v('zijn', 'être', 'Ik ben moe.', 'Je suis fatigué.');
v('hebben', 'avoir', 'Ik heb een vraag.', 'J’ai une question.');
v('gaan', 'aller', 'Ik ga naar huis.', 'Je rentre à la maison.');
v('komen', 'venir', 'Kom je morgen?', 'Tu viens demain ?');
v('doen', 'faire', 'Wat doe je?', 'Que fais-tu ?');
v('maken', 'faire, fabriquer', 'Ik maak eten.', 'Je prépare à manger.');
v('willen', 'vouloir', 'Ik wil koffie.', 'Je veux un café.');
v('kunnen', 'pouvoir, savoir', 'Kun je zwemmen?', 'Sais-tu nager ?');
v('moeten', 'devoir', 'Ik moet werken.', 'Je dois travailler.');
v('mogen', 'avoir le droit', 'Mag ik binnenkomen?', 'Puis-je entrer ?');
v('zien', 'voir', 'Ik zie de bus.', 'Je vois le bus.');
v('horen', 'entendre', 'Ik hoor muziek.', 'J’entends de la musique.');
v('weten', 'savoir', 'Ik weet het niet.', 'Je ne sais pas.');
v('denken', 'penser', 'Ik denk van wel.', 'Je pense que oui.');
v('vinden', 'trouver', 'Ik vind mijn sleutel niet.', 'Je ne trouve pas ma clé.');
v('geven', 'donner', 'Geef mij het boek.', 'Donne-moi le livre.');
v('krijgen', 'recevoir', 'Ik krijg een brief.', 'Je reçois une lettre.');
v('nemen', 'prendre', 'Neem een stoel.', 'Prends une chaise.');
v('brengen', 'apporter, emmener', 'Ik breng de kinderen naar school.', 'J’emmène les enfants à l’école.');
v('halen', 'aller chercher', 'Ik haal brood.', 'Je vais chercher du pain.');
v('zitten', 'être assis', 'Ik zit op de bank.', 'Je suis assis sur le canapé.');
v('staan', 'être debout, se trouver', 'De fiets staat buiten.', 'Le vélo est dehors.');
v('liggen', 'être couché, se trouver', 'Het boek ligt op tafel.', 'Le livre est sur la table.');
v('opstaan', 'se lever', 'Ik sta om zeven uur op.', 'Je me lève à sept heures.');
v('blijven', 'rester', 'Ik blijf thuis.', 'Je reste à la maison.');
v('leven', 'vivre', 'Ze leven in Nederland.', 'Ils vivent aux Pays-Bas.');
v('gebruiken', 'utiliser', 'Mag ik je telefoon gebruiken?', 'Puis-je utiliser ton téléphone ?');
v('beloven', 'promettre', 'Ik beloof het.', 'Je le promets.');
v('vergeten', 'oublier', 'Ik ben mijn tas vergeten.', 'J’ai oublié mon sac.');
v('onthouden', 'retenir', 'Onthoud dit woord.', 'Retiens ce mot.');
v('sturen', 'envoyer', 'Ik stuur een bericht.', 'J’envoie un message.');
v('ontvangen', 'recevoir', 'Heeft u mijn e-mail ontvangen?', 'Avez-vous reçu mon e-mail ?');
v('tekenen', 'dessiner / signer', 'Het kind tekent een huis.', 'L’enfant dessine une maison.');
v('bezoeken', 'rendre visite', 'Ik bezoek mijn oma.', 'Je rends visite à ma grand-mère.');
v('ontmoeten', 'rencontrer', 'Leuk je te ontmoeten!', 'Ravi de te rencontrer !');
v('feliciteren', 'féliciter', 'Ik feliciteer je!', 'Je te félicite !');
v('bedanken', 'remercier', 'Ik wil u bedanken.', 'Je voudrais vous remercier.');
v('wonen', 'habiter', 'Ik woon in Den Haag.', 'J’habite à La Haye.');
v('lenen', 'emprunter, prêter', 'Mag ik je pen lenen?', 'Puis-je emprunter ton stylo ?');
v('verliezen', 'perdre', 'Ik verlies altijd mijn sleutels.', 'Je perds toujours mes clés.');
v('pakken', 'prendre, attraper', 'Pak je jas.', 'Prends ton manteau.');
v('zetten', 'mettre, poser', 'Zet de fiets in de stalling.', 'Mets le vélo au parking à vélos.');
v('leggen', 'poser (à plat)', 'Leg het boek op tafel.', 'Pose le livre sur la table.');
v('rijden', 'conduire, rouler', 'De bus rijdt naar het centrum.', 'Le bus va au centre.');
v('vallen', 'tomber', 'Pas op, je valt!', 'Attention, tu vas tomber !');
v('roken', 'fumer', 'Hier mag je niet roken.', 'Ici, on ne peut pas fumer.');

T('Adjectifs & mots utiles');
j('snel', 'rapide, vite', 'De trein is snel.', 'Le train est rapide.');
j('langzaam', 'lent, lentement', 'Kunt u langzaam praten?', 'Pouvez-vous parler lentement ?');
j('hoog', 'haut', 'De flat is hoog.', 'L’immeuble est haut.');
j('laag', 'bas', 'De prijs is laag.', 'Le prix est bas.');
j('kort', 'court', 'De les is kort.', 'Le cours est court.');
j('breed', 'large', 'De weg is breed.', 'La route est large.');
j('zwaar', 'lourd, difficile', 'De tas is zwaar.', 'Le sac est lourd.');
j('licht', 'léger, clair', 'De tas is licht.', 'Le sac est léger.');
j('donker', 'sombre', 'Het is donker buiten.', 'Il fait noir dehors.');
j('stil', 'silencieux', 'Wees stil, alstublieft.', 'Silence, s’il vous plaît.');
j('druk', 'animé, occupé', 'Het is druk in de stad.', 'Il y a du monde en ville.');
j('leeg', 'vide', 'De fles is leeg.', 'La bouteille est vide.');
j('vol', 'plein', 'De bus is vol.', 'Le bus est plein.');
j('juist', 'correct, juste', 'Dat is juist.', 'C’est exact.');
j('mogelijk', 'possible', 'Is dat mogelijk?', 'Est-ce possible ?');
j('rustig', 'calme', 'Het is een rustige straat.', 'C’est une rue calme.');
j('beleefd', 'poli', 'Hij is heel beleefd.', 'Il est très poli.');
j('vriendelijk', 'aimable', 'De buurman is vriendelijk.', 'Le voisin est aimable.');
j('verkeerd', 'mauvais, erroné', 'Ik heb het verkeerde nummer.', 'J’ai le mauvais numéro.');
j('bekend', 'connu', 'Dit is een bekend liedje.', 'C’est une chanson connue.');
j('anders', 'différent, autrement', 'Het is hier anders.', 'C’est différent ici.');
b('samen', 'ensemble', 'We eten samen.', 'Nous mangeons ensemble.');
a('wat', 'que, quoi', 'Wat is dat?', 'Qu’est-ce que c’est ?');
a('wie', 'qui', 'Wie is dat?', 'Qui est-ce ?');
a('waar', 'où', 'Waar woont u?', 'Où habitez-vous ?');
a('wanneer', 'quand', 'Wanneer kom je?', 'Quand viens-tu ?');
a('waarom', 'pourquoi', 'Waarom ben je laat?', 'Pourquoi es-tu en retard ?');
a('hoe', 'comment', 'Hoe gaat het?', 'Comment ça va ?');
a('welke', 'quel, quelle', 'Welke bus gaat naar het station?', 'Quel bus va à la gare ?');
a('en', 'et', 'Brood en kaas.', 'Du pain et du fromage.');
a('of', 'ou', 'Koffie of thee?', 'Café ou thé ?');
a('maar', 'mais', 'Ik ben moe, maar blij.', 'Je suis fatigué, mais content.');
a('want', 'car', 'Ik blijf thuis, want ik ben ziek.', 'Je reste à la maison, car je suis malade.');
a('omdat', 'parce que', 'Ik kom niet, omdat ik ziek ben.', 'Je ne viens pas parce que je suis malade.');
a('als', 'si, quand', 'Als het regent, blijf ik thuis.', 'S’il pleut, je reste à la maison.');
a('met', 'avec', 'Ik ga met de bus.', 'J’y vais en bus.');
a('zonder', 'sans', 'Thee zonder suiker.', 'Du thé sans sucre.');
a('voor', 'pour, devant', 'Dit is voor jou.', 'C’est pour toi.');
a('na', 'après', 'Na het eten drink ik thee.', 'Après le repas, je bois du thé.');
a('tussen', 'entre', 'De bank staat tussen de winkels.', 'La banque est entre les magasins.');
a('naast', 'à côté de', 'Ik woon naast de school.', 'J’habite à côté de l’école.');
a('onder', 'sous', 'De kat ligt onder de tafel.', 'Le chat est sous la table.');
a('op', 'sur', 'Het boek ligt op de tafel.', 'Le livre est sur la table.');
a('in', 'dans', 'De melk is in de koelkast.', 'Le lait est dans le frigo.');
a('bij', 'chez, près de', 'Ik ben bij de dokter.', 'Je suis chez le médecin.');
a('naar', 'vers, à', 'Ik ga naar Amsterdam.', 'Je vais à Amsterdam.');
a('uit', 'de (provenance)', 'Ik kom uit Tunesië.', 'Je viens de Tunisie.');
b('ook', 'aussi', 'Ik wil ook koffie.', 'Moi aussi, je veux un café.');
a('niet', 'ne… pas', 'Ik weet het niet.', 'Je ne sais pas.');
a('geen', 'pas de', 'Ik heb geen auto.', 'Je n’ai pas de voiture.');
b('misschien', 'peut-être', 'Misschien kom ik morgen.', 'Peut-être que je viens demain.');
b('heel', 'très', 'Het is heel warm.', 'Il fait très chaud.');
b('te', 'trop', 'Het is te duur.', 'C’est trop cher.');
a('pardon', 'pardon, excusez-moi', 'Pardon, waar is het station?', 'Excusez-moi, où est la gare ?');
a('sorry', 'désolé', 'Sorry, ik ben te laat.', 'Désolé, je suis en retard.');
a('goedemorgen', 'bonjour (le matin)', 'Goedemorgen, meneer!', 'Bonjour, monsieur !');
a('goedemiddag', 'bonjour (l’après-midi)', 'Goedemiddag, mevrouw.', 'Bonjour, madame.');
a('goedenavond', 'bonsoir', 'Goedenavond allemaal!', 'Bonsoir à tous !');
a('meneer', 'monsieur', 'Dag meneer!', 'Au revoir, monsieur !');
a('mevrouw', 'madame', 'Mevrouw, uw tas!', 'Madame, votre sac !');
a('gefeliciteerd', 'félicitations, joyeux anniversaire', 'Gefeliciteerd met je verjaardag!', 'Joyeux anniversaire !');
a('prima', 'très bien, d’accord', 'Dat is prima.', 'C’est très bien.');
a('natuurlijk', 'bien sûr', 'Natuurlijk help ik je.', 'Bien sûr que je t’aide.');

T('Administration');
n('handtekening', 'de', 'handtekeningen', 'la signature', 'Zet hier uw handtekening.', 'Signez ici.');
n('geboortedatum', 'de', 'geboortedata', 'la date de naissance', 'Wat is uw geboortedatum?', 'Quelle est votre date de naissance ?');
n('nationaliteit', 'de', 'nationaliteiten', 'la nationalité', 'Wat is uw nationaliteit?', 'Quelle est votre nationalité ?');
n('telefoonnummer', 'het', 'telefoonnummers', 'le numéro de téléphone', 'Wat is uw telefoonnummer?', 'Quel est votre numéro de téléphone ?');
n('loket', 'het', 'loketten', 'le guichet', 'U kunt naar loket 2 gaan.', 'Vous pouvez aller au guichet 2.');
n('gemeentehuis', 'het', 'gemeentehuizen', 'la mairie', 'Het gemeentehuis is open.', 'La mairie est ouverte.');
n('identiteitsbewijs', 'het', 'identiteitsbewijzen', 'la pièce d’identité', 'Neem uw identiteitsbewijs mee.', 'Apportez votre pièce d’identité.');
n('uitnodiging', 'de', 'uitnodigingen', 'l’invitation, la convocation', 'Ik heb een uitnodiging gekregen.', 'J’ai reçu une convocation.');
n('aanvraag', 'de', 'aanvragen', 'la demande', 'Uw aanvraag is ontvangen.', 'Votre demande a été reçue.');
n('toeslag', 'de', 'toeslagen', 'l’aide financière', 'Ik vraag een toeslag aan.', 'Je demande une aide.');
n('uitkering', 'de', 'uitkeringen', 'l’allocation', 'Hij krijgt een uitkering.', 'Il reçoit une allocation.');
n('regel', 'de', 'regels', 'la règle', 'Dat is de regel.', 'C’est la règle.');
n('wet', 'de', 'wetten', 'la loi', 'Dat staat in de wet.', 'C’est dans la loi.');
n('overheid', 'de', null, 'l’État, les pouvoirs publics', 'De overheid helpt.', 'L’État aide.');
n('rechter', 'de', 'rechters', 'le juge', 'De rechter beslist.', 'Le juge décide.');
n('advocaat', 'de', 'advocaten', 'l’avocat', 'Ik heb een advocaat nodig.', 'J’ai besoin d’un avocat.');
n('noodgeval', 'het', 'noodgevallen', 'l’urgence', 'Bel 112 bij een noodgeval.', 'Appelle le 112 en cas d’urgence.');
n('brandweer', 'de', null, 'les pompiers', 'De brandweer komt snel.', 'Les pompiers arrivent vite.');
n('dief', 'de', 'dieven', 'le voleur', 'De dief is weg.', 'Le voleur est parti.');
n('ongeluk', 'het', 'ongelukken', 'l’accident', 'Er is een ongeluk gebeurd.', 'Il y a eu un accident.');
v('aanvragen', 'demander (officiellement)', 'Ik vraag een paspoort aan.', 'Je demande un passeport.');
v('inschrijven', 's’inscrire', 'Ik schrijf me in bij de gemeente.', 'Je m’inscris à la mairie.');
v('melden', 'signaler', 'Meld het bij de politie.', 'Signale-le à la police.');
v('stemmen', 'voter', 'Ik ga stemmen.', 'Je vais voter.');
v('verlengen', 'prolonger, renouveler', 'Ik moet mijn paspoort verlengen.', 'Je dois renouveler mon passeport.');
v('controleren', 'contrôler, vérifier', 'Controleer uw gegevens.', 'Vérifiez vos données.');
v('ondertekenen', 'signer', 'U moet hier ondertekenen.', 'Vous devez signer ici.');
j('geldig', 'valable', 'Uw paspoort is niet meer geldig.', 'Votre passeport n’est plus valable.');
j('verplicht', 'obligatoire', 'Een verzekering is verplicht.', 'Une assurance est obligatoire.');
j('verboden', 'interdit', 'Roken is hier verboden.', 'Il est interdit de fumer ici.');
j('officieel', 'officiel', 'Dit is een officiële brief.', 'C’est une lettre officielle.');
a('alstublieft', 's’il vous plaît / voici', 'Uw paspoort, alstublieft.', 'Votre passeport, s’il vous plaît.');

export const VOCAB_PLUS_ROWS = rows;
